import {redirect} from 'next/navigation';
import {revalidatePath} from 'next/cache';
import {DoniShell} from '@/components/DoniShell';
import {requirePageUser} from '@/lib/auth/session';
import {canAccessMarketing} from '@/lib/auth/marketing-access';
import {listMarketingCampaigns} from '@/lib/workspace/marketing-campaigns';
import {listMetaAdsAdSetConfigs,saveMetaAdsAdSetConfig} from '@/lib/workspace/meta-ads-adsets';
import {createPausedMetaCampaign,getMetaAdsStatus} from '@/services/facebook/ads';
import {createPausedMetaAdSet} from '@/services/facebook/adsets';
export const dynamic='force-dynamic';

function money(v:number,c:string){return `${Number(v||0).toFixed(2)} ${c||'USD'}`;}
export default async function Page({searchParams}:{searchParams?:Promise<Record<string,string|string[]|undefined>>}){
 const user=await requirePageUser('AGENT');if(!canAccessMarketing(user))redirect('/overview?forbidden=1');
 const params=searchParams?await searchParams:{};const ok=typeof params?.created==='string'?params.created:'';const adsetOk=typeof params?.adset_created==='string'?params.adset_created:'';const error=typeof params?.error==='string'?params.error:'';
 const [campaigns,status,configs]=await Promise.all([listMarketingCampaigns(),getMetaAdsStatus(),listMetaAdsAdSetConfigs()]);
 const items=campaigns.filter(c=>c.channel==='META_ADS');const configById=new Map(configs.map(x=>[x.campaignId,x]));
 async function createPaused(formData:FormData){'use server';const u=await requirePageUser('SUPER_ADMIN');const id=String(formData.get('id')||'');if(!id)redirect('/marketing/meta-ads-publisher?error=campaign_id_required');try{const r=await createPausedMetaCampaign(id,u.id);revalidatePath('/marketing/meta-ads-publisher');revalidatePath('/marketing/campaigns');redirect(`/marketing/meta-ads-publisher?created=${encodeURIComponent(r.remoteCampaignId||r.campaign.metaAds?.remoteCampaignId||'ok')}`);}catch(e){redirect(`/marketing/meta-ads-publisher?error=${encodeURIComponent(e instanceof Error?e.message:'meta_ads_publish_failed')}`);}}
 async function createAdSet(formData:FormData){'use server';const u=await requirePageUser('SUPER_ADMIN');const id=String(formData.get('id')||'');if(!id)redirect('/marketing/meta-ads-publisher?error=campaign_id_required');try{await saveMetaAdsAdSetConfig(id,{countries:String(formData.get('countries')||''),ageMin:Number(formData.get('ageMin')||18),ageMax:Number(formData.get('ageMax')||65),dailyBudget:Number(formData.get('dailyBudget')||0)},u.id);const r=await createPausedMetaAdSet(id,u.id);revalidatePath('/marketing/meta-ads-publisher');redirect(`/marketing/meta-ads-publisher?adset_created=${encodeURIComponent(r.remoteAdSetId||r.config.remoteAdSetId||'ok')}`);}catch(e){redirect(`/marketing/meta-ads-publisher?error=${encodeURIComponent(e instanceof Error?e.message:'meta_ads_adset_failed')}`);}}
 return <DoniShell title="Meta Ads Publisher" active="/marketing/meta-ads-publisher" user={user}>
  <section className="workspaceWelcome"><div><span className="workspaceKicker">Meta Ads · Exécution contrôlée</span><h2>Meta Ads Publisher</h2><p>DONI crée la campagne puis l’Ad Set uniquement en statut PAUSED. Aucune activation, aucune diffusion et aucune dépense automatique.</p></div></section>
  {ok?<div className="settingsMessage">✓ Campagne créée chez Meta en PAUSED · ID {ok}</div>:null}
  {adsetOk?<div className="settingsMessage">✓ Ad Set créé chez Meta en PAUSED · ID {adsetOk}</div>:null}
  {error?<div className="settingsMessage">⚠ Meta Ads : {error}</div>:null}
  <div className="marketingKpis"><div className="card"><span>OAuth Ads</span><strong>{status.connected?'Connecté':'Non connecté'}</strong></div><div className="card"><span>Ad Account</span><strong>{status.account?.name||status.adAccountId||'Non sélectionné'}</strong></div><div className="card"><span>Compte</span><strong>{status.account?.accountStatus===1?'Actif':'Non prêt'}</strong></div><div className="card"><span>Écriture Meta</span><strong>{status.writeEnabled?'AUTORISÉE':'OFF'}</strong></div></div>
  <section className="card publisherQueue"><div className="searchIntelHead"><div><span>Campagnes Meta Ads</span><h3>Campagne → Ad Set</h3></div><small>Tous les objets distants restent PAUSED</small></div>
   <div className="publisherRows">{items.map(c=>{const m=c.metaAds;const cfg=configById.get(c.id);const approved=m?.approvalStatus==='APPROVED'&&m.approvedAt&&m.approvedBy;return <article className="publisherRow" key={c.id} style={{alignItems:'start'}}><div><span className="publisherStatus">{cfg?.remoteAdSetId?'AD SET PAUSED':m?.remoteCampaignId?'META PAUSED':m?.approvalStatus||'DRAFT'}</span><h4>{c.name}</h4><small>{c.audience||'Audience à définir'} · budget préparé {money(c.budget,c.currency)}</small></div><div><span>Campagne Meta</span><strong>{m?.remoteCampaignId||'Pas encore créée'}</strong><small>{m?.remoteStatus||'Local uniquement'}</small>{!m?.remoteCampaignId&&approved&&user.role==='SUPER_ADMIN'?<form action={createPaused} style={{marginTop:8}}><input type="hidden" name="id" value={c.id}/><button className="primaryButton" type="submit" disabled={!status.writeEnabled||status.account?.accountStatus!==1}>Créer campagne Meta (PAUSED)</button></form>:null}</div><div><span>Ad Set</span><strong>{cfg?.remoteAdSetId||'Pas encore créé'}</strong><small>{cfg?.remoteStatus||'Audience/budget non publiés'}</small>{m?.remoteCampaignId&&!cfg?.remoteAdSetId&&user.role==='SUPER_ADMIN'?<form action={createAdSet} style={{display:'grid',gap:7,marginTop:8,minWidth:220}}><input type="hidden" name="id" value={c.id}/><label><small>Pays ISO-2</small><input name="countries" defaultValue={cfg?.countries?.join(',')||'MX'} placeholder="MX,US" required/></label><div style={{display:'flex',gap:6}}><label><small>Âge min</small><input type="number" name="ageMin" min="18" max="65" defaultValue={cfg?.ageMin||18} required style={{width:75}}/></label><label><small>Âge max</small><input type="number" name="ageMax" min="18" max="65" defaultValue={cfg?.ageMax||65} required style={{width:75}}/></label></div><label><small>Budget quotidien ({status.account?.currency||c.currency})</small><input type="number" name="dailyBudget" min="0.01" step="0.01" defaultValue={cfg?.dailyBudget||Math.max(1,c.budget||1)} required/></label><button className="primaryButton" type="submit" disabled={!status.writeEnabled||status.account?.accountStatus!==1}>Créer Ad Set (PAUSED)</button></form>:null}</div><div><span>Sécurité</span><strong>Aucune activation</strong><small>{cfg?.remoteAdSetId?`${cfg.countries.join(', ')} · ${cfg.ageMin}-${cfg.ageMax} ans · ${money(cfg.dailyBudget,status.account?.currency||c.currency)}/jour`:'Le créatif sera ajouté dans l’étape suivante.'}</small></div></article>})}{!items.length?<p className="muted">Aucune campagne Meta Ads.</p>:null}</div>
  </section>
 </DoniShell>;
}
