import {createHash} from 'crypto';import {getSetting} from '@/lib/settings/service';import type {FlightCriteria,FlightOffer,ProviderSearchResult} from '@/services/flights/types';
function formatDateTime(v:any,date:string){const s=String(v||'').trim();if(!s)return `${date}T00:00:00`;if(/^\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}/.test(s))return s.replace(' ','T');const d=new Date(`${date} ${s}`);return Number.isNaN(d.getTime())?`${date}T00:00:00`:d.toISOString().slice(0,19);}
export async function searchGoogleFallback(c:FlightCriteria):Promise<ProviderSearchResult>{
 if(!(await getSetting<boolean>('flights.google_fallback_enabled')))return {offers:[],error:'google_fallback_disabled'};const key=await getSetting<string>('flights.rapidapi_key');if(!key)return {offers:[],error:'rapidapi_not_configured'};
 const q=new URLSearchParams({departure_id:c.origin||'',arrival_id:c.destination||'',outbound_date:c.depart_date||'',adults:String(c.passengers?.adults||1)});if(c.trip_type==='roundtrip'&&c.return_date)q.set('return_date',c.return_date);
 try{const r=await fetch(`https://google-flights2.p.rapidapi.com/api/v1/searchFlights?${q}`,{headers:{'X-RapidAPI-Key':key,'X-RapidAPI-Host':'google-flights2.p.rapidapi.com'},signal:AbortSignal.timeout(20000)});const j:any=await r.json();if(!r.ok)return {offers:[],error:`google_http_${r.status}`};const it=j?.data?.itineraries||{};const list=[...(Array.isArray(it.topFlights)?it.topFlights:[]),...(Array.isArray(it.otherFlights)?it.otherFlights:[])].slice(0,15);const offers:FlightOffer[]=[];
 for(const [idx,f] of list.entries()){const legs=Array.isArray(f?.flights)?f.flights:[];const price=Number(f?.price||0);if(!legs.length||price<=0)continue;const segments=legs.map((leg:any)=>{const raw=String(leg.flight_number||'');const m=raw.match(/^([A-Z0-9]{2,3})\s*(\d+)$/i);return {airline_code:(m?.[1]||'').toUpperCase(),airline_name:String(leg.airline||''),flight_number:m?.[2]||raw,origin:String(leg?.departure_airport?.airport_code||c.origin||''),destination:String(leg?.arrival_airport?.airport_code||c.destination||''),departure_at:formatDateTime(leg?.departure_airport?.time,c.depart_date||''),arrival_at:formatDateTime(leg?.arrival_airport?.time,c.depart_date||''),duration_minutes:Number(leg?.duration?.raw||0)};});const id=createHash('sha1').update(`${c.origin}${c.destination}${c.depart_date}${idx}${JSON.stringify(f)}`).digest('hex');offers.push({offer_id:`google_gf_${id}`,provider:'google_fallback',price_total:price,currency:'USD',segments,_total_duration:Number(f?.duration?.raw||0),_stops:Number(f?.stops??Math.max(0,segments.length-1))});}
 return {offers};}catch(e){return {offers:[],error:e instanceof Error?e.message:'google_fallback_failed'};}
}
