import {redirect} from 'next/navigation';
import {DoniShell} from '@/components/DoniShell';
import {requirePageUser} from '@/lib/auth/session';
import {hasRole} from '@/lib/auth/permissions';
import {getProductivityOverview} from '@/services/workspace/productivity';
import {MetricCard} from '@/components/analytics/MetricCard';
import {AutoRefresh} from '@/components/analytics/AutoRefresh';
import {departmentLabel} from '@/lib/auth/departments';
export const dynamic='force-dynamic';
function loadLabel(score:number,overdue:number,blocked:number){if(blocked||overdue>=2)return 'À aider';if(score>=8)return 'Surchargé';if(score>=4)return 'Chargé';return 'Disponible'}
export default async function Page(){const user=await requirePageUser('ADMIN');if(!hasRole(user.role,'ADMIN'))redirect('/overview?forbidden=1');const d=await getProductivityOverview();return <DoniShell title="Productivité" active="/productivity" user={user}><AutoRefresh seconds={30}/><section className="workspaceWelcome"><div><span className="workspaceKicker">Supervision équipe</span><h2>Charge de travail & priorités</h2><p>Voir qui est disponible, surchargé, en retard ou bloqué afin de redistribuer le travail rapidement.</p></div></section><div className="grid"><MetricCard label="Tâches ouvertes" value={d.summary.open}/><MetricCard label="En retard" value={d.summary.overdue} tone={d.summary.overdue?'bad':'good'}/><MetricCard label="Bloquées" value={d.summary.blocked} tone={d.summary.blocked?'bad':'good'}/><MetricCard label="Non assignées" value={d.summary.unassigned} tone={d.summary.unassigned?'warn':'good'}/></div><h2 className="sectionTitle">Charge par collaborateur</h2><div className="card tableWrap"><table className="table"><thead><tr><th>Collaborateur</th><th>Département</th><th>Ouvertes</th><th>En cours</th><th>Aujourd'hui</th><th>Retard</th><th>Bloquées</th><th>Urgentes</th><th>Terminées aujourd'hui</th><th>Charge</th></tr></thead><tbody>{d.rows.map((r:any)=><tr key={r.id}><td><strong>{r.name}</strong><div className="muted" style={{fontSize:11}}>{r.role}</div></td><td>{r.department?departmentLabel(r.department):'Équipe générale'}</td><td>{r.open}</td><td>{r.inProgress}</td><td>{r.dueToday}</td><td><span className={`badge ${r.overdue?'badBadge':'ok'}`}>{r.overdue}</span></td><td>{r.blocked}</td><td>{r.urgent}</td><td>{r.doneToday}</td><td><span className={`badge ${r.blocked||r.overdue>=2?'badBadge':r.score>=8?'warn':'ok'}`}>{loadLabel(r.score,r.overdue,r.blocked)}</span></td></tr>)}</tbody></table></div><h2 className="sectionTitle">Charge par département</h2><div className="productivityDeptGrid">{d.departments.map((x:any)=><div className="card productivityDept" key={x.department}><strong>{departmentLabel(x.department)}</strong><div><span>Ouvertes</span><b>{x.open}</b></div><div><span>En retard</span><b>{x.overdue}</b></div><div><span>Bloquées</span><b>{x.blocked}</b></div><div><span>Urgentes</span><b>{x.urgent}</b></div></div>)}</div></DoniShell>}
