'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
type User={id:string;username:string;fullName:string|null;role:string};
type Message={id:string;direction:string;senderType:string;text:string|null;contentType:string;createdAt:string|Date;senderUser:{username:string;fullName:string|null}|null};
type Detail={id:string;waId:string;country:string|null;status:string;currentSegment:string;previousSegment:string|null;agentRequired:boolean;assignedAgent:User|null;state:any;messages:Message[];payments:any[];tickets:any[];lastMessageAt:string|Date|null};
export function ConversationViewer({initial,user}:{initial:Detail;user:User}){
 const [data,setData]=useState(initial);const [text,setText]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const bottom=useRef<HTMLDivElement|null>(null);
 const canSend=data.status==='AGENT_HOLD'&&(data.assignedAgent?.id===user.id||user.role!=='AGENT');
 async function refresh(){const r=await fetch(`/api/live-ops/conversations/${data.id}`,{cache:'no-store'});const j=await r.json();if(j.success)setData(j.conversation);}
 useEffect(()=>{const t=setInterval(refresh,8000);return()=>clearInterval(t)},[data.id]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth'})},[data.messages.length]);
 async function action(kind:'takeover'|'release'){setBusy(true);setError('');try{const r=await fetch(`/api/live-ops/conversations/${data.id}/${kind}`,{method:'POST'});const j=await r.json();if(!j.success)throw new Error(j.error||'action_failed');await refresh();}catch(e){setError(e instanceof Error?e.message:'Erreur');}finally{setBusy(false)}}
 async function send(){if(!text.trim())return;setBusy(true);setError('');try{const r=await fetch(`/api/live-ops/conversations/${data.id}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});const j=await r.json();if(!j.success)throw new Error(j.error||'send_failed');setText('');await refresh();}catch(e){setError(e instanceof Error?e.message:'Erreur');}finally{setBusy(false)}}
 const customer=useMemo(()=>{const s=data.state||{};return {email:s.contact_email||s.email||'—',phone:s.contact_phone||s.phone||data.waId,trip:s.trip_type||'—',origin:s.origin_iata||s.origin||'—',destination:s.destination_iata||s.destination||'—'}},[data]);
 return <div className="conversationLayout"><section className="card conversationPanel"><div className="conversationTop"><div><h2>{data.waId}</h2><div className="muted">{data.country||'Pays inconnu'} · <code>{data.currentSegment}</code></div></div><div className="conversationActions">{data.status!=='AGENT_HOLD'?<button className="btn primary" disabled={busy} onClick={()=>action('takeover')}>Prendre en charge</button>:<button className="btn" disabled={busy} onClick={()=>action('release')}>Rendre à DONI</button>}</div></div>{data.status==='AGENT_HOLD'&&<div className="holdBanner">Automatisation suspendue · Agent : <strong>{data.assignedAgent?.fullName||data.assignedAgent?.username||'assigné'}</strong></div>}<div className="messageStream">{data.messages.map(m=><div key={m.id} className={`messageRow ${m.senderType.toLowerCase()}`}><div className="messageBubble"><div className="messageMeta">{m.senderType==='CUSTOMER'?'Client':m.senderType==='BOT'?'DONI':m.senderType==='AGENT'?(m.senderUser?.fullName||m.senderUser?.username||'Agent'):'Système'} · {new Date(m.createdAt).toLocaleString('fr-FR')}</div><div>{m.text||`[${m.contentType}]`}</div></div></div>)}{data.messages.length===0&&<div className="emptyState">L’historique détaillé commencera avec les nouveaux messages reçus sur Vercel.</div>}<div ref={bottom}/></div><div className="composer"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={canSend?'Écrire au client…':'Prends d’abord la conversation en charge pour répondre.'} disabled={!canSend||busy} rows={3}/><button className="btn primary" onClick={send} disabled={!canSend||busy||!text.trim()}>Envoyer WhatsApp</button></div>{error&&<div className="loginError">{error}</div>}</section><aside className="conversationSide"><div className="card"><h3>Dossier client</h3><dl className="detailList"><dt>Téléphone</dt><dd>{customer.phone}</dd><dt>Email</dt><dd>{String(customer.email)}</dd><dt>Voyage</dt><dd>{String(customer.trip)}</dd><dt>Trajet</dt><dd>{String(customer.origin)} → {String(customer.destination)}</dd><dt>Étape actuelle</dt><dd><code>{data.currentSegment}</code></dd><dt>Étape précédente</dt><dd><code>{data.previousSegment||'—'}</code></dd></dl></div><div className="card"><h3>Paiements</h3>{data.payments.length?data.payments.map(p=><div className="sideRecord" key={p.id}><strong>{p.amount} {p.currency}</strong><span>{p.provider} · {p.status}</span></div>):<p className="muted">Aucun paiement.</p>}</div><div className="card"><h3>Tickets</h3>{data.tickets.length?data.tickets.map(t=><div className="sideRecord" key={t.id}><strong>{t.reference}</strong><span>{t.status}{t.pnr?` · PNR ${t.pnr}`:''}</span></div>):<p className="muted">Aucun ticket.</p>}</div></aside></div>
}
