'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';

type R={id:string;type:string;title:string;subtitle:string;meta?:string|null;href:string};
const labels:Record<string,string>={CLIENT:'Client',PAYMENT:'Paiement',TICKET:'Billet',POST_BOOKING:'Après-vente',FLIGHT:'Vol',TASK:'Tâche'};
export function GlobalSearch(){
 const[open,setOpen]=useState(false),[q,setQ]=useState(''),[rows,setRows]=useState<R[]>([]),[loading,setLoading]=useState(false),[selected,setSelected]=useState(-1);const input=useRef<HTMLInputElement>(null);const router=useRouter();
 function openSearch(){setOpen(true);setTimeout(()=>input.current?.focus(),0)}
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape')setOpen(false)};const onOpen=()=>openSearch();window.addEventListener('keydown',onKey);window.addEventListener('doni:open-search',onOpen);return()=>{window.removeEventListener('keydown',onKey);window.removeEventListener('doni:open-search',onOpen)}},[]);
 useEffect(()=>{setSelected(-1);if(!open||q.trim().length<2){setRows([]);setLoading(false);return}setLoading(true);const id=setTimeout(async()=>{try{const r=await fetch(`/api/workspace/search?q=${encodeURIComponent(q.trim())}`,{cache:'no-store'});const j=await r.json();const next=j.success?j.results||[]:[];setRows(next);setSelected(next.length?0:-1)}catch{setRows([]);setSelected(-1)}finally{setLoading(false)}},220);return()=>clearTimeout(id)},[q,open]);
 function close(){setOpen(false);setQ('');setRows([]);setSelected(-1)}
 function openSelected(){const row=rows[selected];if(!row)return;const href=row.href;close();router.push(href)}
 function onInputKeyDown(e:React.KeyboardEvent<HTMLInputElement>){if(!rows.length)return;if(e.key==='ArrowDown'){e.preventDefault();setSelected(i=>i<0?0:(i+1)%rows.length)}else if(e.key==='ArrowUp'){e.preventDefault();setSelected(i=>i<=0?rows.length-1:i-1)}else if(e.key==='Enter'&&selected>=0){e.preventDefault();openSelected()}}
 return <><button className="globalSearchTrigger" onClick={openSearch} aria-label="Recherche globale"><span>⌕</span><span className="globalSearchText">Rechercher</span><kbd>⌘K</kbd></button>{open?<div className="globalSearchBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="globalSearchDialog" role="dialog" aria-modal="true" aria-label="Recherche globale DONI"><div className="globalSearchInputRow"><span aria-hidden>⌕</span><input ref={input} autoFocus value={q} onChange={e=>setQ(e.target.value)} onKeyDown={onInputKeyDown} placeholder="Client, téléphone, PNR, billet, paiement, tâche…" role="combobox" aria-expanded={rows.length>0} aria-controls="global-search-results" aria-activedescendant={selected>=0?`global-search-option-${selected}`:undefined} aria-autocomplete="list" aria-label="Rechercher dans DONI"/><button onClick={close} aria-label="Fermer la recherche">Esc</button></div><div className="globalSearchResults" id="global-search-results" role="listbox" aria-label="Résultats de recherche">{q.trim().length<2?<div className="globalSearchHint"><strong>Recherche DONI</strong><span>Saisissez au moins 2 caractères. Vous pouvez rechercher un nom, téléphone, PNR, numéro de billet, référence ou tâche.</span></div>:loading?<div className="globalSearchHint" role="status">Recherche…</div>:rows.length?rows.map((r,i)=><Link href={r.href} key={`${r.type}:${r.id}`} id={`global-search-option-${i}`} role="option" aria-selected={i===selected} onMouseEnter={()=>setSelected(i)} onFocus={()=>setSelected(i)} onClick={close} className={`globalSearchResult ${i===selected?'selected':''}`}><span className={`globalSearchType type-${r.type.toLowerCase()}`}>{labels[r.type]||r.type}</span><div><strong>{r.title}</strong><span>{r.subtitle}</span></div><small>{r.meta||'Ouvrir'}</small><b aria-hidden>↗</b></Link>):<div className="globalSearchHint"><strong>Aucun résultat</strong><span>Essayez une référence, un téléphone, un PNR ou une partie du nom.</span></div>}</div><div className="globalSearchFooter"><span>↑ ↓ sélectionner</span><span>↵ ouvrir</span><span>Esc fermer</span><span>Ctrl/Cmd + K depuis n’importe quelle page</span></div></div></div>:null}</>;
}
