'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';

type R={id:string;type:string;title:string;subtitle:string;meta?:string|null;href:string};
const labels:Record<string,string>={CLIENT:'Client',PAYMENT:'Paiement',TICKET:'Billet',POST_BOOKING:'Après-vente',FLIGHT:'Vol',TASK:'Tâche'};
export function GlobalSearch(){
 const[open,setOpen]=useState(false),[q,setQ]=useState(''),[rows,setRows]=useState<R[]>([]),[loading,setLoading]=useState(false);const input=useRef<HTMLInputElement>(null);
 function openSearch(){setOpen(true);setTimeout(()=>input.current?.focus(),0)}
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape')setOpen(false)};const onOpen=()=>openSearch();window.addEventListener('keydown',onKey);window.addEventListener('doni:open-search',onOpen);return()=>{window.removeEventListener('keydown',onKey);window.removeEventListener('doni:open-search',onOpen)}},[]);
 useEffect(()=>{if(!open||q.trim().length<2){setRows([]);setLoading(false);return}setLoading(true);const id=setTimeout(async()=>{try{const r=await fetch(`/api/workspace/search?q=${encodeURIComponent(q.trim())}`,{cache:'no-store'});const j=await r.json();setRows(j.success?j.results||[]:[])}catch{setRows([])}finally{setLoading(false)}},220);return()=>clearTimeout(id)},[q,open]);
 function close(){setOpen(false);setQ('');setRows([])}
 return <><button className="globalSearchTrigger" onClick={openSearch} aria-label="Recherche globale"><span>⌕</span><span className="globalSearchText">Rechercher</span><kbd>⌘K</kbd></button>{open?<div className="globalSearchBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="globalSearchDialog"><div className="globalSearchInputRow"><span>⌕</span><input ref={input} autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Client, téléphone, PNR, billet, paiement, tâche…"/><button onClick={close}>Esc</button></div><div className="globalSearchResults">{q.trim().length<2?<div className="globalSearchHint"><strong>Recherche DONI</strong><span>Saisissez au moins 2 caractères. Vous pouvez rechercher un nom, téléphone, PNR, numéro de billet, référence ou tâche.</span></div>:loading?<div className="globalSearchHint">Recherche…</div>:rows.length?rows.map(r=><Link href={r.href} key={`${r.type}:${r.id}`} onClick={close} className="globalSearchResult"><span className={`globalSearchType type-${r.type.toLowerCase()}`}>{labels[r.type]||r.type}</span><div><strong>{r.title}</strong><span>{r.subtitle}</span></div><small>{r.meta||'Ouvrir'}</small><b>↗</b></Link>):<div className="globalSearchHint"><strong>Aucun résultat</strong><span>Essayez une référence, un téléphone, un PNR ou une partie du nom.</span></div>}</div><div className="globalSearchFooter"><span>↵ ouvrir</span><span>Esc fermer</span><span>Ctrl/Cmd + K depuis n’importe quelle page</span></div></div></div>:null}</>;
}
