'use client';
import {useEffect,useMemo,useState} from 'react';
type Campaign={id:string;name:string;channel:string;status:string;objective?:string|null;audience?:string|null;destination?:string|null;startAt?:string|null;endAt?:string|null;budget:number;currency:string;spend:number;leads:number;sales:number;revenue:number;ownerId?:string|null;ownerName?:string|null;notes?:string|null};
type User={id:string;username:string;fullName?:string|null};
type MetaAdAccount={id:string;name:string;accountStatus:number|null;currency:string|null;timezoneName:string|null};
type MetaAdsStatus={connected:boolean;configured:boolean;writeEnabled:boolean;businessId:string|null;adAccountId:string|null;account:MetaAdAccount|null;error:string|null};
const channels=[['META_ADS','Meta Ads'],['GOOGLE_ADS','Google Ads'],['WHATSAPP','WhatsApp'],['ORGANIC','Organique'],['INFLUENCER','Influenceur'],['FIELD','Terrain'],['OTHER','Autre']];
const statuses=[['DRAFT','Brouillon'],['PLANNED','Planifiée'],['ACTIVE','Active'],['PAUSED','En pause'],['COMPLETED','Terminée'],['CANCELLED','Annulée']];
function metrics(c:Campaign){return {cpl:c.leads?c.spend/c.leads:null,cac:c.sales?c.spend/c.sales:null,roas:c.spend?c.revenue/c.spend:null,roi:c.spend?((c.revenue-c.spend)/c.spend)*100:null,conv:c.leads?(c.sales/c.leads)*100:null}}
function money(v:number,c:string){return `${Number(v||0).toFixed(2)} ${c||'USD'}`}
function accountStatus(v:number|null|undefined){return v===1?'Actif':v==null?'—':`Statut ${v}`}
export function MarketingCampaigns(){
 const[campaigns,setCampaigns]=useState<Campaign[]>([]),[users,setUsers]=useState<User[]>([]),[show,setShow]=useState(false),[form,setForm]=useState<any>({name:'',channel:'META_ADS',status:'DRAFT',budget:0,currency:'USD',spend:0,leads:0,sales:0,revenue:0});
 const[metaStatus,setMetaStatus]=useState<MetaAdsStatus|null>(null),[metaAccounts,setMetaAccounts]=useState<MetaAdAccount[]>([]),[metaLoading,setMetaLoading]=useState(false),[metaMessage,setMetaMessage]=useState('');
 async function load(){const[r,m]=await Promise.all([fetch('/api/workspace/marketing/campaigns',{cache:'no-store'}),fetch('/api/workspace/marketing/meta-ads',{cache:'no-store'})]);const j=await r.json();if(j.success){setCampaigns(j.campaigns||[]);setUsers(j.users||[])}const mj=await m.json().catch(()=>({}));if(mj.success){setMetaStatus(mj.status);setMetaAccounts(mj.accounts||[])}}
 useEffect(()=>{load()},[]);
 async function refreshMeta(){setMetaLoading(true);setMetaMessage('');try{const r=await fetch('/api/workspace/marketing/meta-ads',{cache:'no-store'});const j=await r.json();if(j.success){setMetaStatus(j.status);setMetaAccounts(j.accounts||[]);setMetaMessage('Diagnostic Meta Ads actualisé.')}else setMetaMessage(j.error||'Diagnostic impossible.')}finally{setMetaLoading(false)}}
 async function selectMetaAccount(adAccountId:string){if(!adAccountId)return;setMetaLoading(true);const r=await fetch('/api/workspace/marketing/meta-ads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'select_account',adAccountId})});const j=await r.json();if(j.success){setMetaStatus(j.status);setMetaMessage('Compte publicitaire lié à DONI.')}else setMetaMessage(j.error||'Liaison impossible.');setMetaLoading(false)}
 async function setWriteEnabled(enabled:boolean){setMetaLoading(true);const r=await fetch('/api/workspace/marketing/meta-ads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'set_write_enabled',enabled})});const j=await r.json();if(j.success){setMetaStatus(j.status);setMetaMessage(enabled?'Lancement réel Meta Ads autorisé. Les campagnes restent soumises à approbation humaine.':'Lancement réel Meta Ads désactivé.')}else setMetaMessage(j.error||'Modification impossible.');setMetaLoading(false)}
 async function create(){const r=await fetch('/api/workspace/marketing/campaigns',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(j.success){setCampaigns([j.campaign,...campaigns]);setShow(false);setForm({name:'',channel:'META_ADS',status:'DRAFT',budget:0,currency:'USD',spend:0,leads:0,sales:0,revenue:0})}}
 async function patch(c:Campaign,data:Record<string,unknown>){const r=await fetch(`/api/workspace/marketing/campaigns/${c.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(data)});const j=await r.json();if(j.success)setCampaigns(prev=>prev.map(x=>x.id===c.id?j.campaign:x))}
 const totals=useMemo(()=>campaigns.reduce((a,c)=>({budget:a.budget+c.budget,spend:a.spend+c.spend,leads:a.leads+c.leads,sales:a.sales+c.sales,revenue:a.revenue+c.revenue}),{budget:0,spend:0,leads:0,sales:0,revenue:0}),[campaigns]);
 return <section className="mkCampaigns">
  <div className="mkCampaignTop"><div><span className="workspaceKicker">Acquisition payante & campagnes</span><h2>Campagnes & Ads</h2><p>Budgets, audiences, leads, ventes et rendement par campagne.</p></div><button className="btn primary" onClick={()=>setShow(!show)}>+ Nouvelle campagne</button></div>
  <div className="card" style={{marginBottom:16}}><div className="mkCampaignHead"><div><span>Meta Marketing API</span><h3>Connexion Meta Ads</h3><small>Connexion, sélection du compte publicitaire et garde-fou de dépense.</small></div><strong>{metaStatus?.connected?(metaStatus?.account?'Connecté':'OAuth connecté'):'Non connecté'}</strong></div>
   <div className="mkCampaignSummary"><div className="card"><span>OAuth Ads</span><strong>{metaStatus?.connected?'✓ Connecté':'À connecter'}</strong></div><div className="card"><span>Ad Account</span><strong>{metaStatus?.account?.name||metaStatus?.adAccountId||'Non sélectionné'}</strong><small>{metaStatus?.account?`${accountStatus(metaStatus.account.accountStatus)} · ${metaStatus.account.currency||'—'}`:''}</small></div><div className="card"><span>Lancement réel</span><strong>{metaStatus?.writeEnabled?'ACTIVÉ':'DÉSACTIVÉ'}</strong><small>Approbation humaine toujours obligatoire</small></div></div>
   <div style={{display:'flex',gap:10,flexWrap:'wrap',alignItems:'center'}}><a className="btn primary" href="/api/settings/facebook/ads/connect">Connecter Meta Ads</a><button className="btn" onClick={refreshMeta} disabled={metaLoading}>{metaLoading?'Vérification…':'Actualiser les comptes'}</button>{metaAccounts.length?<select value={metaStatus?.adAccountId||''} onChange={e=>selectMetaAccount(e.target.value)}><option value="">Choisir un Ad Account</option>{metaAccounts.map(a=><option key={a.id} value={a.id}>{a.name} — {a.id}</option>)}</select>:null}{metaStatus?.account?<label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" checked={Boolean(metaStatus.writeEnabled)} onChange={e=>setWriteEnabled(e.target.checked)} disabled={metaLoading}/> Autoriser le lancement réel Meta Ads</label>:null}</div>
   {metaMessage?<p className="muted">{metaMessage}</p>:null}{metaStatus?.error&&metaStatus.error!=='ad_account_missing'&&metaStatus.error!=='meta_ads_oauth_required'?<p className="muted">Meta : {metaStatus.error}</p>:null}<p className="muted">Sécurité DONI : aucune campagne ne doit être créée ou activée chez Meta tant que le garde-fou « lancement réel » est OFF.</p>
  </div>
  {show?<div className="card mkCampaignForm"><input placeholder="Nom de la campagne" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})}>{channels.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input placeholder="Destination / offre" value={form.destination||''} onChange={e=>setForm({...form,destination:e.target.value})}/><input placeholder="Audience cible" value={form.audience||''} onChange={e=>setForm({...form,audience:e.target.value})}/><input type="number" min="0" placeholder="Budget" value={form.budget} onChange={e=>setForm({...form,budget:Number(e.target.value)})}/><input placeholder="Devise" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}/><select value={form.ownerId||''} onChange={e=>setForm({...form,ownerId:e.target.value||null})}><option value="">Responsable</option>{users.map(u=><option key={u.id} value={u.id}>{u.fullName||u.username}</option>)}</select><button className="btn primary" onClick={create} disabled={!form.name.trim()}>Créer</button></div>:null}
  <div className="mkCampaignSummary"><div className="card"><span>Budget</span><strong>{money(totals.budget,campaigns[0]?.currency||'USD')}</strong></div><div className="card"><span>Dépensé</span><strong>{money(totals.spend,campaigns[0]?.currency||'USD')}</strong></div><div className="card"><span>Leads</span><strong>{totals.leads}</strong></div><div className="card"><span>Ventes</span><strong>{totals.sales}</strong></div><div className="card"><span>Revenu attribué</span><strong>{money(totals.revenue,campaigns[0]?.currency||'USD')}</strong></div></div>
  <div className="mkCampaignGrid">{campaigns.map(c=>{const m=metrics(c);return <article className="card mkCampaignCard" key={c.id}><div className="mkCampaignHead"><div><span>{channels.find(x=>x[0]===c.channel)?.[1]||c.channel}</span><h3>{c.name}</h3><small>{c.destination||'Offre générale'} · {c.ownerName||'Non assignée'}</small></div><select value={c.status} onChange={e=>patch(c,{status:e.target.value})}>{statuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="mkCampaignNumbers"><label>Budget<input type="number" value={c.budget} onChange={e=>patch(c,{budget:Number(e.target.value)})}/></label><label>Dépensé<input type="number" value={c.spend} onChange={e=>patch(c,{spend:Number(e.target.value)})}/></label><label>Leads<input type="number" value={c.leads} onChange={e=>patch(c,{leads:Number(e.target.value)})}/></label><label>Ventes<input type="number" value={c.sales} onChange={e=>patch(c,{sales:Number(e.target.value)})}/></label><label>Revenu<input type="number" value={c.revenue} onChange={e=>patch(c,{revenue:Number(e.target.value)})}/></label></div><div className="mkCampaignMetrics"><div><span>CPL</span><b>{m.cpl==null?'—':money(m.cpl,c.currency)}</b></div><div><span>CAC</span><b>{m.cac==null?'—':money(m.cac,c.currency)}</b></div><div><span>Conv.</span><b>{m.conv==null?'—':`${m.conv.toFixed(1)}%`}</b></div><div><span>ROAS</span><b>{m.roas==null?'—':`${m.roas.toFixed(2)}x`}</b></div><div><span>ROI</span><b>{m.roi==null?'—':`${m.roi.toFixed(1)}%`}</b></div></div><label className="mkCampaignOwner">Responsable<select value={c.ownerId||''} onChange={e=>patch(c,{ownerId:e.target.value||null})}><option value="">Non assigné</option>{users.map(u=><option key={u.id} value={u.id}>{u.fullName||u.username}</option>)}</select></label></article>})}{!campaigns.length?<div className="card portfolioEmpty">Aucune campagne créée.</div>:null}</div>
 </section>}
