'use client';
import {useEffect,useMemo,useState} from 'react';
type MetaAdsDraft={creativeText:string;destinationUrl?:string|null;callToAction:string;approvalStatus:'DRAFT'|'WAITING_APPROVAL'|'APPROVED'|'REJECTED';approvedBy?:string|null;approvedAt?:string|null;rejectedBy?:string|null;rejectedAt?:string|null;launchAllowed:boolean;remoteCampaignId?:string|null;remoteStatus?:string|null};
type Campaign={id:string;name:string;channel:string;status:string;objective?:string|null;audience?:string|null;destination?:string|null;startAt?:string|null;endAt?:string|null;budget:number;currency:string;spend:number;leads:number;sales:number;revenue:number;ownerId?:string|null;ownerName?:string|null;notes?:string|null;metaAds?:MetaAdsDraft|null};
type User={id:string;username:string;fullName?:string|null};
type MetaAdAccount={id:string;name:string;accountStatus:number|null;currency:string|null;timezoneName:string|null};
type MetaAdsStatus={connected:boolean;configured:boolean;writeEnabled:boolean;businessId:string|null;adAccountId:string|null;account:MetaAdAccount|null;error:string|null};
const channels=[['META_ADS','Meta Ads'],['GOOGLE_ADS','Google Ads'],['WHATSAPP','WhatsApp'],['ORGANIC','Organique'],['INFLUENCER','Influenceur'],['FIELD','Terrain'],['OTHER','Autre']];
const statuses=[['DRAFT','Brouillon'],['PLANNED','Planifiée'],['ACTIVE','Active'],['PAUSED','En pause'],['COMPLETED','Terminée'],['CANCELLED','Annulée']];
const ctas=[['LEARN_MORE','En savoir plus'],['BOOK_TRAVEL','Réserver'],['CONTACT_US','Nous contacter'],['GET_QUOTE','Obtenir un devis']];
function metrics(c:Campaign){return {cpl:c.leads?c.spend/c.leads:null,cac:c.sales?c.spend/c.sales:null,roas:c.spend?c.revenue/c.spend:null,roi:c.spend?((c.revenue-c.spend)/c.spend)*100:null,conv:c.leads?(c.sales/c.leads)*100:null}}
function money(v:number,c:string){return `${Number(v||0).toFixed(2)} ${c||'USD'}`}
function accountStatus(v:number|null|undefined){return v===1?'Actif':v==null?'—':`Statut ${v}`}
function approvalLabel(v:string|undefined){return ({DRAFT:'Brouillon Ads',WAITING_APPROVAL:'À approuver',APPROVED:'Approuvée',REJECTED:'Rejetée'} as Record<string,string>)[v||'DRAFT']||v||'Brouillon Ads'}
export function MarketingCampaigns({userRole}:{userRole:string}){
 const isAdmin=userRole==='ADMIN'||userRole==='SUPER_ADMIN';
 const emptyForm={name:'',channel:'META_ADS',status:'DRAFT',objective:'',destination:'',audience:'',budget:0,currency:'USD',spend:0,leads:0,sales:0,revenue:0,metaAds:{creativeText:'',destinationUrl:'',callToAction:'LEARN_MORE'}};
 const[campaigns,setCampaigns]=useState<Campaign[]>([]),[users,setUsers]=useState<User[]>([]),[show,setShow]=useState(false),[form,setForm]=useState<any>(emptyForm),[message,setMessage]=useState('');
 const[metaStatus,setMetaStatus]=useState<MetaAdsStatus|null>(null),[metaAccounts,setMetaAccounts]=useState<MetaAdAccount[]>([]),[metaLoading,setMetaLoading]=useState(false),[metaMessage,setMetaMessage]=useState('');
 async function load(){const[r,m]=await Promise.all([fetch('/api/workspace/marketing/campaigns',{cache:'no-store'}),fetch('/api/workspace/marketing/meta-ads',{cache:'no-store'})]);const j=await r.json();if(j.success){setCampaigns(j.campaigns||[]);setUsers(j.users||[])}const mj=await m.json().catch(()=>({}));if(mj.success){setMetaStatus(mj.status);setMetaAccounts(mj.accounts||[])}}
 useEffect(()=>{load()},[]);
 async function refreshMeta(){setMetaLoading(true);setMetaMessage('');try{const r=await fetch('/api/workspace/marketing/meta-ads',{cache:'no-store'});const j=await r.json();if(j.success){setMetaStatus(j.status);setMetaAccounts(j.accounts||[]);setMetaMessage('Diagnostic Meta Ads actualisé.')}else setMetaMessage(j.error||'Diagnostic impossible.')}finally{setMetaLoading(false)}}
 async function selectMetaAccount(adAccountId:string){if(!adAccountId)return;setMetaLoading(true);const r=await fetch('/api/workspace/marketing/meta-ads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'select_account',adAccountId})});const j=await r.json();if(j.success){setMetaStatus(j.status);setMetaMessage('Compte publicitaire lié à DONI.')}else setMetaMessage(j.error||'Liaison impossible.');setMetaLoading(false)}
 async function setWriteEnabled(enabled:boolean){setMetaLoading(true);const r=await fetch('/api/workspace/marketing/meta-ads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'set_write_enabled',enabled})});const j=await r.json();if(j.success){setMetaStatus(j.status);setMetaMessage(enabled?'Lancement réel Meta Ads autorisé. Les campagnes restent soumises à approbation humaine.':'Lancement réel Meta Ads désactivé.')}else setMetaMessage(j.error||'Modification impossible.');setMetaLoading(false)}
 async function create(){setMessage('');const r=await fetch('/api/workspace/marketing/campaigns',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(j.success){setCampaigns([j.campaign,...campaigns]);setShow(false);setForm(emptyForm);setMessage(form.channel==='META_ADS'?'Brouillon Meta Ads créé. Aucune dépense ni campagne Meta n’a été lancée.':'Campagne créée.')}else setMessage(j.error||'Création impossible.')}
 async function patch(c:Campaign,data:Record<string,unknown>){setMessage('');const r=await fetch(`/api/workspace/marketing/campaigns/${c.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(data)});const j=await r.json();if(j.success)setCampaigns(prev=>prev.map(x=>x.id===c.id?j.campaign:x));else setMessage(j.error||'Modification impossible.')}
 async function metaAction(c:Campaign,action:'meta_submit'|'meta_approve'|'meta_reject'){setMessage('');const r=await fetch(`/api/workspace/marketing/campaigns/${c.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action})});const j=await r.json();if(j.success){setCampaigns(prev=>prev.map(x=>x.id===c.id?j.campaign:x));setMessage(action==='meta_submit'?'Campagne soumise à approbation.':action==='meta_approve'?'Campagne approuvée. Elle n’est pas encore envoyée à Meta.':'Campagne rejetée.')}else setMessage(j.error||'Action impossible.')}
 const totals=useMemo(()=>campaigns.reduce((a,c)=>({budget:a.budget+c.budget,spend:a.spend+c.spend,leads:a.leads+c.leads,sales:a.sales+c.sales,revenue:a.revenue+c.revenue}),{budget:0,spend:0,leads:0,sales:0,revenue:0}),[campaigns]);
 return <section className="mkCampaigns">
  <div className="mkCampaignTop"><div><span className="workspaceKicker">Acquisition payante & campagnes</span><h2>Campagnes & Ads</h2><p>Budgets, audiences, leads, ventes et rendement par campagne.</p></div><button className="btn primary" onClick={()=>setShow(!show)}>+ Nouvelle campagne</button></div>
  {message?<div className="settingsMessage">{message}</div>:null}
  <div className="card" style={{marginBottom:16}}><div className="mkCampaignHead"><div><span>Meta Marketing API</span><h3>Connexion Meta Ads</h3><small>Connexion, sélection du compte publicitaire et garde-fou de dépense.</small></div><strong>{metaStatus?.connected?(metaStatus?.account?'Connecté':'OAuth connecté'):'Non connecté'}</strong></div>
   <div className="mkCampaignSummary"><div className="card"><span>OAuth Ads</span><strong>{metaStatus?.connected?'✓ Connecté':'À connecter'}</strong></div><div className="card"><span>Ad Account</span><strong>{metaStatus?.account?.name||metaStatus?.adAccountId||'Non sélectionné'}</strong><small>{metaStatus?.account?`${accountStatus(metaStatus.account.accountStatus)} · ${metaStatus.account.currency||'—'}`:''}</small></div><div className="card"><span>Lancement réel</span><strong>{metaStatus?.writeEnabled?'ACTIVÉ':'DÉSACTIVÉ'}</strong><small>Approbation humaine toujours obligatoire</small></div></div>
   <div style={{display:'flex',gap:10,flexWrap:'wrap',alignItems:'center'}}><a className="btn primary" href="/api/settings/facebook/ads/connect">Connecter Meta Ads</a><button className="btn" onClick={refreshMeta} disabled={metaLoading}>{metaLoading?'Vérification…':'Actualiser les comptes'}</button>{metaAccounts.length?<select value={metaStatus?.adAccountId||''} onChange={e=>selectMetaAccount(e.target.value)}><option value="">Choisir un Ad Account</option>{metaAccounts.map(a=><option key={a.id} value={a.id}>{a.name} — {a.id}</option>)}</select>:null}{metaStatus?.account&&userRole==='SUPER_ADMIN'?<label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" checked={Boolean(metaStatus.writeEnabled)} onChange={e=>setWriteEnabled(e.target.checked)} disabled={metaLoading}/> Autoriser le lancement réel Meta Ads</label>:null}</div>
   {metaMessage?<p className="muted">{metaMessage}</p>:null}{metaStatus?.error&&metaStatus.error!=='ad_account_missing'&&metaStatus.error!=='meta_ads_oauth_required'?<p className="muted">Meta : {metaStatus.error}</p>:null}<p className="muted">Sécurité DONI : aucune campagne ne doit être créée ou activée chez Meta tant que le garde-fou « lancement réel » est OFF.</p>
  </div>
  {show?<div className="card mkCampaignForm"><input placeholder="Nom de la campagne" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})}>{channels.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input placeholder="Objectif" value={form.objective||''} onChange={e=>setForm({...form,objective:e.target.value})}/><input placeholder="Destination / offre" value={form.destination||''} onChange={e=>setForm({...form,destination:e.target.value})}/><input placeholder="Audience cible" value={form.audience||''} onChange={e=>setForm({...form,audience:e.target.value})}/><input type="number" min="0" placeholder="Budget" value={form.budget} onChange={e=>setForm({...form,budget:Number(e.target.value)})}/><input placeholder="Devise" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}/>{form.channel==='META_ADS'?<><textarea rows={4} placeholder="Texte de la publicité" value={form.metaAds?.creativeText||''} onChange={e=>setForm({...form,metaAds:{...form.metaAds,creativeText:e.target.value}})}/><input placeholder="URL de destination" value={form.metaAds?.destinationUrl||''} onChange={e=>setForm({...form,metaAds:{...form.metaAds,destinationUrl:e.target.value}})}/><select value={form.metaAds?.callToAction||'LEARN_MORE'} onChange={e=>setForm({...form,metaAds:{...form.metaAds,callToAction:e.target.value}})}>{ctas.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></>:null}<select value={form.ownerId||''} onChange={e=>setForm({...form,ownerId:e.target.value||null})}><option value="">Responsable</option>{users.map(u=><option key={u.id} value={u.id}>{u.fullName||u.username}</option>)}</select><button className="btn primary" onClick={create} disabled={!form.name.trim()||(form.channel==='META_ADS'&&!String(form.metaAds?.creativeText||'').trim())}>Créer le brouillon</button></div>:null}
  <div className="mkCampaignSummary"><div className="card"><span>Budget</span><strong>{money(totals.budget,campaigns[0]?.currency||'USD')}</strong></div><div className="card"><span>Dépensé</span><strong>{money(totals.spend,campaigns[0]?.currency||'USD')}</strong></div><div className="card"><span>Leads</span><strong>{totals.leads}</strong></div><div className="card"><span>Ventes</span><strong>{totals.sales}</strong></div><div className="card"><span>Revenu attribué</span><strong>{money(totals.revenue,campaigns[0]?.currency||'USD')}</strong></div></div>
  <div className="mkCampaignGrid">{campaigns.map(c=>{const m=metrics(c),isMeta=c.channel==='META_ADS',approval=c.metaAds?.approvalStatus||'DRAFT';const allowedStatuses=isMeta?statuses.filter(x=>x[0]!=='ACTIVE'):statuses;return <article className="card mkCampaignCard" key={c.id}><div className="mkCampaignHead"><div><span>{channels.find(x=>x[0]===c.channel)?.[1]||c.channel}</span><h3>{c.name}</h3><small>{c.destination||'Offre générale'} · {c.ownerName||'Non assignée'}</small></div><select value={c.status} onChange={e=>patch(c,{status:e.target.value})}>{allowedStatuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>
   {isMeta?<div className="card" style={{margin:'12px 0',padding:14}}><div className="mkCampaignHead"><div><span>Contrôle Meta Ads</span><strong>{approvalLabel(approval)}</strong><small>{c.metaAds?.approvedBy?`Approuvée par ${c.metaAds.approvedBy}`:c.metaAds?.rejectedBy?`Rejetée par ${c.metaAds.rejectedBy}`:'Aucune approbation active'}</small></div><strong>{metaStatus?.writeEnabled?'Publisher autorisé':'Publisher OFF'}</strong></div><textarea rows={4} value={c.metaAds?.creativeText||''} disabled={approval==='WAITING_APPROVAL'} onChange={e=>patch(c,{metaAds:{...(c.metaAds||{}),creativeText:e.target.value}})}/><input style={{width:'100%',marginTop:8}} placeholder="URL de destination" value={c.metaAds?.destinationUrl||''} disabled={approval==='WAITING_APPROVAL'} onChange={e=>patch(c,{metaAds:{...(c.metaAds||{}),destinationUrl:e.target.value}})}/><select style={{marginTop:8}} value={c.metaAds?.callToAction||'LEARN_MORE'} disabled={approval==='WAITING_APPROVAL'} onChange={e=>patch(c,{metaAds:{...(c.metaAds||{}),callToAction:e.target.value}})}>{ctas.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}>{(approval==='DRAFT'||approval==='REJECTED')?<button className="btn primary" onClick={()=>metaAction(c,'meta_submit')}>Soumettre pour approbation</button>:null}{approval==='WAITING_APPROVAL'&&isAdmin?<><button className="btn primary" onClick={()=>metaAction(c,'meta_approve')}>Approuver</button><button className="btn" onClick={()=>metaAction(c,'meta_reject')}>Rejeter</button></>:null}{approval==='APPROVED'?<span className="muted">Approuvée — aucun lancement Meta automatique dans cette phase.</span>:null}</div></div>:null}
   <div className="mkCampaignNumbers"><label>Budget<input type="number" value={c.budget} onChange={e=>patch(c,{budget:Number(e.target.value)})}/></label><label>Dépensé<input type="number" value={c.spend} disabled={isMeta} onChange={e=>patch(c,{spend:Number(e.target.value)})}/></label><label>Leads<input type="number" value={c.leads} onChange={e=>patch(c,{leads:Number(e.target.value)})}/></label><label>Ventes<input type="number" value={c.sales} onChange={e=>patch(c,{sales:Number(e.target.value)})}/></label><label>Revenu<input type="number" value={c.revenue} onChange={e=>patch(c,{revenue:Number(e.target.value)})}/></label></div><div className="mkCampaignMetrics"><div><span>CPL</span><b>{m.cpl==null?'—':money(m.cpl,c.currency)}</b></div><div><span>CAC</span><b>{m.cac==null?'—':money(m.cac,c.currency)}</b></div><div><span>Conv.</span><b>{m.conv==null?'—':`${m.conv.toFixed(1)}%`}</b></div><div><span>ROAS</span><b>{m.roas==null?'—':`${m.roas.toFixed(2)}x`}</b></div><div><span>ROI</span><b>{m.roi==null?'—':`${m.roi.toFixed(1)}%`}</b></div></div><label className="mkCampaignOwner">Responsable<select value={c.ownerId||''} onChange={e=>patch(c,{ownerId:e.target.value||null})}><option value="">Non assigné</option>{users.map(u=><option key={u.id} value={u.id}>{u.fullName||u.username}</option>)}</select></label></article>})}{!campaigns.length?<div className="card portfolioEmpty">Aucune campagne créée.</div>:null}</div>
 </section>}
