import { redirect } from 'next/navigation';
import { DoniShell } from '@/components/DoniShell';
import { requirePageUser } from '@/lib/auth/session';
import { hasRole } from '@/lib/auth/permissions';
import { getFinanceMetrics } from '@/services/analytics/dashboard';
import { MetricCard } from '@/components/analytics/MetricCard';
import { Bar } from '@/components/analytics/Bar';
import { AutoRefresh } from '@/components/analytics/AutoRefresh';
export const dynamic='force-dynamic';
function money(n:number,c:string){try{return new Intl.NumberFormat('fr-FR',{style:'currency',currency:c,maximumFractionDigits:2}).format(n)}catch{return `${n.toFixed(2)} ${c}`}}
export default async function Page(){const user=await requirePageUser('AGENT');if(!hasRole(user.role,'ADMIN')&&user.department!=='FINANCE')redirect('/overview?forbidden=1');const d=await getFinanceMetrics();const paid=d.statusGroups.find(x=>x.status==='PAID')?.count||0,pending=d.statusGroups.find(x=>x.status==='PENDING')?.count||0,failed=(d.statusGroups.find(x=>x.status==='FAILED')?.count||0)+(d.statusGroups.find(x=>x.status==='EXPIRED')?.count||0);const max=Math.max(1,...d.providerTotals.map(x=>x.amount));return <DoniShell title="Finance" active="/finance" user={user}><AutoRefresh seconds={45}/><div className="grid"><MetricCard label="Paiements confirmés" value={paid} tone="good"/><MetricCard label="Paiements en attente" value={pending} tone={pending?'warn':'default'}/><MetricCard label="Échecs / expirés" value={failed} tone={failed?'bad':'good'}/><MetricCard label="Devises actives · 7 j" value={d.currencyTotals.length}/></div><h2 className="sectionTitle">Chiffre d’affaires encaissé</h2><div className="financeCurrencyGrid">{d.currencyTotals.length?d.currencyTotals.map(x=><div className="card" key={x.currency}><div className="currencyCode">{x.currency}</div><div className="financeAmount">{money(x.amount,x.currency)}</div><div className="metricNote">{x.count} paiement{x.count===1?'':'s'} · 7 jours</div><div className={`trend ${x.changePct==null?'neutral':x.changePct>=0?'up':'down'}`}>{x.changePct==null?'Pas de comparaison':`${x.changePct>=0?'+':''}${x.changePct}% vs 7 j précédents`}</div></div>):<div className="card muted">Aucun encaissement sur les 7 derniers jours.</div>}</div><h2 className="sectionTitle">Encaissements par fournisseur · 7 jours</h2><div className="card">{d.providerTotals.length?d.providerTotals.map(x=><Bar key={`${x.provider}-${x.currency}`} value={x.amount} max={max} label={`${x.provider} · ${x.currency}`} right={`${money(x.amount,x.currency)} · ${x.count}`}/>):<span className="muted">Aucune donnée.</span>}</div><h2 className="sectionTitle">Transactions récentes</h2><div className="card tableWrap"><table className="table"><thead><tr><th>Référence</th><th>Fournisseur</th><th>Montant</th><th>Statut</th><th>Mise à jour</th></tr></thead><tbody>{d.recentPayments.map(p=><tr key={p.reference}><td><code>{p.reference}</code></td><td>{p.provider}</td><td>{money(Number(p.amount),p.currency)}</td><td><span className={`badge ${p.status==='PAID'?'ok':p.status==='PENDING'?'warn':'badBadge'}`}>{p.status}</span></td><td>{p.updatedAt.toLocaleString('fr-FR')}</td></tr>)}</tbody></table></div></DoniShell>}
