import {redirect} from 'next/navigation';
import {revalidatePath} from 'next/cache';
import {DoniShell} from '@/components/DoniShell';
import {requirePageUser} from '@/lib/auth/session';
import {canAccessMarketing} from '@/lib/auth/marketing-access';
import {listMarketingCampaigns} from '@/lib/workspace/marketing-campaigns';
import {listMetaAdsAdSetConfigs} from '@/lib/workspace/meta-ads-adsets';
import {listMetaAdsCreativeConfigs} from '@/lib/workspace/meta-ads-creatives';
import {approveMetaAdsLaunch,listMetaAdsLaunchControls,requestMetaAdsLaunch} from '@/lib/workspace/meta-ads-launch';
import {activateMetaAdsCampaign,pauseMetaAdsCampaign} from '@/services/facebook/activation';
import {getMetaAdsStatus} from '@/services/facebook/ads';
export const dynamic='force-dynamic';

export default async function Page({searchParams}:{searchParams?:Promise<Record<string,string|string[]|undefined>>}){
 const user=await requirePageUser('AGENT');if(!canAccessMarketing(user))redirect('/overview?forbidden=1');
 const params=searchParams?await searchParams:{};const ok=typeof params?.ok==='string'?params.ok:'';const error=typeof params?.error==='string'?params.error:'';
 const [campaigns,adsets,creatives,launches,meta]=await Promise.all([listMarketingCampaigns(),listMetaAdsAdSetConfigs(),listMetaAdsCreativeConfigs(),listMetaAdsLaunchControls(),getMetaAdsStatus()]);
 const adsetBy=new Map(adsets.map(x=>[x.campaignId,x])),creativeBy=new Map(creatives.map(x=>[x.campaignId,x])),launchBy=new Map(launches.map(x=>[x.campaignId,x]));
 const items=campaigns.filter(c=>c.channel==='META_ADS'&&c.metaAds?.remoteCampaignId);
 async function request(formData:FormData){'use server';const u=await requirePageUser('ADMIN');const id=String(formData.get('id')||'');try{await requestMetaAdsLaunch(id,{id:u.id,username:u.username});revalidatePath('/marketing/meta-ads-launch');redirect('/marketing/meta-ads-launch?ok=requested');}catch(e){redirect(`/marketing/meta-ads-launch?error=${encodeURIComponent(e instanceof Error?e.message:'request_failed')}`);}}
 async function approve(formData:FormData){'use server';const u=await requirePageUser('SUPER_ADMIN');const id=String(formData.get('id')||'');try{await approveMetaAdsLaunch(id,{id:u.id,username:u.username,role:u.role});revalidatePath('/marketing/meta-ads-launch');redirect('/marketing/meta-ads-launch?ok=approved');}catch(e){redirect(`/marketing/meta-ads-launch?error=${encodeURIComponent(e instanceof Error?e.message:'approval_failed')}`);}}
 async function activate(formData:FormData){'use server';const u=await requirePageUser('SUPER_ADMIN');const id=String(formData.get('id')||''),confirm=String(formData.get('confirm')||'').trim().toUpperCase();if(confirm!=='ACTIVER')redirect('/marketing/meta-ads-launch?error=confirmation_ACTIVER_required');try{await activateMetaAdsCampaign(id,{id:u.id,username:u.username,role:u.role});revalidatePath('/marketing/meta-ads-launch');redirect('/marketing/meta-ads-launch?ok=active');}catch(e){redirect(`/marketing/meta-ads-launch?error=${encodeURIComponent(e instanceof Error?e.message:'activation_failed')}`);}}
 async function pause(formData:FormData){'use server';const u=await requirePageUser('SUPER_ADMIN');const id=String(formData.get('id')||'');try{await pauseMetaAdsCampaign(id,{id:u.id,username:u.username,role:u.role});revalidatePath('/marketing/meta-ads-launch');redirect('/marketing/meta-ads-launch?ok=paused');}catch(e){redirect(`/marketing/meta-ads-launch?error=${encodeURIComponent(e instanceof Error?e.message:'pause_failed')}`);}}
 return <DoniShell title="Meta Ads Launch Control" active="/marketing/meta-ads-launch" user={user}>
  <section className="workspaceWelcome"><div><span className="workspaceKicker">Meta Ads · Diffusion contrôlée</span><h2>Meta Ads Launch Control</h2><p>L’activation est séparée de la création. Une campagne doit être complète, demandée, approuvée par un Super Admin, puis confirmée avec le mot ACTIVER. Pause d’urgence disponible à tout moment.</p></div></section>
  {ok?<div className="settingsMessage">✓ {ok==='requested'?'Demande de diffusion enregistrée.':ok==='approved'?'Diffusion approuvée. Une confirmation finale est encore requise.':ok==='active'?'Campagne Meta activée. La diffusion peut maintenant générer des dépenses.':'Campagne mise en pause.'}</div>:null}
  {error?<div className="settingsMessage">⚠ Meta Ads : {error}</div>:null}
  <div className="marketingKpis"><div className="card"><span>Compte Ads</span><strong>{meta.account?.name||'Non prêt'}</strong></div><div className="card"><span>Écriture Meta</span><strong>{meta.writeEnabled?'AUTORISÉE':'OFF'}</strong></div><div className="card"><span>Sécurité</span><strong>3 validations</strong><small>Demande → approbation → ACTIVER</small></div><div className="card"><span>Arrêt</span><strong>Pause d’urgence</strong><small>Campaign PAUSED en premier</small></div></div>
  <section className="card publisherQueue"><div className="searchIntelHead"><div><span>Campagnes prêtes</span><h3>Contrôle de diffusion Meta Ads</h3></div><small>Aucune activation automatique</small></div>
   <div className="publisherRows">{items.map(c=>{const a=adsetBy.get(c.id),cr=creativeBy.get(c.id),l=launchBy.get(c.id);const ready=Boolean(a?.remoteAdSetId&&cr?.remoteAdId);const state=l?.status||'IDLE';return <article className="publisherRow" key={c.id} style={{alignItems:'start'}}><div><span className="publisherStatus">{state}</span><h4>{c.name}</h4><small>Campaign {c.metaAds?.remoteCampaignId} · Ad Set {a?.remoteAdSetId||'manquant'} · Ad {cr?.remoteAdId||'manquant'}</small></div><div><span>Préparation</span><strong>{ready?'Complète':'Incomplète'}</strong><small>{ready?'Tous les objets Meta existent.':'Terminer Publisher avant diffusion.'}</small></div><div><span>Validation</span><strong>{l?.approvedBy?`Approuvée par ${l.approvedBy}`:l?.requestedBy?`Demandée par ${l.requestedBy}`:'Aucune demande'}</strong><small>{l?.lastError?`Erreur : ${l.lastError}`:'Activation jamais automatique'}</small></div><div style={{display:'grid',gap:8,minWidth:220}}>{ready&&state!=='ACTIVE'&&state!=='REQUESTED'&&state!=='APPROVED_FOR_LAUNCH'?<form action={request}><input type="hidden" name="id" value={c.id}/><button className="btn" type="submit">Demander la diffusion</button></form>:null}{state==='REQUESTED'&&user.role==='SUPER_ADMIN'?<form action={approve}><input type="hidden" name="id" value={c.id}/><button className="btn primary" type="submit">Approuver la diffusion</button></form>:null}{state==='APPROVED_FOR_LAUNCH'&&user.role==='SUPER_ADMIN'?<form action={activate} style={{display:'grid',gap:6}}><input type="hidden" name="id" value={c.id}/><label><small>Taper ACTIVER pour confirmer la dépense potentielle</small><input name="confirm" autoComplete="off" required placeholder="ACTIVER"/></label><button className="primaryButton" type="submit" disabled={!meta.writeEnabled||meta.account?.accountStatus!==1}>ACTIVER META ADS</button></form>:null}{state==='ACTIVE'&&user.role==='SUPER_ADMIN'?<form action={pause}><input type="hidden" name="id" value={c.id}/><button className="btn" type="submit">⏸ Pause d’urgence</button></form>:null}{!ready?<span className="muted">Publication PAUSED incomplète.</span>:null}</div></article>})}{!items.length?<p className="muted">Aucune campagne Meta distante.</p>:null}</div>
  </section>
 </DoniShell>;
}
