import {redirect} from 'next/navigation';
import {DoniShell} from '@/components/DoniShell';
import {requirePageUser} from '@/lib/auth/session';
import {canAccessMarketing} from '@/lib/auth/marketing-access';
import {getMarketingDeliveryDashboard} from '@/lib/workspace/marketing-delivery-tracking';
export const dynamic='force-dynamic';
function date(v:string|null|undefined){return v?new Date(v).toLocaleString('fr-FR'):'—';}
function status(x:any){if(x.failedAt)return'Échec';if(x.repliedAt)return'Réponse';if(x.readAt)return'Lu';if(x.deliveredAt)return'Livré';return'Envoyé';}
export default async function Page(){const user=await requirePageUser('AGENT');if(!canAccessMarketing(user))redirect('/overview?forbidden=1');const data=await getMarketingDeliveryDashboard();return <DoniShell title="Delivery & Conversion Analytics" active="/marketing/delivery-analytics" user={user}>
<section className="workspaceWelcome"><div><span className="workspaceKicker">Marketing V2 · Mesure réelle</span><h2>Delivery, Engagement & Conversion Tracking</h2><p>Mesure des statuts Meta WhatsApp, des réponses clients et des paiements attribués dans les 7 jours suivant une campagne.</p></div></section>
<div className="marketingKpis"><div className="card"><span>Messages suivis</span><strong>{data.counts.SENT}</strong></div><div className="card"><span>Livrés</span><strong>{data.rates.deliveredRate}%</strong><small>{data.counts.DELIVERED} messages</small></div><div className="card"><span>Lus</span><strong>{data.rates.readRate}%</strong><small>{data.counts.READ} messages</small></div><div className="card"><span>Réponses</span><strong>{data.rates.replyRate}%</strong><small>{data.counts.REPLIED} réponses</small></div><div className="card"><span>Conversions 7 j</span><strong>{data.rates.conversionRate}%</strong><small>{data.conversions} campagnes converties</small></div><div className="card"><span>Échecs Meta</span><strong>{data.counts.FAILED}</strong></div></div>
<section className="card deliveryRevenue"><div className="searchIntelHead"><div><span>Attribution</span><h3>Revenu observé après campagne</h3></div><small>Fenêtre 7 jours · même conversation</small></div><div className="deliveryRevenueGrid">{Object.entries(data.revenueByCurrency).length?Object.entries(data.revenueByCurrency).map(([currency,amount])=><div key={currency}><span>{currency}</span><strong>{Number(amount).toLocaleString('fr-FR',{maximumFractionDigits:2})}</strong></div>):<p className="muted">Aucun paiement attribué pour le moment.</p>}</div></section>
<section className="card deliveryTable"><div className="searchIntelHead"><div><span>Campagnes</span><h3>Suivi message par message</h3></div><small>{data.records.length} envois indexés</small></div><div className="deliveryRows">{data.records.map((r:any)=><article className="deliveryRow" key={r.providerMessageId}><div><span className="publisherStatus">{status(r)}</span><strong>{r.itemId}</strong><small>{r.recipient}</small></div><div><span>Envoyé</span><strong>{date(r.sentAt)}</strong></div><div><span>Livré / lu</span><strong>{r.readAt?date(r.readAt):r.deliveredAt?date(r.deliveredAt):'—'}</strong></div><div><span>Réponse</span><strong>{date(r.repliedAt)}</strong></div><div><span>Meta ID</span><small>{r.providerMessageId}</small>{r.failureReason?<small>{r.failureReason}</small>:null}</div></article>)}</div></section>
<section className="card deliveryEvents"><div className="searchIntelHead"><div><span>Journal</span><h3>200 derniers événements</h3></div><small>Meta + réponses</small></div><div className="publisherEventList">{data.events.map((e:any,i:number)=><div className="publisherEvent" key={`${e.at}-${i}`}><strong>{e.type}</strong><span>{e.itemId}</span><span>{e.recipient||'—'}</span><span>{date(e.at)}</span><small>{e.attribution||e.providerStatus||''}</small></div>)}</div></section>
</DoniShell>}
