import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { requireApiUser } from '@/lib/auth/session';
import { canManageAdmins } from '@/lib/auth/permissions';
import { hashPassword } from '@/lib/auth/password';
import { audit } from '@/lib/audit';
import { isDepartment, setUserDepartment, type Department } from '@/lib/auth/departments';
import type { UserRole } from '@prisma/client';
const roles:UserRole[]=['AGENT','ADMIN','SUPER_ADMIN'];
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){const auth=await requireApiUser('ADMIN');if(!auth.ok)return NextResponse.json({success:false,error:auth.error},{status:auth.status});const {id}=await params;const target=await db.portalUser.findUnique({where:{id}});if(!target)return NextResponse.json({success:false,error:'not_found'},{status:404});if((target.role==='ADMIN'||target.role==='SUPER_ADMIN')&&!canManageAdmins(auth.user.role))return NextResponse.json({success:false,error:'forbidden_target'},{status:403});try{const b=await req.json();const data:Record<string,unknown>={};if(typeof b.fullName==='string')data.fullName=b.fullName||null;if(typeof b.email==='string')data.email=b.email.trim().toLowerCase()||null;if(typeof b.country==='string')data.country=b.country||null;if(typeof b.active==='boolean')data.active=b.active;if(typeof b.role==='string'){const role=b.role as UserRole;if(!roles.includes(role))return NextResponse.json({success:false,error:'invalid_role'},{status:400});if((role==='ADMIN'||role==='SUPER_ADMIN')&&!canManageAdmins(auth.user.role))return NextResponse.json({success:false,error:'forbidden_role'},{status:403});data.role=role;}if(typeof b.password==='string'&&b.password)data.passwordHash=hashPassword(b.password);if('department' in b){const rawDepartment=b.department?String(b.department):null;if(rawDepartment&&!isDepartment(rawDepartment))return NextResponse.json({success:false,error:'invalid_department'},{status:400});const department:Department|null=rawDepartment&&isDepartment(rawDepartment)?rawDepartment:null;await setUserDepartment(id,department,auth.user.id);}const updated=await db.portalUser.update({where:{id},data});if(data.active===false)await db.portalSession.deleteMany({where:{userId:id}});await audit({userId:auth.user.id,action:'USER_UPDATE',entity:'PortalUser',entityId:id,metadata:{fields:[...Object.keys(data),...('department' in b?['department']:[])]}});return NextResponse.json({success:true,user:{id:updated.id,username:updated.username,role:updated.role,active:updated.active}});}catch(e){return NextResponse.json({success:false,error:e instanceof Error?e.message:'update_failed'},{status:400});}}
