import './globals.css';
import './doni-shell.css';
import './workspace-v2.css';
import './work-centers.css';
import './tasks-v1.css';
import './notifications-v1.css';
import './global-search-v1.css';
import './case-360.css';
import './case-ops-v1.css';
import './case-portfolio.css';
import './marketing-phase1.css';
import './marketing-phase2.css';
import './marketing-studio.css';
import './marketing-phase4.css';
import './marketing-attribution.css';
import './marketing-planning.css';
import './marketing-executive.css';
import './marketing-team.css';
import './marketing-assets.css';
import './marketing-seasonality.css';
import './marketing-reviews.css';
export const metadata={title:'DONI Portal — Créatif Travel',description:'DONI travel operations platform'};
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="fr"><body>{children}</body></html>}
