'use client';
import {useEffect,useState} from 'react';
import {startRegistration} from '@simplewebauthn/browser';
import {notifyAction} from '@/components/workspace/ActionFeedback';

type PasskeyCredential={id:string;name:string;createdAt:string;lastUsedAt?:string|null;deviceType?:string|null;backedUp?:boolean};
type Status={totp:{enabled:boolean;confirmedAt?:string|null};passkey:{enabled:boolean;available:boolean;count:number;credentials:PasskeyCredential[]};recovery:{available:boolean}};
type Setup={secret:string;uri:string;qrDataUrl:string};
type SessionRow={id:string;current:boolean;createdAt:string;expiresAt:string;device:string;lastSeenAt?:string|null;ipFingerprint?:string|null};

export function SecuritySettings(){
 const[status,setStatus]=useState<Status|null>(null),[setup,setSetup]=useState<Setup|null>(null),[code,setCode]=useState(''),[recovery,setRecovery]=useState<string[]>([]),[sessions,setSessions]=useState<SessionRow[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){const[r,s]=await Promise.all([fetch('/api/auth/mfa/status',{cache:'no-store'}),fetch('/api/auth/sessions',{cache:'no-store'})]);const[j,k]=await Promise.all([r.json(),s.json()]);if(j.success)setStatus(j);if(k.success)setSessions(k.sessions||[])}
 useEffect(()=>{load()},[]);
 async function startTotp(){if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/auth/mfa/totp/setup',{method:'POST'});const j=await r.json();if(!r.ok||!j.success){setError(j.error==='mfa_encryption_key_missing'?'La clé de chiffrement MFA doit être configurée sur le serveur avant activation.':'Impossible de préparer Google Authenticator.');return}setSetup(j)}catch{setError('Connexion interrompue.')}finally{setBusy(false)}}
 async function confirmTotp(){if(busy)return;if(code.replace(/\D/g,'').length!==6){setError('Entre le code à 6 chiffres affiché par Google Authenticator.');return}setBusy(true);setError('');try{const r=await fetch('/api/auth/mfa/totp/confirm',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code})});const j=await r.json();if(!r.ok||!j.success){setError(j.error==='invalid_totp'?'Code incorrect. Attends le prochain code et réessaie.':'Activation impossible.');return}setRecovery(j.recoveryCodes||[]);setSetup(null);setCode('');await load();notifyAction({tone:'success',title:'Protection activée',message:'Google Authenticator est maintenant activé comme facteur de secours.'})}catch{setError('Connexion interrompue.')}finally{setBusy(false)}}
 async function addPasskey(){if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/auth/mfa/passkey/register/options',{method:'POST'});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||'passkey_options_failed');const response=await startRegistration({optionsJSON:j.options});const name=window.prompt('Nom de cette clé / Passkey','Passkey principale')||'Passkey';const v=await fetch('/api/auth/mfa/passkey/register/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({response,name})});const x=await v.json();if(!v.ok||!x.success)throw new Error(x.error||'passkey_registration_failed');await load();notifyAction({tone:'success',title:'Passkey ajoutée',message:'Cette clé peut maintenant être utilisée comme facteur principal de connexion.'});}catch(e){const m=e instanceof Error?e.message:'passkey_failed';setError(m.includes('NotAllowed')?'L’enregistrement a été annulé ou aucune Passkey compatible n’est disponible.':'Impossible d’ajouter la Passkey.');}finally{setBusy(false)}}
 async function revokeSession(id:string){if(busy)return;setBusy(true);setError('');try{const r=await fetch(`/api/auth/sessions/${encodeURIComponent(id)}`,{method:'DELETE'});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||'session_revoke_failed');await load();notifyAction({tone:'success',title:'Session révoquée',message:'Cet appareil devra se reconnecter avec les facteurs de sécurité requis.'});}catch{setError('Impossible de révoquer cette session.')}finally{setBusy(false)}}
 async function revokeOthers(){if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/auth/sessions',{method:'DELETE'});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||'session_revoke_failed');await load();notifyAction({tone:'success',title:'Autres sessions fermées',message:`${Number(j.count||0)} session(s) ont été révoquées.`});}catch{setError('Impossible de fermer les autres sessions.')}finally{setBusy(false)}}
 return <div style={{display:'grid',gap:18}}>
 <section className="card" style={{padding:22}}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'flex-start',flexWrap:'wrap'}}><div><span className="workspaceKicker">Méthode recommandée</span><h2 style={{margin:'6px 0'}}>Passkey / clé physique FIDO2</h2><p className="muted" style={{maxWidth:680}}>Utilise Touch ID, Face ID, Windows Hello ou une clé de sécurité FIDO2. La clé privée reste dans ton appareil et DONI exige une vérification utilisateur.</p></div><span className={`badge ${status?.passkey.enabled?'ok':'warn'}`}>{status?.passkey.enabled?`${status.passkey.count} enregistrée(s)`:'Non activé'}</span></div><button className="btn primary" onClick={addPasskey} disabled={busy}>{busy?'Préparation…':'Ajouter une Passkey / clé de sécurité'}</button>{status?.passkey.credentials?.length?<div style={{display:'grid',gap:8,marginTop:16}}>{status.passkey.credentials.map(x=><div key={x.id} style={{display:'flex',justifyContent:'space-between',gap:12,padding:12,border:'1px solid #e2e8f0',borderRadius:10}}><div><strong>{x.name}</strong><div className="muted" style={{fontSize:13}}>Ajoutée le {new Date(x.createdAt).toLocaleDateString('fr-FR')}{x.lastUsedAt?` · utilisée ${new Date(x.lastUsedAt).toLocaleDateString('fr-FR')}`:''}</div></div><span className="badge ok">FIDO2</span></div>)}</div>:null}</section>
 <section className="card" style={{padding:22}}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'flex-start',flexWrap:'wrap'}}><div><span className="workspaceKicker">Facteur de secours</span><h2 style={{margin:'6px 0'}}>Google Authenticator (TOTP)</h2><p className="muted" style={{maxWidth:680}}>DONI peut aussi demander un code temporaire à 6 chiffres. Le secret est chiffré côté serveur.</p></div><span className={`badge ${status?.totp.enabled?'ok':'warn'}`}>{status?.totp.enabled?'Activé':'Non activé'}</span></div>{!status?.totp.enabled&&!setup?<button className="btn" onClick={startTotp} disabled={busy}>{busy?'Préparation…':'Activer Google Authenticator'}</button>:null}{setup?<div style={{display:'grid',gap:16,marginTop:18}}><div style={{display:'flex',gap:22,alignItems:'center',flexWrap:'wrap'}}><img src={setup.qrDataUrl} width={220} height={220} alt="QR code Google Authenticator" style={{border:'1px solid #e2e8f0',borderRadius:14}}/><div style={{maxWidth:420}}><strong>1. Scanne ce QR code</strong><p className="muted">Dans Google Authenticator : + → Scanner un code QR.</p><strong>2. Code manuel de secours pour l’enrôlement</strong><code style={{display:'block',marginTop:8,padding:10,background:'#f8fafc',borderRadius:8,wordBreak:'break-all'}}>{setup.secret}</code></div></div><label style={{display:'grid',gap:7,maxWidth:320,fontWeight:600}}>3. Confirme avec le code actuel<input value={code} onChange={e=>setCode(e.target.value)} inputMode="numeric" autoComplete="one-time-code" placeholder="123456" style={{height:46,border:'1px solid #cbd5e1',borderRadius:10,padding:'0 12px',fontSize:20,letterSpacing:3}}/></label><div><button className="btn primary" onClick={confirmTotp} disabled={busy}>{busy?'Validation…':'Confirmer et activer'}</button></div></div>:null}</section>
 {recovery.length?<section className="card" style={{padding:22,border:'2px solid #f59e0b'}}><h2>Codes de récupération — à conserver maintenant</h2><p>Chaque code ne fonctionne qu’une seule fois. Enregistre-les dans un gestionnaire de mots de passe ou imprime-les et garde-les dans un endroit sécurisé.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:8,margin:'16px 0'}}>{recovery.map(c=><code key={c} style={{padding:10,background:'#f8fafc',borderRadius:8,textAlign:'center'}}>{c}</code>)}</div><button className="btn" onClick={()=>navigator.clipboard.writeText(recovery.join('\n'))}>Copier les codes</button></section>:null}
 <section className="card" style={{padding:22}}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'flex-start',flexWrap:'wrap'}}><div><span className="workspaceKicker">Appareils & sessions</span><h2 style={{margin:'6px 0'}}>Sessions actives</h2><p className="muted" style={{maxWidth:680}}>Une session révoquée est immédiatement invalide. L’empreinte réseau affichée est hachée : DONI ne montre pas l’adresse IP brute.</p></div>{sessions.length>1?<button className="btn" onClick={revokeOthers} disabled={busy}>Déconnecter tous les autres appareils</button>:null}</div><div style={{display:'grid',gap:10,marginTop:16}}>{sessions.map(s=><div key={s.id} style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',padding:14,border:'1px solid #e2e8f0',borderRadius:12,flexWrap:'wrap'}}><div><div style={{display:'flex',gap:8,alignItems:'center'}}><strong>{s.device}</strong>{s.current?<span className="badge ok">Cet appareil</span>:null}</div><div className="muted" style={{fontSize:13,marginTop:5}}>Connexion {new Date(s.createdAt).toLocaleString('fr-FR')} · expire {new Date(s.expiresAt).toLocaleString('fr-FR')}</div>{s.ipFingerprint?<div className="muted" style={{fontSize:12,marginTop:3}}>Empreinte réseau : {s.ipFingerprint}</div>:null}</div>{!s.current?<button className="btn" onClick={()=>revokeSession(s.id)} disabled={busy}>Révoquer</button>:null}</div>)}</div></section>
 {error?<div role="alert" style={{padding:12,borderRadius:10,background:'#fef2f2',color:'#b91c1c'}}>{error}</div>:null}
 </div>}
