'use client';
import { useEffect,useState } from 'react';
import {notifyAction} from './workspace/ActionFeedback';
type Row={reference:string;status:string;createdAt:string;passengerCount:number;segmentCount:number;passengers:any[];segments:any[];contact:any;total?:string;currency?:string};
type Issued={reference:string;pnr?:string;ticketNumber?:string;issuedAt?:string;deliveryStatus:string;passengerCount:number;segmentCount:number};
export function TicketingQueue(){const[rows,setRows]=useState<Row[]>([]),[issued,setIssued]=useState<Issued[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState('');
 const load=async()=>{setLoading(true);try{const res=await fetch('/api/ticketing/queue',{cache:'no-store'});const r=await res.json().catch(()=>({}));if(res.ok&&r.success){setRows(r.rows||[]);setIssued(r.issued||[])}else notifyAction({tone:'error',title:'File Ticketing indisponible',message:'Impossible d’actualiser la file d’émission. Réessaie avant de traiter un billet.'})}catch{notifyAction({tone:'error',title:'Connexion interrompue',message:'La file Ticketing n’a pas pu être actualisée.'})}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const issue=async(ref:string)=>{if(busy)return;const pnr=prompt('PNR / Booking reference');if(!pnr?.trim())return;const ticketNumber=prompt('Numéro de billet (optionnel)')||'';if(!confirm(`Confirmer l’émission de ${ref} avec le PNR ${pnr.trim()} ?`))return;setBusy(`${ref}:issue`);try{const res=await fetch('/api/ticketing/issue',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reference:ref,pnr:pnr.trim(),ticketNumber:ticketNumber.trim()})});const r=await res.json().catch(()=>({}));if(res.ok&&r.success){notifyAction({tone:'success',title:'Billet émis',message:`${ref} a été enregistré comme émis. Vérifie maintenant la livraison au client.`});await load()}else notifyAction({tone:'error',title:'Émission non confirmée',message:r.error?`DONI indique : ${r.error}. Vérifie le dossier avant de réessayer.`:'Le billet n’a pas été confirmé comme émis. Vérifie le dossier avant de réessayer.'})}catch{notifyAction({tone:'error',title:'Connexion interrompue',message:'Le résultat de l’émission est incertain. Vérifie le statut du billet avant de cliquer de nouveau sur Émettre.'})}finally{setBusy('')}};
 const deliver=async(ref:string)=>{if(busy)return;setBusy(`${ref}:deliver`);try{const res=await fetch('/api/ticketing/deliver',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reference:ref})});const r=await res.json().catch(()=>({}));if(res.ok&&r.success){notifyAction({tone:'success',title:'Livraison déclenchée',message:`Le billet ${ref} a été envoyé au canal de livraison configuré.`});await load()}else notifyAction({tone:'error',title:'Livraison échouée',message:'Le billet reste émis, mais la livraison n’a pas abouti. Vérifie le contact puis réessaie uniquement l’envoi.'})}catch{notifyAction({tone:'error',title:'Connexion interrompue',message:'Impossible de confirmer la livraison. Vérifie son statut avant de relancer l’envoi.'})}finally{setBusy('')}};
 return <><div className="grid"><div className="card"><div className="statLabel">À émettre</div><div className="statValue">{rows.length}</div></div><div className="card"><div className="statLabel">Émis récemment</div><div className="statValue">{issued.length}</div></div><div className="card"><div className="statLabel">Bloqués données</div><div className="statValue">{rows.filter(r=>!r.passengerCount||!r.segmentCount).length}</div></div><div className="card"><div className="statLabel">Livraison OK</div><div className="statValue">{issued.filter(x=>x.deliveryStatus==='DELIVERED').length}</div></div></div>
 <h2 className="sectionTitle">Tickets à émettre</h2><div className="card tableWrap" aria-busy={loading||!!busy}><table className="table"><thead><tr><th>Référence</th><th>Client</th><th>Route</th><th>Pax / Seg</th><th>Montant</th><th>Statut</th><th>Action</th></tr></thead><tbody>{loading?<tr><td colSpan={7}>Chargement…</td></tr>:rows.length===0?<tr><td colSpan={7}>✅ Aucun ticket en attente</td></tr>:rows.map(r=>{const pax=r.passengers?.[0];const route=r.segments?.length?`${r.segments[0].origin||'---'} → ${r.segments.at(-1)?.destination||'---'}`:'—';const can=r.passengerCount>0&&r.segmentCount>0;const issuing=busy===`${r.reference}:issue`;return <tr key={r.reference} aria-busy={issuing}><td><b>{r.reference}</b></td><td>{pax?`${pax.firstName||''} ${pax.lastName||''}`:'—'}</td><td>{route}</td><td><span className={r.passengerCount?'badge ok':'badge warn'}>{r.passengerCount} pax</span> <span className={r.segmentCount?'badge ok':'badge warn'}>{r.segmentCount} seg</span></td><td>{r.total?`${r.total} ${r.currency||''}`:'—'}</td><td><span className="badge warn">{r.status}</span></td><td><button className="btn primary" disabled={!can||!!busy} onClick={()=>issue(r.reference)}>{issuing?'Émission…':'Émettre'}</button></td></tr>})}</tbody></table></div>
 <h2 className="sectionTitle">Récemment émis</h2><div className="card tableWrap"><table className="table"><thead><tr><th>Référence</th><th>PNR</th><th>Ticket #</th><th>Pax / Seg</th><th>Livraison</th><th>Actions</th></tr></thead><tbody>{issued.length===0?<tr><td colSpan={6}>Aucun billet émis.</td></tr>:issued.map(r=>{const delivering=busy===`${r.reference}:deliver`;return <tr key={r.reference} aria-busy={delivering}><td><b>{r.reference}</b></td><td>{r.pnr||'—'}</td><td>{r.ticketNumber||'—'}</td><td>{r.passengerCount} / {r.segmentCount}</td><td><span className={`badge ${r.deliveryStatus==='DELIVERED'?'ok':'warn'}`}>{r.deliveryStatus}</span></td><td><a className="btn" href={`/api/ticketing/${encodeURIComponent(r.reference)}/pdf`} target="_blank" rel="noreferrer">PDF</a> <button className="btn primary" disabled={!!busy} onClick={()=>deliver(r.reference)}>{delivering?'Envoi…':'Renvoyer'}</button></td></tr>})}</tbody></table></div></>}
