'use client';
import { useEffect,useState } from 'react';
type Row={reference:string;status:string;createdAt:string;passengerCount:number;segmentCount:number;passengers:any[];segments:any[];contact:any;total?:string;currency?:string};
type Issued={reference:string;pnr?:string;ticketNumber?:string;issuedAt?:string;deliveryStatus:string;passengerCount:number;segmentCount:number};
export function TicketingQueue(){const[rows,setRows]=useState<Row[]>([]),[issued,setIssued]=useState<Issued[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState('');
 const load=async()=>{setLoading(true);const r=await fetch('/api/ticketing/queue',{cache:'no-store'}).then(x=>x.json());if(r.success){setRows(r.rows||[]);setIssued(r.issued||[])}setLoading(false)};useEffect(()=>{load()},[]);
 const issue=async(ref:string)=>{const pnr=prompt('PNR / Booking reference');if(!pnr)return;const ticketNumber=prompt('Numéro de billet (optionnel)')||'';setBusy(ref);const r=await fetch('/api/ticketing/issue',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reference:ref,pnr,ticketNumber})}).then(x=>x.json());setBusy('');if(!r.success)alert(`Erreur: ${r.error}`);await load()};
 const deliver=async(ref:string)=>{setBusy(ref);const r=await fetch('/api/ticketing/deliver',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reference:ref})}).then(x=>x.json());setBusy('');alert(r.success?'Livraison déclenchée':`Livraison échouée: ${JSON.stringify(r.results||r.error)}`);await load()};
 return <><div className="grid"><div className="card"><div className="statLabel">À émettre</div><div className="statValue">{rows.length}</div></div><div className="card"><div className="statLabel">Émis récemment</div><div className="statValue">{issued.length}</div></div><div className="card"><div className="statLabel">Bloqués données</div><div className="statValue">{rows.filter(r=>!r.passengerCount||!r.segmentCount).length}</div></div><div className="card"><div className="statLabel">Livraison OK</div><div className="statValue">{issued.filter(x=>x.deliveryStatus==='DELIVERED').length}</div></div></div>
 <h2 className="sectionTitle">Tickets à émettre</h2><div className="card tableWrap"><table className="table"><thead><tr><th>Référence</th><th>Client</th><th>Route</th><th>Pax / Seg</th><th>Montant</th><th>Statut</th><th>Action</th></tr></thead><tbody>{loading?<tr><td colSpan={7}>Chargement…</td></tr>:rows.length===0?<tr><td colSpan={7}>✅ Aucun ticket en attente</td></tr>:rows.map(r=>{const pax=r.passengers?.[0];const route=r.segments?.length?`${r.segments[0].origin||'---'} → ${r.segments.at(-1)?.destination||'---'}`:'—';const can=r.passengerCount>0&&r.segmentCount>0;return <tr key={r.reference}><td><b>{r.reference}</b></td><td>{pax?`${pax.firstName||''} ${pax.lastName||''}`:'—'}</td><td>{route}</td><td><span className={r.passengerCount?'badge ok':'badge warn'}>{r.passengerCount} pax</span> <span className={r.segmentCount?'badge ok':'badge warn'}>{r.segmentCount} seg</span></td><td>{r.total?`${r.total} ${r.currency||''}`:'—'}</td><td><span className="badge warn">{r.status}</span></td><td><button className="btn primary" disabled={!can||busy===r.reference} onClick={()=>issue(r.reference)}>{busy===r.reference?'…':'Émettre'}</button></td></tr>})}</tbody></table></div>
 <h2 className="sectionTitle">Récemment émis</h2><div className="card tableWrap"><table className="table"><thead><tr><th>Référence</th><th>PNR</th><th>Ticket #</th><th>Pax / Seg</th><th>Livraison</th><th>Actions</th></tr></thead><tbody>{issued.length===0?<tr><td colSpan={6}>Aucun billet émis.</td></tr>:issued.map(r=><tr key={r.reference}><td><b>{r.reference}</b></td><td>{r.pnr||'—'}</td><td>{r.ticketNumber||'—'}</td><td>{r.passengerCount} / {r.segmentCount}</td><td><span className={`badge ${r.deliveryStatus==='DELIVERED'?'ok':'warn'}`}>{r.deliveryStatus}</span></td><td><a className="btn" href={`/api/ticketing/${encodeURIComponent(r.reference)}/pdf`} target="_blank">PDF</a> <button className="btn primary" disabled={busy===r.reference} onClick={()=>deliver(r.reference)}>Renvoyer</button></td></tr>)}</tbody></table></div></>}
