'use client';
import {useEffect,useState} from 'react';
import {notifyAction} from '@/components/workspace/ActionFeedback';
type U={id:string;username:string;fullName:string|null;email:string|null;role:string;department:string|null;active:boolean;lastLoginAt:string|null};
const departments=[['','Équipe générale'],['RESERVATIONS','Réservations'],['CUSTOMER_SERVICE','Service client'],['TICKETING','Ticketing'],['FLIGHT_OPS','Flight Ops'],['FINANCE','Finance'],['MARKETING','Marketing'],['OPERATIONS','Opérations'],['MANAGEMENT','Direction']];
const initialForm={username:'',fullName:'',email:'',password:'',role:'AGENT',department:''};
const stepLabels=['Identité','Sécurité','Accès & confirmation'];
export function UserAdmin(){
 const[users,setUsers]=useState<U[]>([]),[form,setForm]=useState(initialForm),[step,setStep]=useState(1),[busy,setBusy]=useState(''),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{const r=await fetch('/api/admin/users',{cache:'no-store'});const j=await r.json().catch(()=>({}));if(r.ok)setUsers(j.users||[]);else notifyAction({tone:'error',title:'Chargement impossible',message:'La liste des utilisateurs n’a pas pu être chargée.'})}catch{notifyAction({tone:'error',title:'Connexion interrompue',message:'Impossible de charger les utilisateurs.'})}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 function validate(n:number){if(n===1){const username=form.username.trim();if(username.length<3){notifyAction({tone:'error',title:'Identifiant invalide',message:'L’identifiant doit contenir au moins 3 caractères.'});return false}if(form.email&& !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email.trim())){notifyAction({tone:'error',title:'Email invalide',message:'Vérifie l’adresse email avant de continuer.'});return false}setForm(x=>({...x,username,email:x.email.trim(),fullName:x.fullName.trim()}));return true}if(n===2){if(form.password.length<10){notifyAction({tone:'error',title:'Mot de passe trop court',message:'Utilise au moins 10 caractères.'});return false}return true}if(!['AGENT','ADMIN','SUPER_ADMIN'].includes(form.role)){notifyAction({tone:'error',title:'Rôle invalide',message:'Choisis un rôle autorisé.'});return false}return true}
 function next(){if(validate(step))setStep(x=>Math.min(3,x+1))}
 async function create(){if(busy||!validate(1)||!validate(2)||!validate(3))return;setBusy('create');try{const r=await fetch('/api/admin/users',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const j=await r.json().catch(()=>({}));if(r.ok){setForm(initialForm);setStep(1);await load();notifyAction({tone:'success',title:'Utilisateur créé',message:'Le compte a été créé avec le rôle et le département sélectionnés.'})}else notifyAction({tone:'error',title:'Création impossible',message:j.error||'Le compte n’a pas été créé. Vérifie les informations.'})}catch{notifyAction({tone:'error',title:'Connexion interrompue',message:'La création n’a pas été confirmée. Vérifie la liste avant de réessayer.'})}finally{setBusy('')}}
 async function patch(u:U,data:Record<string,unknown>,label:string){if(busy)return;setBusy(u.id);try{const r=await fetch(`/api/admin/users/${u.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(data)});const j=await r.json().catch(()=>({}));if(r.ok){await load();notifyAction({tone:'success',title:'Utilisateur mis à jour',message:label})}else notifyAction({tone:'error',title:'Modification impossible',message:j.error||'La modification n’a pas été enregistrée.'})}catch{notifyAction({tone:'error',title:'Connexion interrompue',message:'La modification n’a pas été confirmée.'})}finally{setBusy('')}}
 return <><div className="card" aria-busy={busy==='create'}><h2>Créer un utilisateur</h2><p className="muted userAdminIntro">Le rôle définit le niveau de sécurité. Le département définit l’espace de travail principal. Le mot de passe n’est jamais enregistré comme brouillon.</p><div className="doniStepper"><div className="doniStepperNav" aria-label="Progression de création utilisateur">{stepLabels.map((label,i)=>{const n=i+1;return <div key={label} className={`doniStep ${step===n?'isActive':''} ${step>n?'isDone':''}`} aria-current={step===n?'step':undefined}><span>{step>n?'✓':n}</span>{label}</div>})}</div><p className="doniStepProgress">Étape {step} sur 3</p>
 <section className="doniStepPanel" hidden={step!==1} aria-label="Identité utilisateur"><div className="doniStepGrid"><label className="doniStepField">Identifiant<input autoComplete="off" value={form.username} disabled={!!busy} onChange={e=>setForm({...form,username:e.target.value})} placeholder="username"/></label><label className="doniStepField">Nom complet<input value={form.fullName} disabled={!!busy} onChange={e=>setForm({...form,fullName:e.target.value})} placeholder="Nom complet"/></label><label className="doniStepField">Email<input type="email" value={form.email} disabled={!!busy} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Email"/></label></div><div className="doniStepActions"><span/><button type="button" className="btn primary" onClick={next} disabled={!!busy}>Continuer →</button></div></section>
 <section className="doniStepPanel" hidden={step!==2} aria-label="Sécurité du compte"><div className="doniStepGrid"><label className="doniStepField">Mot de passe temporaire<input type="password" autoComplete="new-password" minLength={10} value={form.password} disabled={!!busy} onChange={e=>setForm({...form,password:e.target.value})} placeholder="10 caractères minimum"/></label></div><p className="doniStepHint">Pour des raisons de sécurité, cette valeur reste seulement en mémoire jusqu’à la création du compte.</p><div className="doniStepActions"><button type="button" className="btn" onClick={()=>setStep(1)} disabled={!!busy}>← Retour</button><button type="button" className="btn primary" onClick={next} disabled={!!busy}>Continuer →</button></div></section>
 <section className="doniStepPanel" hidden={step!==3} aria-label="Accès et confirmation"><div className="doniStepGrid"><label className="doniStepField">Rôle<select value={form.role} disabled={!!busy} onChange={e=>setForm({...form,role:e.target.value})}><option>AGENT</option><option>ADMIN</option><option>SUPER_ADMIN</option></select></label><label className="doniStepField">Département<select value={form.department} disabled={!!busy} onChange={e=>setForm({...form,department:e.target.value})}>{departments.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><div className="doniStepSummary" aria-label="Résumé du compte"><div><span>Utilisateur</span><strong>{form.fullName||form.username||'—'}</strong></div><div><span>Email</span><strong>{form.email||'—'}</strong></div><div><span>Rôle</span><strong>{form.role}</strong></div><div><span>Département</span><strong>{departments.find(([v])=>v===form.department)?.[1]||'Équipe générale'}</strong></div></div>{form.role==='SUPER_ADMIN'?<p className="doniStepHint"><strong>Attention :</strong> SUPER_ADMIN donne le niveau d’accès le plus élevé du portail.</p>:null}<div className="doniStepActions"><button type="button" className="btn" onClick={()=>setStep(2)} disabled={!!busy}>← Retour</button><button type="button" className="btn primary" onClick={create} disabled={!!busy}>{busy==='create'?'Création…':'Créer le compte'}</button></div></section></div></div>
 <div className="card"><h2>Utilisateurs & équipes</h2><div className="tableWrap"><table className="table"><thead><tr><th>Utilisateur</th><th>Nom</th><th>Rôle</th><th>Département</th><th>Statut</th><th>Dernière connexion</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={7}>Chargement…</td></tr>:users.map(u=><tr key={u.id} aria-busy={busy===u.id}><td>{u.username}</td><td>{u.fullName||'—'}</td><td><span className="roleChip">{u.role}</span></td><td><select className="miniSelect departmentSelect" value={u.department||''} disabled={!!busy} onChange={e=>patch(u,{department:e.target.value||null},'Le département principal a été mis à jour.')}>{departments.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></td><td><span className={`badge ${u.active?'ok':'warn'}`}>{u.active?'Actif':'Désactivé'}</span></td><td>{u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString():'—'}</td><td><button className="btn" disabled={!!busy} onClick={()=>{if(u.active&&!confirm(`Désactiver le compte ${u.username} ?`))return;patch(u,{active:!u.active},u.active?'Le compte a été désactivé.':'Le compte a été réactivé.')}}>{busy===u.id?'Enregistrement…':u.active?'Désactiver':'Activer'}</button></td></tr>)}</tbody></table>{!loading&&!users.length?<div className="emptyState">Aucun utilisateur.</div>:null}</div></div></>}
