import {NextResponse} from 'next/server';
import {requireApiUser} from '@/lib/auth/session';
import {getSetting} from '@/lib/settings/service';
export const runtime='nodejs';
async function test(name:string,origin?:string){
 if(name==='duffel'){const token=await getSetting<string>('flights.duffel_access_token');if(!token)return{ok:false,message:'Duffel token manquant'};const r=await fetch('https://api.duffel.com/air/airlines?limit=1',{headers:{Authorization:`Bearer ${token}`,'Duffel-Version':'v2',Accept:'application/json'}});return{ok:r.ok,status:r.status,message:r.ok?'Connexion Duffel réussie':'Duffel a refusé les identifiants'};}
 if(name==='stripe'){const key=await getSetting<string>('payments.stripe_secret_key');if(!key)return{ok:false,message:'Stripe key manquante'};const r=await fetch('https://api.stripe.com/v1/balance',{headers:{Authorization:`Bearer ${key}`}});return{ok:r.ok,status:r.status,message:r.ok?'Connexion Stripe réussie':'Stripe a refusé la clé'};}
 if(name==='mercadopago'){const token=await getSetting<string>('payments.mercadopago_access_token');if(!token)return{ok:false,message:'Mercado Pago token manquant'};const r=await fetch('https://api.mercadopago.com/users/me',{headers:{Authorization:`Bearer ${token}`}});return{ok:r.ok,status:r.status,message:r.ok?'Connexion Mercado Pago réussie':'Mercado Pago a refusé le token'};}
 if(name==='paypal'){const id=await getSetting<string>('payments.paypal_client_id'),secret=await getSetting<string>('payments.paypal_client_secret'),mode=await getSetting<string>('payments.paypal_mode');if(!id||!secret)return{ok:false,message:'Identifiants PayPal manquants'};const base=mode==='sandbox'?'https://api-m.sandbox.paypal.com':'https://api-m.paypal.com';const r=await fetch(`${base}/v1/oauth2/token`,{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${id}:${secret}`).toString('base64')}`,'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'});return{ok:r.ok,status:r.status,message:r.ok?`Connexion PayPal ${mode} réussie`:'PayPal a refusé les identifiants'};}
 if(name==='brevo'){const key=await getSetting<string>('email.brevo_api_key');if(!key)return{ok:false,message:'Brevo key manquante'};const r=await fetch('https://api.brevo.com/v3/account',{headers:{'api-key':key,Accept:'application/json'}});return{ok:r.ok,status:r.status,message:r.ok?'Connexion Brevo réussie':'Brevo a refusé la clé'};}
 if(name==='whatsapp'){const token=await getSetting<string>('whatsapp.access_token'),phone=await getSetting<string>('whatsapp.phone_number_id');if(!token||!phone)return{ok:false,message:'Token ou Phone Number ID manquant'};const r=await fetch(`https://graph.facebook.com/v23.0/${encodeURIComponent(phone)}?fields=display_phone_number,verified_name`,{headers:{Authorization:`Bearer ${token}`}});return{ok:r.ok,status:r.status,message:r.ok?'Connexion WhatsApp Meta réussie':'Meta a refusé les identifiants'};}
 if(name==='facebook'){const token=await getSetting<string>('facebook.page_access_token'),pageId=await getSetting<string>('facebook.page_id'),version=await getSetting<string>('facebook.graph_version');if(!token||!pageId)return{ok:false,message:'Facebook Page ID ou Page Access Token manquant'};const v=String(version||'v23.0').replace(/^\/+|\/+$/g,'');const r=await fetch(`https://graph.facebook.com/${v}/${encodeURIComponent(pageId)}?fields=id,name`,{headers:{Authorization:`Bearer ${token}`}});const j:any=await r.json().catch(()=>({}));return{ok:r.ok,status:r.status,message:r.ok?`Connexion Facebook réussie${j?.name?` — ${j.name}`:''}`:'Meta a refusé les identifiants Facebook'};}
 if(name==='whatsapp_webhook'){const verify=await getSetting<string>('whatsapp.verify_token');if(!verify)return{ok:false,message:'Verify token WhatsApp manquant'};if(!origin)return{ok:false,message:'Origin indisponible'};const challenge=`doni-${Date.now()}`;const url=new URL('/api/whatsapp/webhook',origin);url.searchParams.set('hub.mode','subscribe');url.searchParams.set('hub.verify_token',verify);url.searchParams.set('hub.challenge',challenge);const r=await fetch(url,{redirect:'manual'});const body=await r.text();return{ok:r.ok&&body===challenge,status:r.status,message:r.ok&&body===challenge?'Webhook WhatsApp vérifiable par Meta':'Échec de vérification du webhook WhatsApp'};}
 return{ok:false,message:'Intégration inconnue'};
}
export async function POST(req:Request){const auth=await requireApiUser('SUPER_ADMIN');if(!auth.ok)return NextResponse.json({success:false,error:auth.error},{status:auth.status});try{const b=await req.json();return NextResponse.json({success:true,result:await test(String(b.integration||''),new URL(req.url).origin)});}catch(e){return NextResponse.json({success:false,error:e instanceof Error?e.message:'test_failed'},{status:400});}}
