import {BaseSegment} from './base';import type {ConversationSession} from '../conversation/types';import {listCustomerTrackedFlights} from '@/services/customers/service';import {getFlightAwareStatus} from '@/services/flight-ops/flightaware';
function parse(text:string){const upper=text.toUpperCase();const f=upper.match(/\b([A-Z0-9]{2,3})\s*[- ]?\s*(\d{1,4})\b/);const d=text.match(/\b(20\d{2})[-\/.](\d{1,2})[-\/.](\d{1,2})\b/)||text.match(/\b(\d{1,2})[-\/.](\d{1,2})[-\/.](20\d{2})\b/);let date:string|null=null;if(d){if(d[1].length===4)date=`${d[1]}-${d[2].padStart(2,'0')}-${d[3].padStart(2,'0')}`;else date=`${d[3]}-${d[2].padStart(2,'0')}-${d[1].padStart(2,'0')}`;}return {airline:f?.[1]||null,number:f?.[2]||null,date};}
function fmtDate(d:any){try{return new Date(d).toISOString().slice(0,16).replace('T',' ');}catch{return String(d||'—');}}
export class FlightStatusSegment extends BaseSegment{readonly id='segment_flight_status';async handle(s:ConversationSession,text:string){const st=s.state as any;const p=parse(text);let airline=p.airline||st.flight_status_airline||null,number=p.number||st.flight_status_number||null,date=p.date||st.flight_status_date||null;
 if(!airline||!number){const flights=await listCustomerTrackedFlights(s.waId,6);if(flights.length===1){airline=flights[0].airlineCode;number=flights[0].flightNumber;date=new Date(flights[0].scheduledDeparture).toISOString().slice(0,10);}else if(flights.length>1&&!/^\d+$/.test(text.trim())){const lines=flights.map((f:any,i:number)=>`*${i+1}* — ${f.airlineCode}${f.flightNumber} · ${f.origin}→${f.destination} · ${fmtDate(f.scheduledDeparture)}`);return this.retry(this.t(s,{fr:`✈️ J'ai trouvé plusieurs vols actifs :\n\n${lines.join('\n')}\n\nRépondez avec le numéro du vol à vérifier.`,en:`✈️ I found several active flights:\n\n${lines.join('\n')}\n\nReply with the flight number to check.`,es:`✈️ Encontré varios vuelos activos:\n\n${lines.join('\n')}\n\nResponda con el número del vuelo a verificar.`,ht:`✈️ Mwen jwenn plizyè vòl aktif:\n\n${lines.join('\n')}\n\nReponn ak nimewo vòl ou vle verifye a.`}),{flight_status_choices:flights.map((f:any)=>({airline:f.airlineCode,number:f.flightNumber,date:new Date(f.scheduledDeparture).toISOString().slice(0,10)}))});}else if(flights.length>1&&/^\d+$/.test(text.trim())){const n=Number(text.trim())-1,choices=st.flight_status_choices||flights.map((f:any)=>({airline:f.airlineCode,number:f.flightNumber,date:new Date(f.scheduledDeparture).toISOString().slice(0,10)}));if(choices[n])({airline,number,date}=choices[n]);}
 }
 if(!airline||!number)return this.retry(this.t(s,{fr:'✈️ Envoyez le *numéro de vol et la date* (ex. AA123 2026-08-20).',en:'✈️ Send the *flight number and date* (e.g. AA123 2026-08-20).',es:'✈️ Envíe el *número de vuelo y la fecha* (ej. AA123 2026-08-20).',ht:'✈️ Voye *nimewo vòl la ak dat la* (eg. AA123 2026-08-20).'}));
 if(!date)return this.retry(this.t(s,{fr:`J'ai le vol *${airline}${number}*. Envoyez maintenant la date (AAAA-MM-JJ).`,en:`I have flight *${airline}${number}*. Now send the date (YYYY-MM-DD).`,es:`Tengo el vuelo *${airline}${number}*. Envíe ahora la fecha (AAAA-MM-DD).`,ht:`Mwen gen vòl *${airline}${number}*. Kounye a voye dat la (AAAA-MM-JJ).`}),{flight_status_airline:airline,flight_status_number:number});
 const tracked=(await listCustomerTrackedFlights(s.waId,20)).find((f:any)=>String(f.airlineCode).toUpperCase()===String(airline).toUpperCase()&&String(f.flightNumber)===String(number)&&new Date(f.scheduledDeparture).toISOString().slice(0,10)===date);
 let x:any=tracked?{status:tracked.flightStatus,delayMinutes:tracked.delayMinutes||0,scheduledDeparture:tracked.scheduledDeparture,estimatedDeparture:tracked.estimatedDeparture,scheduledArrival:tracked.scheduledArrival,estimatedArrival:tracked.estimatedArrival,gate:tracked.gate,terminal:tracked.terminal,origin:tracked.origin,destination:tracked.destination}:null;
 const live=await getFlightAwareStatus(String(airline),String(number),String(date));if((live as any).ok)x=(live as any).normalized;if(!x)return this.retry(this.t(s,{fr:`Je n'ai pas encore de statut disponible pour *${airline}${number}* le *${date}*. Vérifiez le numéro/date ou demandez un agent.`,en:`I don't have a status yet for *${airline}${number}* on *${date}*. Check the flight/date or ask for an agent.`,es:`Aún no tengo estado para *${airline}${number}* el *${date}*. Verifique vuelo/fecha o pida un agente.`,ht:`Mwen poko gen estati pou *${airline}${number}* nan *${date}*. Verifye vòl/dat la oswa mande yon ajan.`}));
 const msg=this.t(s,{fr:`✈️ *${airline}${number}* · ${x.origin||''}→${x.destination||''}\nStatut : *${String(x.status).toUpperCase()}*\nDépart prévu : ${fmtDate(x.scheduledDeparture)}\nDépart estimé : ${fmtDate(x.estimatedDeparture)}\nRetard : ${x.delayMinutes||0} min\nPorte/terminal : ${x.gate||'—'} / ${x.terminal||'—'}`,en:`✈️ *${airline}${number}* · ${x.origin||''}→${x.destination||''}\nStatus: *${String(x.status).toUpperCase()}*\nScheduled departure: ${fmtDate(x.scheduledDeparture)}\nEstimated departure: ${fmtDate(x.estimatedDeparture)}\nDelay: ${x.delayMinutes||0} min\nGate/terminal: ${x.gate||'—'} / ${x.terminal||'—'}`,es:`✈️ *${airline}${number}* · ${x.origin||''}→${x.destination||''}\nEstado: *${String(x.status).toUpperCase()}*\nSalida prevista: ${fmtDate(x.scheduledDeparture)}\nSalida estimada: ${fmtDate(x.estimatedDeparture)}\nRetraso: ${x.delayMinutes||0} min\nPuerta/terminal: ${x.gate||'—'} / ${x.terminal||'—'}`,ht:`✈️ *${airline}${number}* · ${x.origin||''}→${x.destination||''}\nEstati: *${String(x.status).toUpperCase()}*\nDepa prevwa: ${fmtDate(x.scheduledDeparture)}\nDepa estime: ${fmtDate(x.estimatedDeparture)}\nReta: ${x.delayMinutes||0} min\nPòt/terminal: ${x.gate||'—'} / ${x.terminal||'—'}`});return this.reply(msg,'segment_service_selection',{flight_status_airline:null,flight_status_number:null,flight_status_date:null,flight_status_choices:null,service_awaiting:true},{autoChain:false});}
 prompt(s:ConversationSession){return this.t(s,{fr:'✈️ Envoyez le numéro de vol et la date.',en:'✈️ Send the flight number and date.',es:'✈️ Envíe el número de vuelo y la fecha.',ht:'✈️ Voye nimewo vòl la ak dat la.'});}}
