import {BaseSegment} from './base';import type {ConversationSession} from '../conversation/types';import {hasCurrencyChoice,paymentCurrencies,paymentOptions,resolvePaymentCountry} from '../payments/matrix';import {createPayment} from '../payments/service';import type {PaymentOption} from '../payments/types';
const yes=(x:string)=>/^(oui|yes|si|sí|wi)$/i.test(x.trim());
function labels(s:ConversationSession,opts:PaymentOption[]){return opts.map((o,i)=>`*${i+1}* — ${o.label}`).join('\n')}
async function manualText(s:ConversationSession,o:PaymentOption,ref:string,ttl:number){if(o.method==='zelle'){const {getSetting}=await import('@/lib/settings/service');const dest=(await getSetting<string>('payments.zelle_email'))||(await getSetting<string>('payments.zelle_phone'))||'—';return `💸 *Zelle*\n\nRéférence: *${ref}*\nEnvoyez le paiement à: *${dest}*\n\nAprès le paiement, envoyez la photo/reçu ici.\n⏱️ Instructions valides ${ttl} minutes.`}if(o.method==='bank_wire'){const {getSetting}=await import('@/lib/settings/service');const instructions=(await getSetting<string>('payments.us_bank_instructions'))||'Instructions bancaires indisponibles.';return `🏦 *Bank transfer*\n\nRéférence: *${ref}*\n${instructions}\n\nEnvoyez ensuite votre reçu ici.\n⏱️ Valide ${ttl} minutes.`;}return''}
export class PaymentChoiceSegment extends BaseSegment{readonly id='segment_payment_choice';async handle(s:ConversationSession,text:string){const country=resolvePaymentCountry(s);let currency=String(s.state.payment_currency??'');if(hasCurrencyChoice(country)&&!currency){const t=text.trim().toUpperCase();if(t==='1'||t==='USD')currency='USD';else if(t==='2'||t==='HTG')currency='HTG';else return this.retry(this.t(s,{fr:'💱 Dans quelle devise souhaitez-vous payer ?\n\n*1* — USD\n*2* — HTG',en:'💱 Which currency would you like to pay in?\n\n*1* — USD\n*2* — HTG',es:'💱 ¿En qué moneda desea pagar?\n\n*1* — USD\n*2* — HTG',ht:'💱 Nan ki lajan ou vle peye?\n\n*1* — USD\n*2* — HTG'}),{payment_country:country,payment_currency_awaiting:true});}
if(!currency)currency=paymentCurrencies(country)[0];const opts=await paymentOptions(country,currency);if(!opts.length)return this.reply(this.t(s,{fr:'⚠️ Les paiements sont momentanément indisponibles. Un agent va vous contacter.',en:'⚠️ Payments are temporarily unavailable. An agent will contact you.',es:'⚠️ Los pagos no están disponibles temporalmente. Un agente se comunicará con usted.',ht:'⚠️ Peman yo pa disponib kounye a. Yon ajan ap kontakte w.'}),'segment_post_booking',{requires_human_review:true,payment_country:country,payment_currency:currency});
const n=Number(text.trim());if(!Number.isInteger(n)||n<1||n>opts.length)return this.retry(`${this.t(s,{fr:'💳 Comment souhaitez-vous payer ?',en:'💳 How would you like to pay?',es:'💳 ¿Cómo desea pagar?',ht:'💳 Kijan ou vle peye?'})}\n\n${labels(s,opts)}`,{payment_country:country,payment_currency:currency,payment_options:opts.map(o=>({key:o.key,method:o.method,provider:o.provider,currency:o.currency,label:o.label,manual:o.manual}))});const chosen=opts[n-1];const r=await createPayment(s,chosen);if(!r.ok){const msg=String(r.error||'payment_create_failed');if(msg.startsWith('currency_conversion_required'))return this.reply(this.t(s,{fr:'⚠️ Une conversion de devise est nécessaire avant ce paiement. Le dossier est transmis à un agent.',en:'⚠️ Currency conversion is required before this payment. The case was sent to an agent.',es:'⚠️ Se requiere conversión de moneda antes de este pago. El caso fue enviado a un agente.',ht:'⚠️ Fòk gen konvèsyon lajan anvan peman sa a. Dosye a voye bay yon ajan.'}),'segment_post_booking',{requires_human_review:true,payment_error:msg});return this.retry(this.t(s,{fr:'⚠️ Ce moyen de paiement est indisponible. Choisissez-en un autre.',en:'⚠️ This payment method is unavailable. Choose another.',es:'⚠️ Este método de pago no está disponible. Elija otro.',ht:'⚠️ Metòd peman sa a pa disponib. Chwazi yon lòt.'}),{last_payment_error:msg});}
const expiresAt=r.expiresAt!;const ttl=Math.max(1,Math.round((expiresAt.getTime()-Date.now())/60000));if(r.manual)return this.reply(await manualText(s,chosen,r.reference,ttl),'segment_payment_confirmation',{payment_reference:r.reference,payment_method:chosen.method,payment_provider:chosen.provider,payment_currency:currency,payment_expires_at:expiresAt.toISOString(),payment_manual:true});return this.reply(`${this.t(s,{fr:'✅ Votre lien de paiement est prêt.',en:'✅ Your payment link is ready.',es:'✅ Su enlace de pago está listo.',ht:'✅ Lyen peman ou pare.'})}\n\n💰 ${currency}\n🔖 *${r.reference}*\n⏱️ ${ttl} min\n\n${r.checkoutUrl}`,'segment_payment_confirmation',{payment_reference:r.reference,payment_method:chosen.method,payment_provider:chosen.provider,payment_currency:currency,payment_expires_at:expiresAt.toISOString(),payment_manual:false,payment_link:r.checkoutUrl});}
prompt(s:ConversationSession){return this.handle(s,'').then(r=>r.message??'');}}
