import type {SegmentHandler} from '../conversation/types';
import {LanguageSegment} from './language';import {ServiceSelectionSegment} from './service-selection';import {TripTypeSegment} from './trip-type';import {PlaceholderSegment} from './placeholder';
import {OriginSegment} from './origin';import {OriginAirportSegment,DestinationAirportSegment} from './airport-choice';import {DestinationSegment} from './destination';import {DepartureDateSegment} from './departure-date';import {ReturnDateSegment} from './return-date';import {PassengersSegment} from './passengers';import {SearchSegment} from './search';import {ResultsSegment} from './results';import {SelectionSegment} from './selection';import {CabinSegment} from './cabin';import {StopsSegment} from './stops';import {AirlineSegment} from './airline';
import {ComplianceSegment} from './compliance';import {PostBookingSegment} from './post-booking';import {FlightStatusSegment} from './flight-status';
import {RepricingSegment} from './repricing';import {PaymentChoiceSegment} from './payment-choice';import {PaymentConfirmationSegment} from './payment-confirmation';import {SavedPassengersSegment} from './saved-passengers';import {NewPassengerSegment} from './new-passenger';import {OcrUploadSegment} from './ocr-upload';import {OcrConfirmationSegment} from './ocr-confirmation';import {ManualPassengerSegment} from './manual-passenger';import {ContactEmailSegment} from './contact-email';import {ContactPhoneSegment} from './contact-phone';import {RecapSegment} from './recap';
const handlers=new Map<string,SegmentHandler>();export function registerSegment(h:SegmentHandler){handlers.set(h.id,h);return h;}
[ new LanguageSegment(),new ServiceSelectionSegment(),new TripTypeSegment(),new OriginSegment(),new OriginAirportSegment(),new DestinationSegment(),new DestinationAirportSegment(),new DepartureDateSegment(),new ReturnDateSegment(),new PassengersSegment(),new CabinSegment(),new StopsSegment(),new AirlineSegment(),new SearchSegment(),new ResultsSegment(),new SelectionSegment(),new RepricingSegment(),new SavedPassengersSegment(),new NewPassengerSegment(),new OcrUploadSegment(),new OcrConfirmationSegment(),new ManualPassengerSegment(),new ContactEmailSegment(),new ContactPhoneSegment(),new ComplianceSegment(),new RecapSegment(),new PaymentChoiceSegment(),new PaymentConfirmationSegment(),new PostBookingSegment(),new FlightStatusSegment() ].forEach(registerSegment);
for(const [id,label] of [['segment_agent_escalation','Autonomous review']] as const)registerSegment(new PlaceholderSegment(id,label));
export function getSegment(id:string){return handlers.get(id)??null;}export function segmentExists(id:string){return handlers.has(id);}export function registeredSegmentIds(){return[...handlers.keys()];}
