import {BaseSegment} from './base'; import {getState} from '../conversation/state'; import type {ConversationSession} from '../conversation/types';
type Service='flights'|'hotels'|'visas'|'my_bookings'|'flight_status'|'agent';
export class ServiceSelectionSegment extends BaseSegment{readonly id='segment_service_selection';handle(session:ConversationSession,text:string){
 const awaiting=getState(session.state,'service_awaiting',false); const selected=getState<string|null>(session.state,'service_selected',null);
 if(selected&&!awaiting)return this.reply(null,this.next(selected as Service));
 if(!awaiting){const auto=this.detect(text);if(auto)return this.reply(null,this.next(auto),{service_selected:auto,service_auto:true,service_awaiting:null},{normalized:auto});return this.retry(this.menu(session),{service_awaiting:true});}
 const choice=this.detect(text);if(!choice)return this.retry(this.t(session,{fr:'Veuillez choisir : *1* Vols, *2* Hôtels, *3* Visas, *4* Mes réservations, *5* Statut de vol',en:'Please choose: *1* Flights, *2* Hotels, *3* Visas, *4* My bookings, *5* Flight status',es:'Elija: *1* Vuelos, *2* Hoteles, *3* Visas, *4* Mis reservas, *5* Estado de vuelo',ht:'Chwazi: *1* Vòl, *2* Otèl, *3* Viza, *4* Rezèvasyon m, *5* Estati vòl'}));
 return this.reply(this.confirm(choice,session),this.next(choice),{service_selected:choice,service_auto:false,service_awaiting:null,business_segment:choice},{normalized:choice});}
 prompt(session:ConversationSession){return this.menu(session);}
 private menu(s:ConversationSession){return this.t(s,{fr:'🌟 Que puis-je faire pour vous aujourd’hui ?\n\n*1️⃣* — ✈️ Vols\n*2️⃣* — 🏨 Hôtels\n*3️⃣* — 📋 Visas\n*4️⃣* — 📂 Mes réservations\n*5️⃣* — 🛫 Statut de vol',en:'🌟 What can I do for you today?\n\n*1️⃣* — ✈️ Flights\n*2️⃣* — 🏨 Hotels\n*3️⃣* — 📋 Visas\n*4️⃣* — 📂 My bookings\n*5️⃣* — 🛫 Flight status',es:'🌟 ¿Qué puedo hacer por usted hoy?\n\n*1️⃣* — ✈️ Vuelos\n*2️⃣* — 🏨 Hoteles\n*3️⃣* — 📋 Visas\n*4️⃣* — 📂 Mis reservas\n*5️⃣* — 🛫 Estado de vuelo',ht:'🌟 Kisa m ka fè pou ou jodi a?\n\n*1️⃣* — ✈️ Vòl\n*2️⃣* — 🏨 Otèl\n*3️⃣* — 📋 Viza\n*4️⃣* — 📂 Rezèvasyon mwen\n*5️⃣* — 🛫 Estati vòl'});}
 private detect(input:string):Service|null{const t=input.trim().toLocaleLowerCase();if(t==='1')return'flights';if(t==='2')return'hotels';if(t==='3')return'visas';if(t==='4')return'my_bookings';if(t==='5')return'flight_status';if(/^(hello|hi|hey|hola|buenos|bonjour|bonsoir|salut|bonjou|bonswa)[\s!.,]*$/iu.test(t))return null;if(/\b(flight status|statut (du )?vol|estado (del )?vuelo|estati vòl|retard|delay|delayed|porte|gate|cancelled|canceled)\b/iu.test(t))return'flight_status';if(/^doni-[a-z0-9-]{4,32}$/i.test(t)||/\b(my\s+(booking|reservation|ticket)|mes réservations|mis reservas|rezèvasyon|pnr|annul|cancel|cancelar|anile|booking\s+(code|reference))\b/iu.test(t))return'my_bookings';if(/\b(flight|flights|vol|vols|vuelo|vuelos|vòl|ticket|billet|boleto|tikè|tikèt|fly|voyage|trip)\b/iu.test(t))return'flights';if(/\b(hotel|hôtel|otèl|otel|room|chambre|habitación|chanm)\b/iu.test(t))return'hotels';if(/\b(visa|viza|consular|consulat|consulado|embassy|ambassade|embajada)\b/iu.test(t))return'visas';if(/\b(agent|agente|ajan|humain|human being)\b/iu.test(t))return'agent';return null;}
 private next(s:Service){return s==='flights'?'segment_trip_type':s==='my_bookings'?'segment_post_booking':s==='flight_status'?'segment_flight_status':'segment_agent_escalation';}
 private confirm(c:Service,s:ConversationSession){const values:Record<Service,Parameters<typeof this.t>[1]>={flights:{fr:'✈️ Très bien, cherchons un vol !\n\nVoyage *aller simple (1)* ou *aller-retour (2)* ?',en:"✈️ Great, let's find a flight!\n\n*One-way (1)* or *round trip (2)* ?",es:'✈️ ¡Perfecto, busquemos un vuelo!\n\n¿Viaje de *ida (1)* o *ida y vuelta (2)* ?',ht:'✈️ Anfòm, ann chèche yon vòl!\n\nVwayaj *sèl ale (1)* oswa *ale-retou (2)* ?'},hotels:{fr:"🏨 Très bien ! Je prépare votre demande d'hôtel.",en:'🏨 Great! I am preparing your hotel request.',es:'🏨 ¡Perfecto! Preparo su solicitud de hotel.',ht:'🏨 Anfòm! M ap prepare demand otèl ou.'},visas:{fr:'📋 Très bien ! Je prépare votre demande visa.',en:'📋 Great! I am preparing your visa request.',es:'📋 ¡Perfecto! Preparo su solicitud de visa.',ht:'📋 Anfòm! M ap prepare demand viza ou.'},my_bookings:{fr:'📂 Je recherche vos réservations liées à ce numéro.',en:'📂 I am looking for bookings linked to this number.',es:'📂 Busco las reservas vinculadas a este número.',ht:'📂 M ap chèche rezèvasyon ki lye ak nimewo sa a.'},flight_status:{fr:'🛫 Je vérifie votre statut de vol.',en:'🛫 I will check your flight status.',es:'🛫 Verificaré el estado de su vuelo.',ht:'🛫 M ap verifye estati vòl ou.'},agent:{fr:"Bien sûr, je m'occupe de votre demande.",en:"Of course, I'm handling your request.",es:'Por supuesto, me ocupo de su solicitud.',ht:'Byen sûr, m ap pran swen demand ou.'}};return this.t(s,values[c]);}}
