import {db} from '@/lib/db';
import {taskAssignees} from '@/lib/workspace/tasks';

export type CasePriority='LOW'|'NORMAL'|'HIGH'|'URGENT';
export type CaseNote={id:string;body:string;createdAt:string;createdById:string;createdByName:string};
export type CaseWorkspaceState={kind:string;caseId:string;ownerId?:string|null;ownerName?:string|null;priority:CasePriority;tags:string[];nextAction?:string|null;nextActionDueAt?:string|null;notes:CaseNote[];updatedAt:string;history:Array<{at:string;by:string;action:string;from?:string|null;to?:string|null}>};
const CATEGORY='Case 360 Workspace';
const PREFIX='workspace.case.';
function key(kind:string,id:string){return `${PREFIX}${kind}.${id}`;}
function parse(v:unknown):CaseWorkspaceState|null{if(!v||typeof v!=='object')return null;const x=v as CaseWorkspaceState;return x.kind&&x.caseId&&Array.isArray(x.tags)&&Array.isArray(x.notes)&&Array.isArray(x.history)?x:null;}
export async function getCaseWorkspace(kind:string,caseId:string){const row=await db.appSetting.findUnique({where:{key:key(kind,caseId)}});return parse(row?.value);}
export async function listCaseWorkspaces(){const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PREFIX}},orderBy:{updatedAt:'desc'}});return rows.map(r=>parse(r.value)).filter((x):x is CaseWorkspaceState=>x!==null);}
export async function ensureCaseWorkspace(kind:string,caseId:string){const current=await getCaseWorkspace(kind,caseId);if(current)return current;const now=new Date().toISOString();const state:CaseWorkspaceState={kind,caseId,ownerId:null,ownerName:null,priority:'NORMAL',tags:[],nextAction:null,nextActionDueAt:null,notes:[],updatedAt:now,history:[]};await db.appSetting.create({data:{key:key(kind,caseId),category:CATEGORY,value:state as any,updatedBy:'DONI_CASE_360'}});return state;}
export async function updateCaseWorkspace(kind:string,caseId:string,patch:Partial<Pick<CaseWorkspaceState,'ownerId'|'priority'|'tags'|'nextAction'|'nextActionDueAt'>>,{userId,userName}:{userId:string;userName:string}){const current=await ensureCaseWorkspace(kind,caseId);const next:any={...current};const history=[...(current.history||[])];for(const [field,value] of Object.entries(patch)){if(value===undefined)continue;const before=(current as any)[field];const normalized=field==='tags'&&Array.isArray(value)?value.slice(0,10).map(x=>String(x).trim()).filter(Boolean):value;if(JSON.stringify(before)!==JSON.stringify(normalized)){next[field]=normalized;history.push({at:new Date().toISOString(),by:userName,action:`UPDATE_${field.toUpperCase()}`,from:before==null?null:Array.isArray(before)?before.join(', '):String(before),to:normalized==null?null:Array.isArray(normalized)?normalized.join(', '):String(normalized)});}}
if(patch.ownerId!==undefined){if(patch.ownerId){const u=await db.portalUser.findUnique({where:{id:patch.ownerId},select:{fullName:true,username:true}});next.ownerName=u?.fullName||u?.username||null;}else next.ownerName=null;}
next.updatedAt=new Date().toISOString();next.history=history.slice(-80);await db.appSetting.update({where:{key:key(kind,caseId)},data:{value:next as any,updatedBy:userId}});return next as CaseWorkspaceState;}
export async function addCaseNote(kind:string,caseId:string,body:string,{userId,userName}:{userId:string;userName:string}){const current=await ensureCaseWorkspace(kind,caseId);const text=body.trim().slice(0,4000);if(!text)throw new Error('empty_note');const now=new Date().toISOString();const note:CaseNote={id:`note_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,body:text,createdAt:now,createdById:userId,createdByName:userName};const next={...current,notes:[note,...(current.notes||[])].slice(0,100),updatedAt:now,history:[...(current.history||[]),{at:now,by:userName,action:'ADD_NOTE',to:text.slice(0,120)}].slice(-80)};await db.appSetting.update({where:{key:key(kind,caseId)},data:{value:next as any,updatedBy:userId}});return next as CaseWorkspaceState;}
export async function caseWorkspaceAssignees(){return taskAssignees();}
