import {randomUUID} from 'node:crypto';
import {db} from '@/lib/db';
import {marketingAssignees} from '@/lib/workspace/marketing';

export const INSIGHT_TYPES=['COMPETITOR','PRICE','TREND','DESTINATION','OPPORTUNITY','RISK'] as const;
export const INSIGHT_STATUSES=['NEW','TO_ANALYZE','ACTIONABLE','MONITORED','ARCHIVED'] as const;
export const INSIGHT_PRIORITIES=['LOW','MEDIUM','HIGH','CRITICAL'] as const;
export type InsightType=(typeof INSIGHT_TYPES)[number];
export type InsightStatus=(typeof INSIGHT_STATUSES)[number];
export type InsightPriority=(typeof INSIGHT_PRIORITIES)[number];
export type MarketingInsight={id:string;title:string;type:InsightType;status:InsightStatus;priority:InsightPriority;market?:string|null;destination?:string|null;competitor?:string|null;observedPrice?:number|null;currency?:string|null;sourceName?:string|null;sourceUrl?:string|null;observation:string;recommendedAction?:string|null;ownerId?:string|null;ownerName?:string|null;observedAt:string;nextReviewAt?:string|null;createdAt:string;updatedAt:string;createdById:string;updatedByName:string};
const CATEGORY='Marketing Insights',PREFIX='marketing.insight.';
function parse(v:unknown):MarketingInsight|null{if(!v||typeof v!=='object')return null;const x=v as MarketingInsight;return x.id&&x.title&&x.observation&&INSIGHT_TYPES.includes(x.type)&&INSIGHT_STATUSES.includes(x.status)&&INSIGHT_PRIORITIES.includes(x.priority)?x:null;}
function num(v:unknown){const n=Number(v);return Number.isFinite(n)&&n>=0?n:null;}
async function ownerName(id?:string|null){if(!id)return null;const users=await marketingAssignees();const u=users.find((x:any)=>x.id===id);return u?.fullName||u?.username||u?.name||null;}
export async function listMarketingInsights(){const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PREFIX}},orderBy:{updatedAt:'desc'}});return rows.map(r=>parse(r.value)).filter((x):x is MarketingInsight=>x!==null);}
export async function createMarketingInsight(input:{title:string;type:InsightType;status?:InsightStatus;priority?:InsightPriority;market?:string|null;destination?:string|null;competitor?:string|null;observedPrice?:number|null;currency?:string|null;sourceName?:string|null;sourceUrl?:string|null;observation:string;recommendedAction?:string|null;ownerId?:string|null;observedAt?:string|null;nextReviewAt?:string|null;createdById:string;createdByName:string}){const now=new Date().toISOString(),id=randomUUID();const item:MarketingInsight={id,title:input.title.trim(),type:input.type,status:input.status||'NEW',priority:input.priority||'MEDIUM',market:input.market?.trim()||null,destination:input.destination?.trim()||null,competitor:input.competitor?.trim()||null,observedPrice:num(input.observedPrice),currency:input.currency?.trim().toUpperCase()||null,sourceName:input.sourceName?.trim()||null,sourceUrl:input.sourceUrl?.trim()||null,observation:input.observation.trim(),recommendedAction:input.recommendedAction?.trim()||null,ownerId:input.ownerId||null,ownerName:await ownerName(input.ownerId),observedAt:input.observedAt||now,nextReviewAt:input.nextReviewAt||null,createdAt:now,updatedAt:now,createdById:input.createdById,updatedByName:input.createdByName};await db.appSetting.create({data:{key:`${PREFIX}${id}`,category:CATEGORY,value:item as any,updatedBy:input.createdById}});return item;}
export async function updateMarketingInsight(id:string,patch:Partial<Pick<MarketingInsight,'title'|'type'|'status'|'priority'|'market'|'destination'|'competitor'|'observedPrice'|'currency'|'sourceName'|'sourceUrl'|'observation'|'recommendedAction'|'ownerId'|'observedAt'|'nextReviewAt'>>,{userId,userName}:{userId:string;userName:string}){const key=`${PREFIX}${id}`;const row=await db.appSetting.findUnique({where:{key}});const current=parse(row?.value);if(!current)throw new Error('marketing_insight_not_found');const next:any={...current,...patch,updatedAt:new Date().toISOString(),updatedByName:userName};if(patch.observedPrice!==undefined)next.observedPrice=num(patch.observedPrice);if(patch.currency!==undefined)next.currency=patch.currency?.trim().toUpperCase()||null;if(patch.ownerId!==undefined)next.ownerName=await ownerName(patch.ownerId);await db.appSetting.update({where:{key},data:{value:next as any,updatedBy:userId}});return next as MarketingInsight;}
export async function marketingInsightMeta(){return {assignees:await marketingAssignees()};}
export function insightMetrics(items:MarketingInsight[]){const active=items.filter(x=>x.status!=='ARCHIVED');const due=active.filter(x=>x.nextReviewAt&&new Date(x.nextReviewAt).getTime()<=Date.now());const high=active.filter(x=>['HIGH','CRITICAL'].includes(x.priority));const opportunities=active.filter(x=>x.type==='OPPORTUNITY');return {total:items.length,active:active.length,due:due.length,high:high.length,opportunities:opportunities.length};}
