import {db} from '@/lib/db';
import {detectLanguage} from '@/services/conversation/language-engine';
import type {ConversationSession,DoniLanguage} from '@/services/conversation/types';

const AUTOPILOT_PREFIX='marketing.autopilot.';
const DELIVERY_PREFIX='marketing.delivery.';

export type MarketingBookingEntry={campaignId:string;title:string;origin:string;destination:string;advertisedPrice:number|null;currency:string|null;source:string;entryMode:'LINK'|'WHATSAPP_REPLY'};

function tokenFromText(text:string){const m=String(text||'').match(/(?:DONI[-_\s]?CMP|CMP)\s*[:#-]?\s*([0-9a-f]{8}-[0-9a-f-]{27,})/i);return m?.[1]||null;}
function replyProviderId(raw:unknown){const x=raw as any;return String(x?.context?.id||x?.context?.message_id||'').trim()||null;}
function parseRoute(route:unknown){const raw=String(route||'').toUpperCase().trim();const m=raw.match(/\b([A-Z]{3})\b\s*(?:→|->|–|—|-)\s*\b([A-Z]{3})\b/);return m?{origin:m[1],destination:m[2]}:null;}
async function campaignIdFromReply(raw:unknown){const providerMessageId=replyProviderId(raw);if(!providerMessageId)return null;const row=await db.appSetting.findUnique({where:{key:`${DELIVERY_PREFIX}${providerMessageId}`}});const value=row?.value as any;return value?.itemId?String(value.itemId):null;}
async function loadCampaign(campaignId:string,entryMode:MarketingBookingEntry['entryMode']){const row=await db.appSetting.findUnique({where:{key:`${AUTOPILOT_PREFIX}${campaignId}`}});const item=row?.value as any;if(!item?.id||String(item.status)!=='SENT')return null;const route=parseRoute(item.route);if(!route)return null;return{campaignId:String(item.id),title:String(item.title||`${route.origin} → ${route.destination}`),origin:route.origin,destination:route.destination,advertisedPrice:Number.isFinite(Number(item.amount))?Number(item.amount):null,currency:item.currency?String(item.currency).toUpperCase():null,source:String(item.source||'DONI Marketing'),entryMode} satisfies MarketingBookingEntry;}

export function marketingCampaignToken(campaignId:string){return `DONI-CMP:${campaignId}`;}
export function marketingCampaignPrefill(campaignId:string,language:DoniLanguage='fr'){const token=marketingCampaignToken(campaignId);return language==='es'?`Quiero verificar esta oferta ${token}`:language==='en'?`I want to verify this offer ${token}`:language==='ht'?`Mwen vle verifye òf sa a ${token}`:`Je veux vérifier cette offre ${token}`;}

export async function resolveMarketingBookingEntry(text:string,raw:unknown){const token=tokenFromText(text);if(token){const campaign=await loadCampaign(token,'LINK');if(campaign)return campaign;}const replyCampaignId=await campaignIdFromReply(raw);if(replyCampaignId)return loadCampaign(replyCampaignId,'WHATSAPP_REPLY');return null;}

function localizedPrompt(language:DoniLanguage|null,entry:MarketingBookingEntry){const route=`*${entry.origin} → ${entry.destination}*`;const price=entry.advertisedPrice!==null&&entry.currency?` · ${entry.advertisedPrice.toFixed(2)} ${entry.currency}`:'';if(language==='es')return `✈️ He reconocido la oferta ${route}${price}.\n\nAntes de confirmar cualquier precio debo buscar disponibilidad real para tu viaje.\n\n📅 ¿Cuál es tu *fecha de salida*?`;if(language==='en')return `✈️ I found the offer ${route}${price}.\n\nBefore confirming any price I must check live availability for your trip.\n\n📅 What is your *departure date*?`;if(language==='ht')return `✈️ Mwen jwenn òf ${route}${price}.\n\nAnvan mwen konfime nenpòt pri, mwen dwe verifye disponibilite reyèl pou vwayaj la.\n\n📅 Ki *dat depa* ou?`;return `✈️ J’ai reconnu l’offre ${route}${price}.\n\nAvant de confirmer un prix, je dois vérifier la disponibilité réelle pour votre voyage.\n\n📅 Quelle est votre *date de départ* ?`;}

export async function activateMarketingBookingHandoff(session:ConversationSession,entry:MarketingBookingEntry,text:string){const detected=(detectLanguage(text)??session.lockedLanguage??null) as DoniLanguage|null;const previousCriteria=(session.state.criteria??{}) as Record<string,unknown>;const now=new Date().toISOString();const state={...session.state,business_segment:'flights',service_awaiting:false,criteria:{...previousCriteria,origin:entry.origin,destination:entry.destination,trip_type:null,depart_date:null,return_date:null,passengers:null},marketing_handoff:{active:true,campaign_id:entry.campaignId,title:entry.title,entry_mode:entry.entryMode,origin:entry.origin,destination:entry.destination,advertised_price:entry.advertisedPrice,advertised_currency:entry.currency,source:entry.source,started_at:now,fare_verification_required:true,price_confirmed:false},marketing_campaign_id:entry.campaignId,marketing_source:entry.source,advertised_route:`${entry.origin}-${entry.destination}`,advertised_price:entry.advertisedPrice,advertised_currency:entry.currency} as any;const row=await db.doniConversation.update({where:{id:session.id},data:{previousSegment:session.currentSegment,currentSegment:'segment_departure_date',businessSegment:'flights',state,lockedLanguage:session.lockedLanguage??detected,lastMessageAt:new Date()}});return{session:{...session,currentSegment:'segment_departure_date',previousSegment:session.currentSegment,businessSegment:'flights',state,lockedLanguage:(row.lockedLanguage??detected) as DoniLanguage|null,lastMessageAt:row.lastMessageAt},message:localizedPrompt((row.lockedLanguage??detected) as DoniLanguage|null,entry)};}
