import {randomUUID} from 'node:crypto';
import {db} from '@/lib/db';

const CATEGORY='DONI Marketing Delivery Tracking';
const PREFIX='marketing.delivery.';
const EVENT_CATEGORY='DONI Marketing Delivery Events';
const EVENT_PREFIX='marketing.delivery.event.';
const REPLY_WINDOW_MS=72*60*60*1000;
const CONVERSION_WINDOW_MS=7*24*60*60*1000;

type DeliveryStatus='SENT'|'DELIVERED'|'READ'|'FAILED'|'REPLIED';
type TrackingRecord={itemId:string;conversationId:string|null;recipient:string;providerMessageId:string;status:DeliveryStatus;sentAt:string;deliveredAt?:string|null;readAt?:string|null;failedAt?:string|null;repliedAt?:string|null;replyMessageId?:string|null;failureReason?:string|null;updatedAt:string};

function normalizeRecipient(v:string){return String(v||'').replace(/[^0-9]/g,'');}
function key(id:string){return `${PREFIX}${id}`;}
function parse(v:unknown):TrackingRecord|null{if(!v||typeof v!=='object')return null;const x=v as TrackingRecord;return x.itemId&&x.providerMessageId?x:null;}
async function logEvent(type:string,record:TrackingRecord,details:Record<string,unknown>={}){const now=new Date().toISOString();await db.appSetting.create({data:{key:`${EVENT_PREFIX}${now}.${randomUUID()}`,category:EVENT_CATEGORY,value:{type,itemId:record.itemId,conversationId:record.conversationId,recipient:record.recipient,providerMessageId:record.providerMessageId,at:now,...details} as any}});}

export async function registerMarketingOutbound(input:{itemId:string;conversationId?:string|null;recipient:string;providerMessageId:string;sentAt?:string}){const now=input.sentAt||new Date().toISOString();const record:TrackingRecord={itemId:input.itemId,conversationId:input.conversationId||null,recipient:normalizeRecipient(input.recipient),providerMessageId:input.providerMessageId,status:'SENT',sentAt:now,updatedAt:now};await db.appSetting.upsert({where:{key:key(input.providerMessageId)},create:{key:key(input.providerMessageId),category:CATEGORY,value:record as any},update:{category:CATEGORY,value:record as any}});await logEvent('SENT',record);return record;}

export async function recordMarketingDeliveryStatus(input:{providerMessageId:string;status:string;timestamp?:string|null;recipient?:string|null;errors?:unknown}){const row=await db.appSetting.findUnique({where:{key:key(input.providerMessageId)}});const record=parse(row?.value);if(!record)return{matched:false} as const;const raw=String(input.status||'').toLowerCase();const mapped:DeliveryStatus|null=raw==='delivered'?'DELIVERED':raw==='read'?'READ':raw==='failed'?'FAILED':raw==='sent'?'SENT':null;if(!mapped)return{matched:true,ignored:true} as const;const at=input.timestamp?new Date(Number(input.timestamp)*1000).toISOString():new Date().toISOString();const next:TrackingRecord={...record,status:mapped,updatedAt:new Date().toISOString()};if(mapped==='DELIVERED')next.deliveredAt=at;if(mapped==='READ')next.readAt=at;if(mapped==='FAILED'){next.failedAt=at;next.failureReason=input.errors?JSON.stringify(input.errors).slice(0,500):'provider_failed';}await db.appSetting.update({where:{key:key(input.providerMessageId)},data:{value:next as any}});await logEvent(mapped,next,{providerStatus:raw,errors:input.errors||null});return{matched:true,record:next} as const;}

export async function recordMarketingReply(recipient:string,replyMessageId:string){const normalized=normalizeRecipient(recipient);const cutoff=new Date(Date.now()-REPLY_WINDOW_MS);const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PREFIX},updatedAt:{gte:cutoff}},orderBy:{updatedAt:'desc'},take:200});const record=rows.map(r=>parse(r.value)).find(x=>x&&x.recipient===normalized&&!x.repliedAt);if(!record)return{matched:false} as const;const now=new Date().toISOString();const next:TrackingRecord={...record,status:'REPLIED',repliedAt:now,replyMessageId,updatedAt:now};await db.appSetting.update({where:{key:key(record.providerMessageId)},data:{value:next as any}});await logEvent('REPLIED',next,{replyMessageId,attribution:'last_marketing_touch_72h'});return{matched:true,itemId:record.itemId} as const;}

export async function getMarketingDeliveryDashboard(){const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PREFIX}},orderBy:{updatedAt:'desc'},take:500});const records=rows.map(r=>parse(r.value)).filter((x):x is TrackingRecord=>Boolean(x));const counts={SENT:records.length,DELIVERED:records.filter(x=>Boolean(x.deliveredAt||x.readAt)).length,READ:records.filter(x=>Boolean(x.readAt)).length,FAILED:records.filter(x=>Boolean(x.failedAt)).length,REPLIED:records.filter(x=>Boolean(x.repliedAt)).length};const deliveredRate=counts.SENT?Math.round(counts.DELIVERED/counts.SENT*1000)/10:0;const readRate=counts.SENT?Math.round(counts.READ/counts.SENT*1000)/10:0;const replyRate=counts.SENT?Math.round(counts.REPLIED/counts.SENT*1000)/10:0;const conversationIds=[...new Set(records.map(r=>r.conversationId).filter((x):x is string=>Boolean(x)))];const earliest=records.length?new Date(Math.min(...records.map(r=>new Date(r.sentAt).getTime()))):new Date();const payments=conversationIds.length?await db.payment.findMany({where:{conversationId:{in:conversationIds},status:'PAID',updatedAt:{gte:earliest}},select:{conversationId:true,amount:true,currency:true,updatedAt:true}}):[];const byConversation=new Map<string,typeof payments>();for(const p of payments){if(!p.conversationId)continue;const list=byConversation.get(p.conversationId)||[];list.push(p);byConversation.set(p.conversationId,list);}let conversions=0;const revenueByCurrency:Record<string,number>={};for(const r of records){if(!r.conversationId)continue;const sentMs=new Date(r.sentAt).getTime();const until=sentMs+CONVERSION_WINDOW_MS;const matched=(byConversation.get(r.conversationId)||[]).filter(p=>{const t=p.updatedAt.getTime();return t>=sentMs&&t<=until;});if(matched.length){conversions++;for(const p of matched){const c=String(p.currency);revenueByCurrency[c]=(revenueByCurrency[c]||0)+Number(p.amount);}}}const conversionRate=counts.SENT?Math.round(conversions/counts.SENT*1000)/10:0;const events=await db.appSetting.findMany({where:{category:EVENT_CATEGORY,key:{startsWith:EVENT_PREFIX}},orderBy:{createdAt:'desc'},take:200});return{counts,rates:{deliveredRate,readRate,replyRate,conversionRate},conversions,revenueByCurrency,records,events:events.map(e=>e.value as any).filter(Boolean),generatedAt:new Date().toISOString()};}
