import {randomUUID} from 'node:crypto';
import {db} from '@/lib/db';
import {taskAssignees} from '@/lib/workspace/tasks';

export const MARKETING_LEAD_STATUSES=['NEW','QUALIFIED','HOT','QUOTE_SENT','FOLLOW_UP','CONVERTED','LOST'] as const;
export const MARKETING_SOURCES=['WHATSAPP','FACEBOOK','INSTAGRAM','TIKTOK','GOOGLE','REFERRAL','FIELD','OTHER'] as const;
export const CONTENT_STATUSES=['DRAFT','REVIEW','APPROVED','SCHEDULED','PUBLISHED'] as const;
export const CONTENT_PLATFORMS=['FACEBOOK','INSTAGRAM','TIKTOK','WHATSAPP'] as const;
export const CONTENT_FORMATS=['POST','STORY','REEL','TIKTOK','OFFER','TESTIMONIAL'] as const;
export type MarketingLeadStatus=(typeof MARKETING_LEAD_STATUSES)[number];
export type MarketingSource=(typeof MARKETING_SOURCES)[number];
export type MarketingContentStatus=(typeof CONTENT_STATUSES)[number];
export type MarketingLead={id:string;name:string;phone?:string|null;email?:string|null;source:MarketingSource;status:MarketingLeadStatus;destination?:string|null;budget?:number|null;currency?:string|null;travelDate?:string|null;ownerId?:string|null;ownerName?:string|null;nextFollowUpAt?:string|null;notes?:string|null;createdAt:string;updatedAt:string;createdById:string};
export type MarketingContent={id:string;title:string;caption?:string|null;platform:string;format:string;status:MarketingContentStatus;scheduledAt?:string|null;ownerId?:string|null;ownerName?:string|null;campaign?:string|null;createdAt:string;updatedAt:string;createdById:string};
const LEAD_CATEGORY='Marketing Leads',CONTENT_CATEGORY='Marketing Content',LEAD_PREFIX='marketing.lead.',CONTENT_PREFIX='marketing.content.';
function isLead(v:unknown):v is MarketingLead{if(!v||typeof v!=='object')return false;const x=v as MarketingLead;return Boolean(x.id&&x.name&&MARKETING_LEAD_STATUSES.includes(x.status)&&MARKETING_SOURCES.includes(x.source));}
function isContent(v:unknown):v is MarketingContent{if(!v||typeof v!=='object')return false;const x=v as MarketingContent;return Boolean(x.id&&x.title&&CONTENT_STATUSES.includes(x.status));}
async function assigneeName(id?:string|null){if(!id)return null;const u=await db.portalUser.findUnique({where:{id},select:{fullName:true,username:true}});return u?.fullName||u?.username||null;}
export async function listMarketingLeads(){const rows=await db.appSetting.findMany({where:{category:LEAD_CATEGORY,key:{startsWith:LEAD_PREFIX}},orderBy:{updatedAt:'desc'}});return rows.map(r=>r.value).filter(isLead);}
export async function createMarketingLead(input:{name:string;phone?:string|null;email?:string|null;source:MarketingSource;status?:MarketingLeadStatus;destination?:string|null;budget?:number|null;currency?:string|null;travelDate?:string|null;ownerId?:string|null;nextFollowUpAt?:string|null;notes?:string|null;createdById:string}){const now=new Date().toISOString();const id=randomUUID();const lead:MarketingLead={id,name:input.name.trim(),phone:input.phone?.trim()||null,email:input.email?.trim()||null,source:input.source,status:input.status||'NEW',destination:input.destination?.trim()||null,budget:input.budget??null,currency:input.currency?.trim()||null,travelDate:input.travelDate||null,ownerId:input.ownerId||null,ownerName:await assigneeName(input.ownerId),nextFollowUpAt:input.nextFollowUpAt||null,notes:input.notes?.trim()||null,createdAt:now,updatedAt:now,createdById:input.createdById};await db.appSetting.create({data:{key:`${LEAD_PREFIX}${id}`,category:LEAD_CATEGORY,value:lead as any,updatedBy:input.createdById}});return lead;}
export async function updateMarketingLead(id:string,patch:Partial<Omit<MarketingLead,'id'|'createdAt'|'createdById'>>,{userId}:{userId:string}){const key=`${LEAD_PREFIX}${id}`;const row=await db.appSetting.findUnique({where:{key}});if(!isLead(row?.value))throw new Error('lead_not_found');const next:any={...row!.value,...patch,updatedAt:new Date().toISOString()};if(patch.ownerId!==undefined)next.ownerName=await assigneeName(patch.ownerId);await db.appSetting.update({where:{key},data:{value:next,updatedBy:userId}});return next as MarketingLead;}
export async function listMarketingContent(){const rows=await db.appSetting.findMany({where:{category:CONTENT_CATEGORY,key:{startsWith:CONTENT_PREFIX}},orderBy:{updatedAt:'desc'}});return rows.map(r=>r.value).filter(isContent);}
export async function createMarketingContent(input:{title:string;caption?:string|null;platform:string;format:string;status?:MarketingContentStatus;scheduledAt?:string|null;ownerId?:string|null;campaign?:string|null;createdById:string}){const now=new Date().toISOString();const id=randomUUID();const item:MarketingContent={id,title:input.title.trim(),caption:input.caption?.trim()||null,platform:input.platform,format:input.format,status:input.status||'DRAFT',scheduledAt:input.scheduledAt||null,ownerId:input.ownerId||null,ownerName:await assigneeName(input.ownerId),campaign:input.campaign?.trim()||null,createdAt:now,updatedAt:now,createdById:input.createdById};await db.appSetting.create({data:{key:`${CONTENT_PREFIX}${id}`,category:CONTENT_CATEGORY,value:item as any,updatedBy:input.createdById}});return item;}
export async function updateMarketingContent(id:string,patch:Partial<Omit<MarketingContent,'id'|'createdAt'|'createdById'>>,{userId}:{userId:string}){const key=`${CONTENT_PREFIX}${id}`;const row=await db.appSetting.findUnique({where:{key}});if(!isContent(row?.value))throw new Error('content_not_found');const next:any={...row!.value,...patch,updatedAt:new Date().toISOString()};if(patch.ownerId!==undefined)next.ownerName=await assigneeName(patch.ownerId);await db.appSetting.update({where:{key},data:{value:next,updatedBy:userId}});return next as MarketingContent;}
export async function marketingAssignees(){return taskAssignees();}
