import {randomUUID} from 'node:crypto';
import {db} from '@/lib/db';

export const MARKETING_PLAN_PERIODS=['DAY','WEEK','MONTH','YEAR'] as const;
export const MARKETING_PLAN_STATUSES=['DRAFT','ACTIVE','REVIEW','COMPLETED'] as const;
export type MarketingPlanPeriod=(typeof MARKETING_PLAN_PERIODS)[number];
export type MarketingPlanStatus=(typeof MARKETING_PLAN_STATUSES)[number];
export type MarketingPlan={id:string;period:MarketingPlanPeriod;periodKey:string;title:string;focus:string;theme?:string|null;objectives:string[];budget?:number|null;currency?:string|null;specialAction?:string|null;trainingTopic?:string|null;reportNotes?:string|null;status:MarketingPlanStatus;createdAt:string;updatedAt:string;createdById:string;updatedByName:string;history:Array<{at:string;by:string;action:string}>};
const CATEGORY='Marketing Planning',PREFIX='marketing.plan.';
function parse(v:unknown):MarketingPlan|null{if(!v||typeof v!=='object')return null;const x=v as MarketingPlan;return x.id&&x.period&&x.periodKey&&x.title&&Array.isArray(x.objectives)&&Array.isArray(x.history)?x:null;}
function safeNum(v:unknown){const n=Number(v);return Number.isFinite(n)&&n>=0?n:null;}
export async function listMarketingPlans(){const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PREFIX}},orderBy:{updatedAt:'desc'}});return rows.map(r=>parse(r.value)).filter((x):x is MarketingPlan=>x!==null);}
export async function createMarketingPlan(input:{period:MarketingPlanPeriod;periodKey:string;title:string;focus:string;theme?:string|null;objectives?:string[];budget?:number|null;currency?:string|null;specialAction?:string|null;trainingTopic?:string|null;status?:MarketingPlanStatus;createdById:string;createdByName:string}){const now=new Date().toISOString(),id=randomUUID();const plan:MarketingPlan={id,period:input.period,periodKey:input.periodKey.trim(),title:input.title.trim(),focus:input.focus.trim(),theme:input.theme?.trim()||null,objectives:(input.objectives||[]).map(x=>x.trim()).filter(Boolean).slice(0,20),budget:safeNum(input.budget),currency:input.currency?.trim().toUpperCase()||null,specialAction:input.specialAction?.trim()||null,trainingTopic:input.trainingTopic?.trim()||null,reportNotes:null,status:input.status||'DRAFT',createdAt:now,updatedAt:now,createdById:input.createdById,updatedByName:input.createdByName,history:[{at:now,by:input.createdByName,action:'CREATED'}]};await db.appSetting.create({data:{key:`${PREFIX}${id}`,category:CATEGORY,value:plan as any,updatedBy:input.createdById}});return plan;}
export async function updateMarketingPlan(id:string,patch:Partial<Pick<MarketingPlan,'title'|'focus'|'theme'|'objectives'|'budget'|'currency'|'specialAction'|'trainingTopic'|'reportNotes'|'status'>>,{userId,userName}:{userId:string;userName:string}){const key=`${PREFIX}${id}`;const row=await db.appSetting.findUnique({where:{key}});const current=parse(row?.value);if(!current)throw new Error('marketing_plan_not_found');const next:any={...current,...patch,updatedAt:new Date().toISOString(),updatedByName:userName};if(patch.objectives)next.objectives=patch.objectives.map(x=>x.trim()).filter(Boolean).slice(0,20);if(patch.budget!==undefined)next.budget=safeNum(patch.budget);if(patch.currency!==undefined)next.currency=patch.currency?.trim().toUpperCase()||null;next.history=[...(current.history||[]),{at:new Date().toISOString(),by:userName,action:patch.status?`STATUS_${patch.status}`:'UPDATED'}].slice(-100);await db.appSetting.update({where:{key},data:{value:next as any,updatedBy:userId}});return next as MarketingPlan;}
