import {randomUUID} from 'node:crypto';
import {db} from '@/lib/db';

export const REVIEW_SOURCES=['GOOGLE','WHATSAPP','FACEBOOK','INSTAGRAM','TRUSTPILOT','EMAIL','IN_PERSON','OTHER'] as const;
export const REVIEW_STATUSES=['NEW','FOLLOW_UP','RESOLVED','PUBLISHED_TESTIMONIAL','ARCHIVED'] as const;
export type ReviewSource=(typeof REVIEW_SOURCES)[number];
export type ReviewStatus=(typeof REVIEW_STATUSES)[number];
export type MarketingReview={id:string;customerName:string;source:ReviewSource;rating:number;reviewText?:string|null;reviewUrl?:string|null;destination?:string|null;bookingReference?:string|null;consentMarketing:boolean;consentNote?:string|null;status:ReviewStatus;responseRequired:boolean;responseNotes?:string|null;testimonialAssetId?:string|null;receivedAt:string;createdAt:string;updatedAt:string;createdById:string;updatedByName:string};
const CATEGORY='Marketing Reviews',PREFIX='marketing.review.';
function parse(v:unknown):MarketingReview|null{if(!v||typeof v!=='object')return null;const x=v as MarketingReview;return x.id&&x.customerName&&REVIEW_SOURCES.includes(x.source)&&REVIEW_STATUSES.includes(x.status)&&Number.isFinite(Number(x.rating))?x:null;}
function rating(v:unknown){const n=Number(v);return Number.isFinite(n)?Math.max(1,Math.min(5,Math.round(n))):5;}
export async function listMarketingReviews(){const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PREFIX}},orderBy:{updatedAt:'desc'}});return rows.map(r=>parse(r.value)).filter((x):x is MarketingReview=>x!==null);}
export async function createMarketingReview(input:{customerName:string;source:ReviewSource;rating:number;reviewText?:string|null;reviewUrl?:string|null;destination?:string|null;bookingReference?:string|null;consentMarketing?:boolean;consentNote?:string|null;status?:ReviewStatus;responseRequired?:boolean;responseNotes?:string|null;receivedAt?:string|null;createdById:string;createdByName:string}){const now=new Date().toISOString(),id=randomUUID();const r=rating(input.rating);const item:MarketingReview={id,customerName:input.customerName.trim(),source:input.source,rating:r,reviewText:input.reviewText?.trim()||null,reviewUrl:input.reviewUrl?.trim()||null,destination:input.destination?.trim()||null,bookingReference:input.bookingReference?.trim()||null,consentMarketing:Boolean(input.consentMarketing),consentNote:input.consentNote?.trim()||null,status:input.status||'NEW',responseRequired:input.responseRequired??r<=3,responseNotes:input.responseNotes?.trim()||null,testimonialAssetId:null,receivedAt:input.receivedAt||now,createdAt:now,updatedAt:now,createdById:input.createdById,updatedByName:input.createdByName};await db.appSetting.create({data:{key:`${PREFIX}${id}`,category:CATEGORY,value:item as any,updatedBy:input.createdById}});return item;}
export async function updateMarketingReview(id:string,patch:Partial<Pick<MarketingReview,'customerName'|'source'|'rating'|'reviewText'|'reviewUrl'|'destination'|'bookingReference'|'consentMarketing'|'consentNote'|'status'|'responseRequired'|'responseNotes'|'testimonialAssetId'|'receivedAt'>>,{userId,userName}:{userId:string;userName:string}){const key=`${PREFIX}${id}`;const row=await db.appSetting.findUnique({where:{key}});const current=parse(row?.value);if(!current)throw new Error('marketing_review_not_found');const next:any={...current,...patch,updatedAt:new Date().toISOString(),updatedByName:userName};if(patch.rating!==undefined)next.rating=rating(patch.rating);if(patch.consentMarketing===false)next.testimonialAssetId=null;await db.appSetting.update({where:{key},data:{value:next as any,updatedBy:userId}});return next as MarketingReview;}
export function reviewGovernance(review:MarketingReview){const canUseAsTestimonial=review.rating>=4&&review.consentMarketing&&Boolean(review.reviewText?.trim());return {canUseAsTestimonial,needsResponse:review.responseRequired&&review.status!=='RESOLVED'&&review.status!=='ARCHIVED',positive:review.rating>=4,negative:review.rating<=3};}
