import {randomUUID} from 'node:crypto';
import {db} from '@/lib/db';

export const LOYALTY_TIERS=['NEW','ACTIVE','LOYAL','VIP','REACTIVATE'] as const;
export const LOYALTY_STATUSES=['OPEN','FOLLOW_UP','OFFER_PROPOSED','CONTACTED','COMPLETED','PAUSED'] as const;
export type LoyaltyTier=(typeof LOYALTY_TIERS)[number];
export type LoyaltyStatus=(typeof LOYALTY_STATUSES)[number];
export type MarketingLoyalty={id:string;customerName:string;phone?:string|null;email?:string|null;tier:LoyaltyTier;status:LoyaltyStatus;purchaseCount:number;lastPurchaseAt?:string|null;valueByCurrency:Array<{currency:string;amount:number}>;preferredDestinations:string[];benefit?:string|null;nextAction?:string|null;nextActionAt?:string|null;relationshipSince?:string|null;notes?:string|null;createdAt:string;updatedAt:string;createdById:string;updatedByName:string};
const CATEGORY='Marketing Loyalty',PREFIX='marketing.loyalty.';
function parse(v:unknown):MarketingLoyalty|null{if(!v||typeof v!=='object')return null;const x=v as MarketingLoyalty;return x.id&&x.customerName&&LOYALTY_TIERS.includes(x.tier)&&LOYALTY_STATUSES.includes(x.status)&&Array.isArray(x.valueByCurrency)&&Array.isArray(x.preferredDestinations)?x:null;}
function safeNum(v:unknown){const n=Number(v);return Number.isFinite(n)&&n>=0?n:0;}
function normalizeValues(v:unknown){if(!Array.isArray(v))return [];const out=new Map<string,number>();for(const row of v){if(!row||typeof row!=='object')continue;const currency=String((row as any).currency||'').trim().toUpperCase();if(!currency)continue;out.set(currency,(out.get(currency)||0)+safeNum((row as any).amount));}return [...out.entries()].map(([currency,amount])=>({currency,amount}));}
export async function listMarketingLoyalty(){const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PREFIX}},orderBy:{updatedAt:'desc'}});return rows.map(r=>parse(r.value)).filter((x):x is MarketingLoyalty=>x!==null);}
export async function createMarketingLoyalty(input:{customerName:string;phone?:string|null;email?:string|null;tier?:LoyaltyTier;status?:LoyaltyStatus;purchaseCount?:number;lastPurchaseAt?:string|null;valueByCurrency?:Array<{currency:string;amount:number}>;preferredDestinations?:string[];benefit?:string|null;nextAction?:string|null;nextActionAt?:string|null;relationshipSince?:string|null;notes?:string|null;createdById:string;createdByName:string}){const now=new Date().toISOString(),id=randomUUID();const item:MarketingLoyalty={id,customerName:input.customerName.trim(),phone:input.phone?.trim()||null,email:input.email?.trim().toLowerCase()||null,tier:input.tier||'NEW',status:input.status||'OPEN',purchaseCount:Math.floor(safeNum(input.purchaseCount)),lastPurchaseAt:input.lastPurchaseAt||null,valueByCurrency:normalizeValues(input.valueByCurrency),preferredDestinations:(input.preferredDestinations||[]).map(x=>x.trim()).filter(Boolean).slice(0,12),benefit:input.benefit?.trim()||null,nextAction:input.nextAction?.trim()||null,nextActionAt:input.nextActionAt||null,relationshipSince:input.relationshipSince||null,notes:input.notes?.trim()||null,createdAt:now,updatedAt:now,createdById:input.createdById,updatedByName:input.createdByName};await db.appSetting.create({data:{key:`${PREFIX}${id}`,category:CATEGORY,value:item as any,updatedBy:input.createdById}});return item;}
export async function updateMarketingLoyalty(id:string,patch:Partial<Pick<MarketingLoyalty,'customerName'|'phone'|'email'|'tier'|'status'|'purchaseCount'|'lastPurchaseAt'|'valueByCurrency'|'preferredDestinations'|'benefit'|'nextAction'|'nextActionAt'|'relationshipSince'|'notes'>>,{userId,userName}:{userId:string;userName:string}){const key=`${PREFIX}${id}`;const row=await db.appSetting.findUnique({where:{key}});const current=parse(row?.value);if(!current)throw new Error('marketing_loyalty_not_found');const next:any={...current,...patch,updatedAt:new Date().toISOString(),updatedByName:userName};if(patch.purchaseCount!==undefined)next.purchaseCount=Math.floor(safeNum(patch.purchaseCount));if(patch.valueByCurrency!==undefined)next.valueByCurrency=normalizeValues(patch.valueByCurrency);if(patch.preferredDestinations!==undefined)next.preferredDestinations=patch.preferredDestinations.map(x=>x.trim()).filter(Boolean).slice(0,12);if(patch.email!==undefined)next.email=patch.email?.trim().toLowerCase()||null;await db.appSetting.update({where:{key},data:{value:next as any,updatedBy:userId}});return next as MarketingLoyalty;}
export function loyaltyMetrics(items:MarketingLoyalty[]){const due=items.filter(x=>x.nextActionAt&&new Date(x.nextActionAt).getTime()<=Date.now()&&!['COMPLETED','PAUSED'].includes(x.status));const vip=items.filter(x=>x.tier==='VIP');const reactivate=items.filter(x=>x.tier==='REACTIVATE');const values=new Map<string,number>();for(const item of items)for(const v of item.valueByCurrency)values.set(v.currency,(values.get(v.currency)||0)+v.amount);return {total:items.length,vip:vip.length,reactivate:reactivate.length,due:due.length,valueByCurrency:[...values.entries()].map(([currency,amount])=>({currency,amount}))};}
