import {randomUUID} from 'node:crypto';
import {db} from '@/lib/db';
import {marketingAssignees} from '@/lib/workspace/marketing';

export const SEASON_TYPES=['HOLIDAY','SCHOOL_BREAK','SUMMER','WINTER','EVENT','DESTINATION','ROUTE_PROMO','OTHER'] as const;
export const SEASON_STATUSES=['IDEA','PLANNING','PREPARING','READY','ACTIVE','COMPLETED','CANCELLED'] as const;
export type SeasonType=(typeof SEASON_TYPES)[number];
export type SeasonStatus=(typeof SEASON_STATUSES)[number];
export type SeasonChecklist={offerReady:boolean;contentReady:boolean;assetsApproved:boolean;adsReady:boolean;landingReady:boolean;trackingReady:boolean};
export type MarketingSeason={id:string;title:string;type:SeasonType;status:SeasonStatus;market?:string|null;destination?:string|null;theme?:string|null;startAt:string;endAt?:string|null;prepStartAt:string;ownerId?:string|null;ownerName?:string|null;notes?:string|null;checklist:SeasonChecklist;createdAt:string;updatedAt:string;createdById:string;updatedByName:string};
const CATEGORY='Marketing Seasonality',PREFIX='marketing.season.';
const EMPTY:SeasonChecklist={offerReady:false,contentReady:false,assetsApproved:false,adsReady:false,landingReady:false,trackingReady:false};
function parse(v:unknown):MarketingSeason|null{if(!v||typeof v!=='object')return null;const x=v as MarketingSeason;return x.id&&x.title&&x.startAt&&x.prepStartAt&&x.checklist?x:null;}
function prepDate(startAt:string){const d=new Date(startAt);d.setUTCDate(d.getUTCDate()-60);return d.toISOString();}
async function ownerName(id?:string|null){if(!id)return null;const u=await db.portalUser.findUnique({where:{id},select:{fullName:true,username:true}});return u?.fullName||u?.username||null;}
export function seasonReadiness(x:MarketingSeason){const values=Object.values(x.checklist);const done=values.filter(Boolean).length;return {done,total:values.length,percent:Math.round((done/values.length)*100)};}
export async function listMarketingSeasons(){const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PREFIX}},orderBy:{updatedAt:'desc'}});return rows.map(r=>parse(r.value)).filter((x):x is MarketingSeason=>x!==null);}
export async function createMarketingSeason(input:{title:string;type:SeasonType;status?:SeasonStatus;market?:string|null;destination?:string|null;theme?:string|null;startAt:string;endAt?:string|null;ownerId?:string|null;notes?:string|null;createdById:string;createdByName:string}){const now=new Date().toISOString(),id=randomUUID();const item:MarketingSeason={id,title:input.title.trim(),type:input.type,status:input.status||'IDEA',market:input.market?.trim()||null,destination:input.destination?.trim()||null,theme:input.theme?.trim()||null,startAt:new Date(input.startAt).toISOString(),endAt:input.endAt?new Date(input.endAt).toISOString():null,prepStartAt:prepDate(input.startAt),ownerId:input.ownerId||null,ownerName:await ownerName(input.ownerId),notes:input.notes?.trim()||null,checklist:{...EMPTY},createdAt:now,updatedAt:now,createdById:input.createdById,updatedByName:input.createdByName};await db.appSetting.create({data:{key:`${PREFIX}${id}`,category:CATEGORY,value:item as any,updatedBy:input.createdById}});return item;}
export async function updateMarketingSeason(id:string,patch:Partial<Pick<MarketingSeason,'title'|'type'|'status'|'market'|'destination'|'theme'|'startAt'|'endAt'|'ownerId'|'notes'|'checklist'>>,{userId,userName}:{userId:string;userName:string}){const key=`${PREFIX}${id}`;const row=await db.appSetting.findUnique({where:{key}});const current=parse(row?.value);if(!current)throw new Error('marketing_season_not_found');const next:any={...current,...patch,updatedAt:new Date().toISOString(),updatedByName:userName};if(patch.startAt!==undefined){next.startAt=new Date(patch.startAt).toISOString();next.prepStartAt=prepDate(next.startAt);}if(patch.endAt!==undefined)next.endAt=patch.endAt?new Date(patch.endAt).toISOString():null;if(patch.ownerId!==undefined)next.ownerName=await ownerName(patch.ownerId);if(patch.checklist)next.checklist={...current.checklist,...patch.checklist};await db.appSetting.update({where:{key},data:{value:next as any,updatedBy:userId}});return next as MarketingSeason;}
export async function marketingSeasonMeta(){return {users:await marketingAssignees()};}
