import {randomUUID} from 'node:crypto';
import {db} from '@/lib/db';
import {listMarketingStudio} from '@/lib/workspace/marketing-studio';

export const ASSET_CATEGORIES=['LOGO','BRAND_GUIDE','TEMPLATE','VISUAL','VIDEO','FLYER','OFFER','TESTIMONIAL','DESTINATION','PHOTO','DOCUMENT','OTHER'] as const;
export const ASSET_STATUSES=['DRAFT','REVIEW','APPROVED','RESTRICTED','ARCHIVED'] as const;
export const ASSET_USAGE=['INTERNAL','ORGANIC','ADS','PARTNERS','ALL'] as const;
export type AssetCategory=(typeof ASSET_CATEGORIES)[number];
export type AssetStatus=(typeof ASSET_STATUSES)[number];
export type AssetUsage=(typeof ASSET_USAGE)[number];
export type MarketingAsset={id:string;title:string;category:AssetCategory;status:AssetStatus;usage:AssetUsage;url:string;destination?:string|null;tags:string[];rightsNote?:string|null;expiresAt?:string|null;studioId?:string|null;studioTitle?:string|null;notes?:string|null;createdAt:string;updatedAt:string;createdById:string;updatedByName:string};
const CATEGORY='Marketing Assets',PREFIX='marketing.asset.';
function parse(v:unknown):MarketingAsset|null{if(!v||typeof v!=='object')return null;const x=v as MarketingAsset;return x.id&&x.title&&x.url&&ASSET_CATEGORIES.includes(x.category)&&ASSET_STATUSES.includes(x.status)&&ASSET_USAGE.includes(x.usage)&&Array.isArray(x.tags)?x:null;}
export async function listMarketingAssets(){const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PREFIX}},orderBy:{updatedAt:'desc'}});return rows.map(r=>parse(r.value)).filter((x):x is MarketingAsset=>x!==null);}
export async function createMarketingAsset(input:{title:string;category:AssetCategory;status?:AssetStatus;usage?:AssetUsage;url:string;destination?:string|null;tags?:string[];rightsNote?:string|null;expiresAt?:string|null;studioId?:string|null;notes?:string|null;createdById:string;createdByName:string}){const now=new Date().toISOString(),id=randomUUID();const studio=input.studioId?(await listMarketingStudio()).find(x=>x.id===input.studioId):null;const asset:MarketingAsset={id,title:input.title.trim(),category:input.category,status:input.status||'DRAFT',usage:input.usage||'INTERNAL',url:input.url.trim(),destination:input.destination?.trim()||null,tags:(input.tags||[]).map(x=>x.trim()).filter(Boolean).slice(0,20),rightsNote:input.rightsNote?.trim()||null,expiresAt:input.expiresAt||null,studioId:studio?.id||null,studioTitle:studio?.title||null,notes:input.notes?.trim()||null,createdAt:now,updatedAt:now,createdById:input.createdById,updatedByName:input.createdByName};await db.appSetting.create({data:{key:`${PREFIX}${id}`,category:CATEGORY,value:asset as any,updatedBy:input.createdById}});return asset;}
export async function updateMarketingAsset(id:string,patch:Partial<Pick<MarketingAsset,'title'|'category'|'status'|'usage'|'url'|'destination'|'tags'|'rightsNote'|'expiresAt'|'studioId'|'notes'>>,{userId,userName}:{userId:string;userName:string}){const key=`${PREFIX}${id}`;const row=await db.appSetting.findUnique({where:{key}});const current=parse(row?.value);if(!current)throw new Error('marketing_asset_not_found');const next:any={...current,...patch,updatedAt:new Date().toISOString(),updatedByName:userName};if(patch.tags)next.tags=patch.tags.map(x=>x.trim()).filter(Boolean).slice(0,20);if(patch.studioId!==undefined){const studio=patch.studioId?(await listMarketingStudio()).find(x=>x.id===patch.studioId):null;next.studioId=studio?.id||null;next.studioTitle=studio?.title||null;}await db.appSetting.update({where:{key},data:{value:next as any,updatedBy:userId}});return next as MarketingAsset;}
export async function marketingAssetMeta(){return {studio:await listMarketingStudio()};}
