import {randomUUID} from 'node:crypto';
import {db} from '@/lib/db';

export const REFERRAL_STATUSES=['LEAD','QUALIFIED','BOOKED','PAID','REWARDED','CANCELLED'] as const;
export const REWARD_STATUSES=['NONE','PENDING','APPROVED','DELIVERED','REJECTED'] as const;
export type ReferralStatus=(typeof REFERRAL_STATUSES)[number];
export type RewardStatus=(typeof REWARD_STATUSES)[number];
export type MarketingReferral={id:string;referrerName:string;referrerPhone?:string|null;referralCode:string;referredName:string;referredPhone?:string|null;destination?:string|null;status:ReferralStatus;saleReference?:string|null;saleAmount?:number|null;saleCurrency?:string|null;rewardType?:string|null;rewardValue?:number|null;rewardCurrency?:string|null;rewardStatus:RewardStatus;notes?:string|null;createdAt:string;updatedAt:string;createdById:string;updatedByName:string};
const CATEGORY='Marketing Referrals',PREFIX='marketing.referral.';
function parse(v:unknown):MarketingReferral|null{if(!v||typeof v!=='object')return null;const x=v as MarketingReferral;return x.id&&x.referrerName&&x.referredName&&x.referralCode&&REFERRAL_STATUSES.includes(x.status)&&REWARD_STATUSES.includes(x.rewardStatus)?x:null;}
function num(v:unknown){const n=Number(v);return Number.isFinite(n)&&n>=0?n:null;}
function code(){return `DONI-${Math.random().toString(36).slice(2,8).toUpperCase()}`;}
export async function listMarketingReferrals(){const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PREFIX}},orderBy:{updatedAt:'desc'}});return rows.map(r=>parse(r.value)).filter((x):x is MarketingReferral=>x!==null);}
export async function createMarketingReferral(input:{referrerName:string;referrerPhone?:string|null;referralCode?:string|null;referredName:string;referredPhone?:string|null;destination?:string|null;status?:ReferralStatus;saleReference?:string|null;saleAmount?:number|null;saleCurrency?:string|null;rewardType?:string|null;rewardValue?:number|null;rewardCurrency?:string|null;notes?:string|null;createdById:string;createdByName:string}){const now=new Date().toISOString(),id=randomUUID();const item:MarketingReferral={id,referrerName:input.referrerName.trim(),referrerPhone:input.referrerPhone?.trim()||null,referralCode:input.referralCode?.trim().toUpperCase()||code(),referredName:input.referredName.trim(),referredPhone:input.referredPhone?.trim()||null,destination:input.destination?.trim()||null,status:input.status||'LEAD',saleReference:input.saleReference?.trim()||null,saleAmount:num(input.saleAmount),saleCurrency:input.saleCurrency?.trim().toUpperCase()||null,rewardType:input.rewardType?.trim()||null,rewardValue:num(input.rewardValue),rewardCurrency:input.rewardCurrency?.trim().toUpperCase()||null,rewardStatus:'NONE',notes:input.notes?.trim()||null,createdAt:now,updatedAt:now,createdById:input.createdById,updatedByName:input.createdByName};await db.appSetting.create({data:{key:`${PREFIX}${id}`,category:CATEGORY,value:item as any,updatedBy:input.createdById}});return item;}
export async function updateMarketingReferral(id:string,patch:Partial<Pick<MarketingReferral,'referrerName'|'referrerPhone'|'referredName'|'referredPhone'|'destination'|'status'|'saleReference'|'saleAmount'|'saleCurrency'|'rewardType'|'rewardValue'|'rewardCurrency'|'rewardStatus'|'notes'>>,{userId,userName}:{userId:string;userName:string}){const key=`${PREFIX}${id}`;const row=await db.appSetting.findUnique({where:{key}});const current=parse(row?.value);if(!current)throw new Error('marketing_referral_not_found');const next:any={...current,...patch,updatedAt:new Date().toISOString(),updatedByName:userName};if(patch.saleAmount!==undefined)next.saleAmount=num(patch.saleAmount);if(patch.rewardValue!==undefined)next.rewardValue=num(patch.rewardValue);if(patch.saleCurrency!==undefined)next.saleCurrency=patch.saleCurrency?.trim().toUpperCase()||null;if(patch.rewardCurrency!==undefined)next.rewardCurrency=patch.rewardCurrency?.trim().toUpperCase()||null;await db.appSetting.update({where:{key},data:{value:next as any,updatedBy:userId}});return next as MarketingReferral;}
export function referralMetrics(items:MarketingReferral[]){const paid=items.filter(x=>['PAID','REWARDED'].includes(x.status));const rewarded=items.filter(x=>x.rewardStatus==='DELIVERED');const pendingRewards=items.filter(x=>x.rewardStatus==='PENDING'||x.rewardStatus==='APPROVED');const byCurrency=new Map<string,{sales:number;revenue:number}>();for(const x of paid){if(!x.saleCurrency||x.saleAmount==null)continue;const c=byCurrency.get(x.saleCurrency)||{sales:0,revenue:0};c.sales++;c.revenue+=x.saleAmount;byCurrency.set(x.saleCurrency,c);}return {total:items.length,paid:paid.length,rewarded:rewarded.length,pendingRewards:pendingRewards.length,byCurrency:[...byCurrency.entries()].map(([currency,v])=>({currency,...v}))};}
