import {db} from '@/lib/db';

const CATEGORY='DONI Marketing Publisher Policy';
const KEY='marketing.publisher.policy';
const EVENT_CATEGORY='DONI Marketing Publisher Events';
const EVENT_PREFIX='marketing.publisher.';

export type PublisherPolicy={globalPause:boolean;maxPerRun:number;maxPerHour:number;maxPerRecipient24h:number;quietHoursEnabled:boolean;quietStartHour:number;quietEndHour:number;timezone:string};
export type PolicyDecision={allowed:boolean;reason?:string;retryAfter?:string|null};

const DEFAULT_POLICY:PublisherPolicy={globalPause:false,maxPerRun:20,maxPerHour:120,maxPerRecipient24h:2,quietHoursEnabled:false,quietStartHour:21,quietEndHour:8,timezone:'America/Mexico_City'};
function clamp(n:number,min:number,max:number){return Math.max(min,Math.min(max,Math.round(n)));}
function normalize(v:any):PublisherPolicy{return{globalPause:!!v?.globalPause,maxPerRun:clamp(Number(v?.maxPerRun??DEFAULT_POLICY.maxPerRun),1,50),maxPerHour:clamp(Number(v?.maxPerHour??DEFAULT_POLICY.maxPerHour),1,5000),maxPerRecipient24h:clamp(Number(v?.maxPerRecipient24h??DEFAULT_POLICY.maxPerRecipient24h),1,20),quietHoursEnabled:!!v?.quietHoursEnabled,quietStartHour:clamp(Number(v?.quietStartHour??DEFAULT_POLICY.quietStartHour),0,23),quietEndHour:clamp(Number(v?.quietEndHour??DEFAULT_POLICY.quietEndHour),0,23),timezone:String(v?.timezone||DEFAULT_POLICY.timezone)}};
export async function getPublisherPolicy(){const row=await db.appSetting.findUnique({where:{key:KEY}}).catch(()=>null);return normalize(row?.value);}
export async function savePublisherPolicy(input:Partial<PublisherPolicy>,updatedBy?:string){const current=await getPublisherPolicy();const value=normalize({...current,...input});await db.appSetting.upsert({where:{key:KEY},create:{key:KEY,category:CATEGORY,value:value as any,updatedBy},update:{category:CATEGORY,value:value as any,updatedBy}});return value;}

async function sentEvents(){const rows=await db.appSetting.findMany({where:{category:EVENT_CATEGORY,key:{startsWith:EVENT_PREFIX}},orderBy:{createdAt:'desc'},take:1000});return rows.map(r=>r.value as any).filter(v=>v?.status==='SENT'&&v?.at);}
function nextQuietEnd(policy:PublisherPolicy,now:Date){const parts=new Intl.DateTimeFormat('en-US',{timeZone:policy.timezone,hour:'2-digit',hourCycle:'h23',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now);const hour=Number(parts.find(p=>p.type==='hour')?.value||0);const inQuiet=policy.quietStartHour===policy.quietEndHour?false:policy.quietStartHour<policy.quietEndHour?hour>=policy.quietStartHour&&hour<policy.quietEndHour:hour>=policy.quietStartHour||hour<policy.quietEndHour;if(!inQuiet)return null;const delayHours=policy.quietStartHour<policy.quietEndHour?policy.quietEndHour-hour:(hour>=policy.quietStartHour?24-hour+policy.quietEndHour:policy.quietEndHour-hour);return new Date(now.getTime()+Math.max(1,delayHours)*3600000).toISOString();}
export async function evaluatePublisherPolicy(to?:string|null):Promise<PolicyDecision>{const policy=await getPublisherPolicy();const now=new Date();if(policy.globalPause)return{allowed:false,reason:'global_pause',retryAfter:null};if(policy.quietHoursEnabled){const q=nextQuietEnd(policy,now);if(q)return{allowed:false,reason:'quiet_hours',retryAfter:q};}const events=await sentEvents();const hourAgo=now.getTime()-3600000;const sentHour=events.filter(e=>new Date(e.at).getTime()>=hourAgo);if(sentHour.length>=policy.maxPerHour){const oldest=sentHour.map(e=>new Date(e.at).getTime()).sort((a,b)=>a-b)[0];return{allowed:false,reason:'hourly_limit',retryAfter:new Date(oldest+3600000+1000).toISOString()};}if(to){const dayAgo=now.getTime()-86400000;const recipient=events.filter(e=>e.to===to&&new Date(e.at).getTime()>=dayAgo);if(recipient.length>=policy.maxPerRecipient24h){const oldest=recipient.map(e=>new Date(e.at).getTime()).sort((a,b)=>a-b)[0];return{allowed:false,reason:'recipient_24h_limit',retryAfter:new Date(oldest+86400000+1000).toISOString()};}}return{allowed:true};}
