import {randomUUID} from 'node:crypto';
import {db} from '@/lib/db';
import {marketingAssignees,listMarketingContent} from '@/lib/workspace/marketing';
import {listMarketingCampaigns} from '@/lib/workspace/marketing-campaigns';

export const STUDIO_STATUSES=['IDEA','BRIEF','IN_PRODUCTION','REVIEW','CHANGES_REQUESTED','APPROVED','ARCHIVED'] as const;
export const STUDIO_TYPES=['VISUAL','VIDEO','FLYER','STORY','REEL','COPY','TESTIMONIAL','OTHER'] as const;
export type StudioStatus=(typeof STUDIO_STATUSES)[number];
export type StudioType=(typeof STUDIO_TYPES)[number];
export type MarketingStudioItem={id:string;title:string;type:StudioType;status:StudioStatus;brief?:string|null;assetUrl?:string|null;campaignId?:string|null;campaignName?:string|null;contentId?:string|null;contentTitle?:string|null;ownerId?:string|null;ownerName?:string|null;reviewerId?:string|null;reviewerName?:string|null;reviewNote?:string|null;dueAt?:string|null;approvedAt?:string|null;approvedBy?:string|null;createdAt:string;updatedAt:string;createdById:string;history:Array<{at:string;by:string;action:string;note?:string|null}>};
const CATEGORY='Marketing Studio',PREFIX='marketing.studio.';
function isItem(v:unknown):v is MarketingStudioItem{if(!v||typeof v!=='object')return false;const x=v as MarketingStudioItem;return Boolean(x.id&&x.title&&STUDIO_STATUSES.includes(x.status)&&STUDIO_TYPES.includes(x.type)&&Array.isArray(x.history));}
async function resolveUserName(id?:string|null){if(!id)return null;const u=await db.portalUser.findUnique({where:{id},select:{fullName:true,username:true}});return u?.fullName||u?.username||null;}
export async function listMarketingStudio(){const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PREFIX}},orderBy:{updatedAt:'desc'}});return rows.map(r=>r.value).filter(isItem);}
export async function createMarketingStudioItem(input:{title:string;type:StudioType;brief?:string|null;assetUrl?:string|null;campaignId?:string|null;contentId?:string|null;ownerId?:string|null;reviewerId?:string|null;dueAt?:string|null;createdById:string;createdByName:string}){const now=new Date().toISOString(),id=randomUUID();const campaigns=await listMarketingCampaigns(),contents=await listMarketingContent();const campaign=campaigns.find(x=>x.id===input.campaignId),content=contents.find(x=>x.id===input.contentId);const item:MarketingStudioItem={id,title:input.title.trim(),type:input.type,status:'BRIEF',brief:input.brief?.trim()||null,assetUrl:input.assetUrl?.trim()||null,campaignId:campaign?.id||null,campaignName:campaign?.name||null,contentId:content?.id||null,contentTitle:content?.title||null,ownerId:input.ownerId||null,ownerName:await resolveUserName(input.ownerId),reviewerId:input.reviewerId||null,reviewerName:await resolveUserName(input.reviewerId),reviewNote:null,dueAt:input.dueAt||null,approvedAt:null,approvedBy:null,createdAt:now,updatedAt:now,createdById:input.createdById,history:[{at:now,by:input.createdByName,action:'CREATED'}]};await db.appSetting.create({data:{key:`${PREFIX}${id}`,category:CATEGORY,value:item as any,updatedBy:input.createdById}});return item;}
export async function updateMarketingStudioItem(id:string,patch:Partial<Pick<MarketingStudioItem,'title'|'type'|'status'|'brief'|'assetUrl'|'campaignId'|'contentId'|'ownerId'|'reviewerId'|'reviewNote'|'dueAt'>>,{userId,userName}:{userId:string;userName:string}){const key=`${PREFIX}${id}`;const row=await db.appSetting.findUnique({where:{key}});if(!isItem(row?.value))throw new Error('studio_item_not_found');const current=row.value as MarketingStudioItem;const next:any={...current,...patch,updatedAt:new Date().toISOString()};if(patch.ownerId!==undefined)next.ownerName=await resolveUserName(patch.ownerId);if(patch.reviewerId!==undefined)next.reviewerName=await resolveUserName(patch.reviewerId);if(patch.campaignId!==undefined){const c=(await listMarketingCampaigns()).find(x=>x.id===patch.campaignId);next.campaignId=c?.id||null;next.campaignName=c?.name||null;}if(patch.contentId!==undefined){const c=(await listMarketingContent()).find(x=>x.id===patch.contentId);next.contentId=c?.id||null;next.contentTitle=c?.title||null;}if(patch.status==='APPROVED'){next.approvedAt=new Date().toISOString();next.approvedBy=userName;}else if(patch.status){next.approvedAt=null;next.approvedBy=null;}next.history=[...(current.history||[]),{at:new Date().toISOString(),by:userName,action:patch.status?`STATUS_${patch.status}`:'UPDATED',note:patch.reviewNote||null}].slice(-80);await db.appSetting.update({where:{key},data:{value:next,updatedBy:userId}});return next as MarketingStudioItem;}
export async function marketingStudioMeta(){const [users,campaigns,content]=await Promise.all([marketingAssignees(),listMarketingCampaigns(),listMarketingContent()]);return {users,campaigns,content};}
