import {db} from '@/lib/db';
import {getMarketingDeliveryDashboard} from '@/lib/workspace/marketing-delivery-tracking';
import {listWinningLearnings} from '@/lib/workspace/marketing-winning-learnings';

const AUTOPILOT_CATEGORY='DONI Marketing Autopilot';
const AUTOPILOT_PREFIX='marketing.autopilot.';
const CONVERSION_WINDOW_MS=7*24*60*60*1000;

type CampaignMeta={id:string;title:string;objective?:string;source?:string;route?:string|null;destination?:string|null;channelSuggestion?:string};
function campaign(v:unknown):CampaignMeta|null{if(!v||typeof v!=='object')return null;const x=v as any;return x.id?{id:String(x.id),title:String(x.title||'Campagne DONI'),objective:String(x.objective||''),source:String(x.source||''),route:x.route||null,destination:x.destination||null,channelSuggestion:String(x.channelSuggestion||'')}:null;}
function pct(n:number,d:number){return d?Math.round(n/d*1000)/10:0;}
function level(score:number){return score>=75?'EXCELLENT':score>=55?'GOOD':score>=35?'WATCH':'WEAK';}

export async function getMarketingLearningLoop(){
 const [delivery,validatedLearnings]=await Promise.all([getMarketingDeliveryDashboard(),listWinningLearnings(50)]);
 const metaRows=await db.appSetting.findMany({where:{category:AUTOPILOT_CATEGORY,key:{startsWith:AUTOPILOT_PREFIX}},select:{value:true}});
 const meta=new Map(metaRows.map(r=>campaign(r.value)).filter((x):x is CampaignMeta=>Boolean(x)).map(x=>[x.id,x]));
 const conversationIds=[...new Set(delivery.records.map((r:any)=>r.conversationId).filter((x:any):x is string=>Boolean(x)))];
 const earliest=delivery.records.length?new Date(Math.min(...delivery.records.map((r:any)=>new Date(r.sentAt).getTime()))):new Date();
 const payments=conversationIds.length?await db.payment.findMany({where:{conversationId:{in:conversationIds},status:'PAID',updatedAt:{gte:earliest}},select:{conversationId:true,amount:true,currency:true,updatedAt:true}}):[];
 const byConversation=new Map<string,typeof payments>();for(const p of payments){if(!p.conversationId)continue;const list=byConversation.get(p.conversationId)||[];list.push(p);byConversation.set(p.conversationId,list);}
 const grouped=new Map<string,any>();
 for(const r of delivery.records as any[]){const g=grouped.get(r.itemId)||{itemId:r.itemId,sent:0,delivered:0,read:0,replied:0,failed:0,converted:0,revenueByCurrency:{} as Record<string,number>,lastSentAt:r.sentAt};g.sent++;if(r.deliveredAt||r.readAt)g.delivered++;if(r.readAt)g.read++;if(r.repliedAt)g.replied++;if(r.failedAt)g.failed++;if(new Date(r.sentAt)>new Date(g.lastSentAt))g.lastSentAt=r.sentAt;if(r.conversationId){const start=new Date(r.sentAt).getTime(),end=start+CONVERSION_WINDOW_MS;const matched=(byConversation.get(r.conversationId)||[]).filter(p=>{const t=p.updatedAt.getTime();return t>=start&&t<=end;});if(matched.length){g.converted++;for(const p of matched){const c=String(p.currency);g.revenueByCurrency[c]=(g.revenueByCurrency[c]||0)+Number(p.amount);}}}grouped.set(r.itemId,g);}
 const campaigns=[...grouped.values()].map(g=>{const m=meta.get(g.itemId);const deliveredRate=pct(g.delivered,g.sent),readRate=pct(g.read,g.sent),replyRate=pct(g.replied,g.sent),conversionRate=pct(g.converted,g.sent),failureRate=pct(g.failed,g.sent);const score=Math.max(0,Math.min(100,Math.round(deliveredRate*.1+readRate*.25+replyRate*.25+conversionRate*.4-failureRate*.25)));const recommendations:string[]=[];if(failureRate>5)recommendations.push('Vérifier la qualité des numéros et les erreurs Meta avant de réutiliser cette audience.');if(deliveredRate<85&&g.sent>=5)recommendations.push('Améliorer la délivrabilité avant d’augmenter le volume.');if(readRate<50&&g.delivered>=5)recommendations.push('Tester une accroche plus courte et un meilleur moment d’envoi.');if(replyRate<10&&g.read>=5)recommendations.push('Renforcer l’appel à l’action et la personnalisation du message.');if(conversionRate<5&&g.replied>=3)recommendations.push('Revoir l’offre, le prix ou le parcours après réponse.');if(conversionRate>=15)recommendations.push('Conserver cette structure comme référence et tester une variante contrôlée.');if(!recommendations.length)recommendations.push('Échantillon encore limité : continuer à collecter des données avant décision forte.');return{...g,title:m?.title||g.itemId,objective:m?.objective||'',source:m?.source||'',route:m?.route||null,destination:m?.destination||null,deliveredRate,readRate,replyRate,conversionRate,failureRate,score,level:level(score),recommendations};}).sort((a,b)=>b.score-a.score);
 const mature=campaigns.filter(x=>x.sent>=5);const winners=mature.filter(x=>x.score>=55).slice(0,5);const needsWork=mature.filter(x=>x.score<55).sort((a,b)=>a.score-b.score).slice(0,5);
 const globalRecommendations:string[]=[];if(validatedLearnings.length)globalRecommendations.push(`${validatedLearnings.length} apprentissage${validatedLearnings.length>1?'s':''} A/B validé${validatedLearnings.length>1?'s':''} disponible${validatedLearnings.length>1?'s':''} comme référence pour les prochains brouillons.`);if(delivery.rates.readRate<50&&delivery.counts.SENT>=10)globalRecommendations.push('Priorité : améliorer l’ouverture/lecture des messages avant d’augmenter la fréquence.');if(delivery.rates.replyRate<10&&delivery.counts.READ>=10)globalRecommendations.push('Priorité : tester de nouveaux CTA sur les audiences qui lisent mais ne répondent pas.');if(delivery.rates.conversionRate<5&&delivery.counts.REPLIED>=5)globalRecommendations.push('Priorité : optimiser le passage réponse → paiement.');if(delivery.counts.FAILED>0)globalRecommendations.push('Surveiller les échecs Meta et nettoyer les destinataires invalides.');if(!globalRecommendations.length)globalRecommendations.push('Pas encore assez de signal négatif pour modifier automatiquement la stratégie. Continuer les tests contrôlés.');
 return{summary:{campaigns:campaigns.length,mature:mature.length,winners:winners.length,needsWork:needsWork.length,validatedLearnings:validatedLearnings.length,globalScore:mature.length?Math.round(mature.reduce((s,x)=>s+x.score,0)/mature.length):0},campaigns,winners,needsWork,validatedLearnings,globalRecommendations,deliveryRates:delivery.rates,generatedAt:new Date().toISOString(),mode:'ADVISORY_ONLY' as const};
}
