import {randomUUID} from 'node:crypto';
import {db} from '@/lib/db';
import {marketingAssignees} from '@/lib/workspace/marketing';

export const CAMPAIGN_CHANNELS=['META_ADS','GOOGLE_ADS','WHATSAPP','ORGANIC','INFLUENCER','FIELD','OTHER'] as const;
export const CAMPAIGN_STATUSES=['DRAFT','PLANNED','ACTIVE','PAUSED','COMPLETED','CANCELLED'] as const;
export const META_ADS_APPROVAL_STATUSES=['DRAFT','WAITING_APPROVAL','APPROVED','REJECTED'] as const;
export type CampaignChannel=(typeof CAMPAIGN_CHANNELS)[number];
export type CampaignStatus=(typeof CAMPAIGN_STATUSES)[number];
export type MetaAdsApprovalStatus=(typeof META_ADS_APPROVAL_STATUSES)[number];
export type MetaAdsDraft={creativeText:string;destinationUrl:string|null;callToAction:string;approvalStatus:MetaAdsApprovalStatus;approvedBy:string|null;approvedAt:string|null;rejectedBy:string|null;rejectedAt:string|null;launchAllowed:boolean;remoteCampaignId:string|null;remoteStatus:string|null};
export type MarketingCampaign={id:string;name:string;channel:CampaignChannel;status:CampaignStatus;objective?:string|null;audience?:string|null;destination?:string|null;startAt?:string|null;endAt?:string|null;budget:number;currency:string;spend:number;leads:number;sales:number;revenue:number;ownerId?:string|null;ownerName?:string|null;notes?:string|null;metaAds?:MetaAdsDraft|null;createdAt:string;updatedAt:string;createdById:string};
export type CampaignMetrics={cpl:number|null;cac:number|null;roas:number|null;roi:number|null;conversion:number|null};
const CATEGORY='Marketing Campaigns',PREFIX='marketing.campaign.';
function isCampaign(v:unknown):v is MarketingCampaign{if(!v||typeof v!=='object')return false;const x=v as MarketingCampaign;return Boolean(x.id&&x.name&&CAMPAIGN_CHANNELS.includes(x.channel)&&CAMPAIGN_STATUSES.includes(x.status));}
async function ownerName(id?:string|null){if(!id)return null;const u=await db.portalUser.findUnique({where:{id},select:{fullName:true,username:true}});return u?.fullName||u?.username||null;}
function num(v:unknown){const n=Number(v);return Number.isFinite(n)&&n>=0?n:0;}
function metaAdsDraft(input:any):MetaAdsDraft{return{creativeText:String(input?.creativeText||'').trim(),destinationUrl:String(input?.destinationUrl||'').trim()||null,callToAction:String(input?.callToAction||'LEARN_MORE').trim().toUpperCase(),approvalStatus:'DRAFT',approvedBy:null,approvedAt:null,rejectedBy:null,rejectedAt:null,launchAllowed:false,remoteCampaignId:null,remoteStatus:null};}
export function campaignMetrics(c:MarketingCampaign):CampaignMetrics{return {cpl:c.leads>0?Math.round((c.spend/c.leads)*100)/100:null,cac:c.sales>0?Math.round((c.spend/c.sales)*100)/100:null,roas:c.spend>0?Math.round((c.revenue/c.spend)*100)/100:null,roi:c.spend>0?Math.round(((c.revenue-c.spend)/c.spend)*1000)/10:null,conversion:c.leads>0?Math.round((c.sales/c.leads)*1000)/10:null};}
export async function listMarketingCampaigns(){const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PREFIX}},orderBy:{updatedAt:'desc'}});return rows.map(r=>r.value).filter(isCampaign);}
export async function createMarketingCampaign(input:{name:string;channel:CampaignChannel;status?:CampaignStatus;objective?:string|null;audience?:string|null;destination?:string|null;startAt?:string|null;endAt?:string|null;budget?:number;currency?:string;spend?:number;leads?:number;sales?:number;revenue?:number;ownerId?:string|null;notes?:string|null;metaAds?:Partial<MetaAdsDraft>|null;createdById:string}){const now=new Date().toISOString(),id=randomUUID();const c:MarketingCampaign={id,name:input.name.trim(),channel:input.channel,status:input.channel==='META_ADS'?'DRAFT':input.status||'DRAFT',objective:input.objective?.trim()||null,audience:input.audience?.trim()||null,destination:input.destination?.trim()||null,startAt:input.startAt||null,endAt:input.endAt||null,budget:num(input.budget),currency:(input.currency||'USD').trim().toUpperCase(),spend:0,leads:Math.floor(num(input.leads)),sales:Math.floor(num(input.sales)),revenue:num(input.revenue),ownerId:input.ownerId||null,ownerName:await ownerName(input.ownerId),notes:input.notes?.trim()||null,metaAds:input.channel==='META_ADS'?metaAdsDraft(input.metaAds):null,createdAt:now,updatedAt:now,createdById:input.createdById};await db.appSetting.create({data:{key:`${PREFIX}${id}`,category:CATEGORY,value:c as any,updatedBy:input.createdById}});return c;}
export async function updateMarketingCampaign(id:string,patch:Partial<Omit<MarketingCampaign,'id'|'createdAt'|'createdById'>>,{userId}:{userId:string}){const key=`${PREFIX}${id}`;const row=await db.appSetting.findUnique({where:{key}});if(!isCampaign(row?.value))throw new Error('campaign_not_found');const current=row.value as MarketingCampaign;if(current.channel==='META_ADS'&&patch.status==='ACTIVE')throw new Error('meta_ads_launch_requires_controlled_publisher');const next:any={...current,...patch,updatedAt:new Date().toISOString()};for(const f of ['budget','spend','leads','sales','revenue'] as const)if((patch as any)[f]!==undefined)next[f]=f==='leads'||f==='sales'?Math.floor(num((patch as any)[f])):num((patch as any)[f]);if(current.channel==='META_ADS')next.spend=current.spend;if(patch.ownerId!==undefined)next.ownerName=await ownerName(patch.ownerId);await db.appSetting.update({where:{key},data:{value:next,updatedBy:userId}});return next as MarketingCampaign;}
async function mutateMetaApproval(id:string,action:'submit'|'approve'|'reject',actor:{id:string;username:string;role:string}){const key=`${PREFIX}${id}`;const row=await db.appSetting.findUnique({where:{key}});if(!isCampaign(row?.value))throw new Error('campaign_not_found');const c=row.value as MarketingCampaign;if(c.channel!=='META_ADS')throw new Error('not_meta_ads');const meta=c.metaAds||metaAdsDraft(null);const now=new Date().toISOString();if(action==='submit'){if(!['DRAFT','REJECTED'].includes(meta.approvalStatus))throw new Error('submit_not_allowed');meta.approvalStatus='WAITING_APPROVAL';meta.approvedBy=null;meta.approvedAt=null;meta.rejectedBy=null;meta.rejectedAt=null;}else{if(actor.role!=='ADMIN'&&actor.role!=='SUPER_ADMIN')throw new Error('admin_required');if(meta.approvalStatus!=='WAITING_APPROVAL')throw new Error('approval_not_allowed');if(action==='approve'){meta.approvalStatus='APPROVED';meta.approvedBy=actor.username;meta.approvedAt=now;meta.rejectedBy=null;meta.rejectedAt=null;}else{meta.approvalStatus='REJECTED';meta.rejectedBy=actor.username;meta.rejectedAt=now;meta.approvedBy=null;meta.approvedAt=null;}}const next={...c,metaAds:meta,status:action==='approve'?'PLANNED':'DRAFT',updatedAt:now};await db.appSetting.update({where:{key},data:{value:next as any,updatedBy:actor.id}});return next;}
export async function submitMetaAdsCampaign(id:string,actor:{id:string;username:string;role:string}){return mutateMetaApproval(id,'submit',actor);}
export async function approveMetaAdsCampaign(id:string,actor:{id:string;username:string;role:string}){return mutateMetaApproval(id,'approve',actor);}
export async function rejectMetaAdsCampaign(id:string,actor:{id:string;username:string;role:string}){return mutateMetaApproval(id,'reject',actor);}
export async function marketingCampaignAssignees(){return marketingAssignees();}
