import {db} from '@/lib/db';
import {listMarketingLeads} from '@/lib/workspace/marketing';
import {listMarketingCampaigns} from '@/lib/workspace/marketing-campaigns';

export type MarketingAttribution={paymentId:string;paymentReference:string;leadId:string;leadName:string;campaignId?:string|null;campaignName?:string|null;source:string;amount:number;currency:string;attributedAt:string;attributedById:string;attributedByName:string};
const CATEGORY='Marketing Attribution',PREFIX='marketing.attribution.';
function parse(v:unknown):MarketingAttribution|null{if(!v||typeof v!=='object')return null;const x=v as MarketingAttribution;return x.paymentId&&x.paymentReference&&x.leadId&&x.currency?x:null;}
function key(paymentId:string){return `${PREFIX}${paymentId}`;}
export async function listMarketingAttributions(){const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PREFIX}},orderBy:{updatedAt:'desc'}});return rows.map(r=>parse(r.value)).filter((x):x is MarketingAttribution=>Boolean(x));}
export async function setMarketingAttribution(input:{paymentId:string;leadId:string;campaignId?:string|null;userId:string;userName:string}){const [payment,leads,campaigns]=await Promise.all([db.payment.findUnique({where:{id:input.paymentId},select:{id:true,reference:true,status:true,amount:true,currency:true}}),listMarketingLeads(),listMarketingCampaigns()]);if(!payment||payment.status!=='PAID')throw new Error('paid_payment_required');const lead=leads.find(x=>x.id===input.leadId);if(!lead)throw new Error('lead_not_found');const campaign=input.campaignId?campaigns.find(x=>x.id===input.campaignId):null;if(input.campaignId&&!campaign)throw new Error('campaign_not_found');const attribution:MarketingAttribution={paymentId:payment.id,paymentReference:payment.reference,leadId:lead.id,leadName:lead.name,campaignId:campaign?.id||null,campaignName:campaign?.name||null,source:lead.source,amount:Number(payment.amount),currency:payment.currency,attributedAt:new Date().toISOString(),attributedById:input.userId,attributedByName:input.userName};await db.appSetting.upsert({where:{key:key(payment.id)},create:{key:key(payment.id),category:CATEGORY,value:attribution as any,updatedBy:input.userId},update:{value:attribution as any,updatedBy:input.userId}});return attribution;}
export async function deleteMarketingAttribution(paymentId:string,userId:string){await db.appSetting.deleteMany({where:{key:key(paymentId),category:CATEGORY}});return {paymentId,userId};}
export async function marketingAttributionWorkspace(){const [attributions,leads,campaigns,payments]=await Promise.all([listMarketingAttributions(),listMarketingLeads(),listMarketingCampaigns(),db.payment.findMany({where:{status:'PAID'},orderBy:{updatedAt:'desc'},take:100,select:{id:true,reference:true,amount:true,currency:true,updatedAt:true,conversation:{select:{customer:{select:{displayName:true,phone:true,email:true}}}}}})]);const used=new Set(attributions.map(x=>x.paymentId));return {attributions,leads,campaigns,payments:payments.map(p=>({id:p.id,reference:p.reference,amount:Number(p.amount),currency:p.currency,updatedAt:p.updatedAt.toISOString(),customerName:p.conversation?.customer?.displayName||null,phone:p.conversation?.customer?.phone||null,email:p.conversation?.customer?.email||null,attributed:used.has(p.id)}))};}
