import {randomUUID} from 'node:crypto';
import {db} from '@/lib/db';
import {getMarketingScorecard} from '@/services/workspace/marketing-scorecard';

export const WEEKLY_REVIEW_STATUSES=['DRAFT','REVIEWED','CLOSED'] as const;
export const WEEKLY_ACTION_STATUSES=['OPEN','IN_PROGRESS','DONE','CANCELLED'] as const;
export type WeeklyReviewStatus=(typeof WEEKLY_REVIEW_STATUSES)[number];
export type WeeklyActionStatus=(typeof WEEKLY_ACTION_STATUSES)[number];
export type WeeklyAction={id:string;title:string;owner?:string|null;dueAt?:string|null;status:WeeklyActionStatus};
export type MarketingWeeklyReview={id:string;weekKey:string;weekStart:string;weekEnd:string;status:WeeklyReviewStatus;summary?:string|null;wins?:string|null;risks?:string|null;decisions?:string|null;actions:WeeklyAction[];snapshot:any;createdAt:string;updatedAt:string;createdById:string;updatedByName:string};
const CATEGORY='Marketing Weekly Reviews',PREFIX='marketing.weekly_review.';
function parse(v:unknown):MarketingWeeklyReview|null{if(!v||typeof v!=='object')return null;const x=v as MarketingWeeklyReview;return x.id&&x.weekKey&&x.weekStart&&x.weekEnd&&WEEKLY_REVIEW_STATUSES.includes(x.status)&&Array.isArray(x.actions)&&x.snapshot?x:null;}
function weekBounds(){const now=new Date(),day=(now.getDay()+6)%7,start=new Date(now);start.setDate(now.getDate()-day);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(start.getDate()+6);end.setHours(23,59,59,999);const key=`${start.getFullYear()}-W${String(Math.ceil((((start.getTime()-new Date(start.getFullYear(),0,1).getTime())/86400000)+new Date(start.getFullYear(),0,1).getDay()+1)/7)).padStart(2,'0')}`;return {weekKey:key,weekStart:start.toISOString(),weekEnd:end.toISOString()};}
export async function listMarketingWeeklyReviews(){const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PREFIX}},orderBy:{updatedAt:'desc'}});return rows.map(r=>parse(r.value)).filter((x):x is MarketingWeeklyReview=>x!==null);}
export async function createMarketingWeeklyReview(input:{summary?:string|null;wins?:string|null;risks?:string|null;decisions?:string|null;actions?:Array<Partial<WeeklyAction>&{title:string}>;createdById:string;createdByName:string}){const b=weekBounds(),existing=(await listMarketingWeeklyReviews()).find(x=>x.weekKey===b.weekKey);if(existing)throw new Error('weekly_review_already_exists');const now=new Date().toISOString(),id=randomUUID(),snapshot=await getMarketingScorecard();const actions=(input.actions||[]).filter(x=>x.title?.trim()).map(x=>({id:randomUUID(),title:x.title.trim(),owner:x.owner?.trim()||null,dueAt:x.dueAt||null,status:WEEKLY_ACTION_STATUSES.includes(x.status as WeeklyActionStatus)?x.status as WeeklyActionStatus:'OPEN'}));const item:MarketingWeeklyReview={id,...b,status:'DRAFT',summary:input.summary?.trim()||null,wins:input.wins?.trim()||null,risks:input.risks?.trim()||null,decisions:input.decisions?.trim()||null,actions,snapshot,createdAt:now,updatedAt:now,createdById:input.createdById,updatedByName:input.createdByName};await db.appSetting.create({data:{key:`${PREFIX}${id}`,category:CATEGORY,value:item as any,updatedBy:input.createdById}});return item;}
export async function updateMarketingWeeklyReview(id:string,patch:Partial<Pick<MarketingWeeklyReview,'status'|'summary'|'wins'|'risks'|'decisions'|'actions'>>,{userId,userName}:{userId:string;userName:string}){const key=`${PREFIX}${id}`,row=await db.appSetting.findUnique({where:{key}}),current=parse(row?.value);if(!current)throw new Error('weekly_review_not_found');const next:any={...current,...patch,updatedAt:new Date().toISOString(),updatedByName:userName};if(patch.actions)next.actions=patch.actions.filter(x=>x.title?.trim()).map(x=>({id:x.id||randomUUID(),title:x.title.trim(),owner:x.owner?.trim()||null,dueAt:x.dueAt||null,status:WEEKLY_ACTION_STATUSES.includes(x.status)?x.status:'OPEN'}));await db.appSetting.update({where:{key},data:{value:next as any,updatedBy:userId}});return next as MarketingWeeklyReview;}
