import {randomUUID} from 'node:crypto';
import {db} from '@/lib/db';
const EVENT_CATEGORY='DONI Marketing Publisher Events';const EVENT_PREFIX='marketing.publisher.';const AUTOPILOT_CATEGORY='DONI Marketing Autopilot';const AUTOPILOT_PREFIX='marketing.autopilot.';
type Actor={id:string;username:string;role:string};
function isAdmin(r:string){return r==='ADMIN'||r==='SUPER_ADMIN';}
function ev(v:unknown){return v&&typeof v==='object'?(v as any):null;}
export async function getPublisherControlCenter(){const events=await db.appSetting.findMany({where:{category:EVENT_CATEGORY,key:{startsWith:EVENT_PREFIX}},orderBy:{createdAt:'desc'},take:200});const parsed=events.map(x=>ev(x.value)).filter(Boolean);const latest=new Map<string,any>();for(const e of parsed)if(e.itemId&&!latest.has(e.itemId))latest.set(e.itemId,e);const counts={SENT:0,FAILED:0,BLOCKED:0,DRY_RUN:0,RETRY_REQUESTED:0};for(const e of parsed)if(e.status in counts)(counts as any)[e.status]++;const items=await db.appSetting.findMany({where:{category:AUTOPILOT_CATEGORY,key:{startsWith:AUTOPILOT_PREFIX}},orderBy:{updatedAt:'desc'},take:100});const queue=items.map(x=>x.value as any).filter(x=>x?.id).map(x=>({id:x.id,title:x.title,status:x.status,channel:x.channelSuggestion,scheduledFor:x.scheduledFor||null,approvedBy:x.approvedBy||null,latestEvent:latest.get(x.id)||null}));return{counts,events:parsed,queue,generatedAt:new Date().toISOString()};}
export async function retryPublisherItem(itemId:string,actor:Actor){if(!isAdmin(actor.role))return{ok:false,reason:'admin_required'} as const;const item=await db.appSetting.findUnique({where:{key:`${AUTOPILOT_PREFIX}${itemId}`}});const v=item?.value as any;if(!v||v.status!=='SCHEDULED')return{ok:false,reason:'item_not_scheduled'} as const;const events=await db.appSetting.findMany({where:{category:EVENT_CATEGORY,key:{startsWith:EVENT_PREFIX}},orderBy:{createdAt:'desc'},take:200});const latest=events.map(x=>ev(x.value)).find(e=>e?.itemId===itemId);if(!latest||!['FAILED','BLOCKED','DRY_RUN'].includes(String(latest.status)))return{ok:false,reason:'retry_not_allowed'} as const;const now=new Date().toISOString();await db.appSetting.create({data:{key:`${EVENT_PREFIX}${now}.${randomUUID()}`,category:EVENT_CATEGORY,value:{itemId,status:'RETRY_REQUESTED',channel:v.channelSuggestion,at:now,actor:actor.username,reason:`retry_after:${latest.status}`} as any}});return{ok:true} as const;}
export async function publisherRetryAllowed(itemId:string){const events=await db.appSetting.findMany({where:{category:EVENT_CATEGORY,key:{startsWith:EVENT_PREFIX}},orderBy:{createdAt:'desc'},take:200});const latest=events.map(x=>ev(x.value)).find(e=>e?.itemId===itemId);return !latest||latest.status==='RETRY_REQUESTED'||latest.status==='SENT';}
