import {randomUUID} from 'node:crypto';
import {db} from '@/lib/db';
import {marketingAssignees,listMarketingContent} from '@/lib/workspace/marketing';
import {listMarketingStudio} from '@/lib/workspace/marketing-studio';
import {assetGovernance,listMarketingAssets} from '@/lib/workspace/marketing-assets';

export const PUBLISHING_PLATFORMS=['FACEBOOK','INSTAGRAM','TIKTOK','WHATSAPP','GOOGLE_BUSINESS','OTHER'] as const;
export const PUBLISHING_STATUSES=['DRAFT','BLOCKED','READY','APPROVED','HANDED_OFF','PUBLISHED','CANCELLED'] as const;
export type PublishingPlatform=(typeof PUBLISHING_PLATFORMS)[number];
export type PublishingStatus=(typeof PUBLISHING_STATUSES)[number];
export type MarketingPublishingItem={id:string;title:string;platform:PublishingPlatform;status:PublishingStatus;contentId?:string|null;contentTitle?:string|null;studioId?:string|null;studioTitle?:string|null;assetIds:string[];caption?:string|null;cta?:string|null;destinationUrl?:string|null;scheduledAt?:string|null;ownerId?:string|null;ownerName?:string|null;approvalNote?:string|null;approvedAt?:string|null;approvedBy?:string|null;handedOffAt?:string|null;publishedAt?:string|null;externalPostUrl?:string|null;createdAt:string;updatedAt:string;createdById:string;updatedByName:string};
export type PublishingGovernance={ready:boolean;blockers:string[];warnings:string[];manualOnly:boolean};
const CATEGORY='Marketing Publishing',PREFIX='marketing.publishing.';
function parse(v:unknown):MarketingPublishingItem|null{if(!v||typeof v!=='object')return null;const x=v as MarketingPublishingItem;return x.id&&x.title&&PUBLISHING_PLATFORMS.includes(x.platform)&&PUBLISHING_STATUSES.includes(x.status)&&Array.isArray(x.assetIds)?x:null;}
async function resolveUserName(id?:string|null){if(!id)return null;const users=await marketingAssignees();const u=users.find(x=>x.id===id);return u?.fullName||u?.username||null;}
export async function listMarketingPublishing(){const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PREFIX}},orderBy:{updatedAt:'desc'}});return rows.map(r=>parse(r.value)).filter((x):x is MarketingPublishingItem=>x!==null);}
export async function publishingGovernance(item:MarketingPublishingItem):Promise<PublishingGovernance>{const [content,studio,assets]=await Promise.all([listMarketingContent(),listMarketingStudio(),listMarketingAssets()]);const blockers:string[]=[],warnings:string[]=[];const c=item.contentId?content.find(x=>x.id===item.contentId):null;if(!c)blockers.push('CONTENT_REQUIRED');else if(!['APPROVED','SCHEDULED','PUBLISHED'].includes(c.status))blockers.push('CONTENT_NOT_APPROVED');const s=item.studioId?studio.find(x=>x.id===item.studioId):null;if(item.studioId&&!s)blockers.push('STUDIO_NOT_FOUND');else if(s&&s.status!=='APPROVED')blockers.push('STUDIO_NOT_APPROVED');for(const id of item.assetIds){const a=assets.find(x=>x.id===id);if(!a){blockers.push(`ASSET_NOT_FOUND:${id}`);continue;}const g=assetGovernance(a);if(!g.usable)blockers.push(`ASSET_${g.reason}:${a.title}`);else if(g.expiresSoon)warnings.push(`ASSET_EXPIRES_SOON:${a.title}`);}if(!item.caption?.trim()&&item.platform!=='OTHER')warnings.push('CAPTION_EMPTY');const manualOnly=item.platform==='WHATSAPP';return {ready:blockers.length===0,blockers,warnings,manualOnly};}
export async function createMarketingPublishing(input:{title:string;platform:PublishingPlatform;contentId?:string|null;studioId?:string|null;assetIds?:string[];caption?:string|null;cta?:string|null;destinationUrl?:string|null;scheduledAt?:string|null;ownerId?:string|null;createdById:string;createdByName:string}){const now=new Date().toISOString(),id=randomUUID();const [content,studio]=await Promise.all([listMarketingContent(),listMarketingStudio()]);const c=content.find(x=>x.id===input.contentId),s=studio.find(x=>x.id===input.studioId);const item:MarketingPublishingItem={id,title:input.title.trim(),platform:input.platform,status:'DRAFT',contentId:c?.id||null,contentTitle:c?.title||null,studioId:s?.id||null,studioTitle:s?.title||null,assetIds:[...new Set(input.assetIds||[])].slice(0,12),caption:input.caption?.trim()||null,cta:input.cta?.trim()||null,destinationUrl:input.destinationUrl?.trim()||null,scheduledAt:input.scheduledAt||null,ownerId:input.ownerId||null,ownerName:await resolveUserName(input.ownerId),approvalNote:null,approvedAt:null,approvedBy:null,handedOffAt:null,publishedAt:null,externalPostUrl:null,createdAt:now,updatedAt:now,createdById:input.createdById,updatedByName:input.createdByName};await db.appSetting.create({data:{key:`${PREFIX}${id}`,category:CATEGORY,value:item as any,updatedBy:input.createdById}});return item;}
export async function updateMarketingPublishing(id:string,patch:Partial<Pick<MarketingPublishingItem,'title'|'platform'|'status'|'contentId'|'studioId'|'assetIds'|'caption'|'cta'|'destinationUrl'|'scheduledAt'|'ownerId'|'approvalNote'|'externalPostUrl'>>,{userId,userName}:{userId:string;userName:string}){const key=`${PREFIX}${id}`;const row=await db.appSetting.findUnique({where:{key}});const current=parse(row?.value);if(!current)throw new Error('marketing_publishing_not_found');const next:any={...current,...patch,updatedAt:new Date().toISOString(),updatedByName:userName};if(patch.ownerId!==undefined)next.ownerName=await resolveUserName(patch.ownerId);if(patch.contentId!==undefined){const c=(await listMarketingContent()).find(x=>x.id===patch.contentId);next.contentId=c?.id||null;next.contentTitle=c?.title||null;}if(patch.studioId!==undefined){const s=(await listMarketingStudio()).find(x=>x.id===patch.studioId);next.studioId=s?.id||null;next.studioTitle=s?.title||null;}if(patch.assetIds!==undefined)next.assetIds=[...new Set(patch.assetIds)].slice(0,12);
 const controlled=['READY','APPROVED','HANDED_OFF','PUBLISHED'];
 if(patch.status&&controlled.includes(patch.status)){
  const g=await publishingGovernance(next as MarketingPublishingItem);
  if(!g.ready){next.status='BLOCKED';next.approvalNote=`Bloqué: ${g.blockers.join(', ')}`;await db.appSetting.update({where:{key},data:{value:next as any,updatedBy:userId}});return next as MarketingPublishingItem;}
 }
 if(patch.status==='APPROVED'){next.approvedAt=new Date().toISOString();next.approvedBy=userName;}
 if(patch.status==='HANDED_OFF'){if(!current.approvedAt)throw new Error('approval_required');next.handedOffAt=new Date().toISOString();}
 if(patch.status==='PUBLISHED'){if(!current.approvedAt)throw new Error('approval_required');next.publishedAt=new Date().toISOString();}
 await db.appSetting.update({where:{key},data:{value:next as any,updatedBy:userId}});return next as MarketingPublishingItem;}
export async function marketingPublishingMeta(){const [users,content,studio,assets]=await Promise.all([marketingAssignees(),listMarketingContent(),listMarketingStudio(),listMarketingAssets()]);return {users,content:content.filter(x=>['APPROVED','SCHEDULED','PUBLISHED'].includes(x.status)),studio:studio.filter(x=>x.status==='APPROVED'),assets:assets.filter(x=>assetGovernance(x).usable)};}
