import {randomUUID} from 'node:crypto';
import {db} from '@/lib/db';
import {marketingAssignees} from '@/lib/workspace/marketing';

export const PARTNERSHIP_TYPES=['HOTEL','AIRLINE','INFLUENCER','COMPANY','BANK','EVENT','AGENCY','OTHER'] as const;
export const PARTNERSHIP_STATUSES=['PROSPECT','CONTACTED','MEETING','NEGOTIATION','PROPOSAL_SENT','SIGNED','ACTIVE','ON_HOLD','LOST'] as const;
export type PartnershipType=(typeof PARTNERSHIP_TYPES)[number];
export type PartnershipStatus=(typeof PARTNERSHIP_STATUSES)[number];
export type MarketingPartnership={id:string;name:string;type:PartnershipType;status:PartnershipStatus;contactName?:string|null;phone?:string|null;email?:string|null;country?:string|null;city?:string|null;ownerId?:string|null;ownerName?:string|null;estimatedValue:number;currency:string;nextAction?:string|null;nextActionAt?:string|null;notes?:string|null;createdAt:string;updatedAt:string;createdById:string;history:Array<{at:string;by:string;action:string;from?:string|null;to?:string|null}>};
const CATEGORY='Marketing Partnerships',PREFIX='marketing.partnership.';
function isPartnership(v:unknown):v is MarketingPartnership{if(!v||typeof v!=='object')return false;const x=v as MarketingPartnership;return Boolean(x.id&&x.name&&PARTNERSHIP_TYPES.includes(x.type)&&PARTNERSHIP_STATUSES.includes(x.status)&&Array.isArray(x.history));}
function num(v:unknown){const n=Number(v);return Number.isFinite(n)&&n>=0?n:0;}
async function resolveOwnerName(id?:string|null){if(!id)return null;const u=await db.portalUser.findUnique({where:{id},select:{fullName:true,username:true}});return u?.fullName||u?.username||null;}
export async function listMarketingPartnerships(){const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PREFIX}},orderBy:{updatedAt:'desc'}});return rows.map(r=>r.value).filter(isPartnership);}
export async function createMarketingPartnership(input:{name:string;type:PartnershipType;status?:PartnershipStatus;contactName?:string|null;phone?:string|null;email?:string|null;country?:string|null;city?:string|null;ownerId?:string|null;estimatedValue?:number;currency?:string;nextAction?:string|null;nextActionAt?:string|null;notes?:string|null;createdById:string;createdByName:string}){const now=new Date().toISOString(),id=randomUUID();const p:MarketingPartnership={id,name:input.name.trim(),type:input.type,status:input.status||'PROSPECT',contactName:input.contactName?.trim()||null,phone:input.phone?.trim()||null,email:input.email?.trim()||null,country:input.country?.trim()||null,city:input.city?.trim()||null,ownerId:input.ownerId||null,ownerName:await resolveOwnerName(input.ownerId),estimatedValue:num(input.estimatedValue),currency:(input.currency||'USD').trim().toUpperCase(),nextAction:input.nextAction?.trim()||null,nextActionAt:input.nextActionAt||null,notes:input.notes?.trim()||null,createdAt:now,updatedAt:now,createdById:input.createdById,history:[{at:now,by:input.createdByName,action:'CREATED'}]};await db.appSetting.create({data:{key:`${PREFIX}${id}`,category:CATEGORY,value:p as any,updatedBy:input.createdById}});return p;}
export async function updateMarketingPartnership(id:string,patch:Partial<Omit<MarketingPartnership,'id'|'createdAt'|'createdById'|'history'>>,{userId,userName}:{userId:string;userName:string}){const key=`${PREFIX}${id}`;const row=await db.appSetting.findUnique({where:{key}});if(!isPartnership(row?.value))throw new Error('partnership_not_found');const current=row.value as MarketingPartnership;const next:any={...current,...patch,updatedAt:new Date().toISOString()};if(patch.ownerId!==undefined)next.ownerName=await resolveOwnerName(patch.ownerId);if(patch.estimatedValue!==undefined)next.estimatedValue=num(patch.estimatedValue);const history=[...(current.history||[])];for(const [field,value] of Object.entries(patch)){const before=(current as any)[field];if(value!==undefined&&JSON.stringify(before)!==JSON.stringify(value))history.push({at:new Date().toISOString(),by:userName,action:`UPDATE_${field.toUpperCase()}`,from:before==null?null:String(before),to:value==null?null:String(value)});}next.history=history.slice(-100);await db.appSetting.update({where:{key},data:{value:next,updatedBy:userId}});return next as MarketingPartnership;}
export async function marketingPartnershipAssignees(){return marketingAssignees();}
