import {db} from '@/lib/db';

const CATEGORY='Meta Ads Launch';
const PREFIX='meta.ads.launch.';
export type MetaAdsLaunchStatus='IDLE'|'REQUESTED'|'APPROVED_FOR_LAUNCH'|'ACTIVE'|'PAUSED'|'FAILED';
export type MetaAdsLaunchControl={campaignId:string;status:MetaAdsLaunchStatus;requestedBy:string|null;requestedAt:string|null;approvedBy:string|null;approvedAt:string|null;activatedBy:string|null;activatedAt:string|null;pausedBy:string|null;pausedAt:string|null;lastError:string|null;updatedAt:string};
function key(id:string){return `${PREFIX}${id}`;}
function base(campaignId:string):MetaAdsLaunchControl{return{campaignId,status:'IDLE',requestedBy:null,requestedAt:null,approvedBy:null,approvedAt:null,activatedBy:null,activatedAt:null,pausedBy:null,pausedAt:null,lastError:null,updatedAt:new Date().toISOString()};}
export async function getMetaAdsLaunchControl(campaignId:string){const row=await db.appSetting.findUnique({where:{key:key(campaignId)}});return (row?.value as MetaAdsLaunchControl|null)||null;}
export async function listMetaAdsLaunchControls(){const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PREFIX}},orderBy:{updatedAt:'desc'}});return rows.map(r=>r.value as MetaAdsLaunchControl).filter(x=>x?.campaignId);}
async function save(campaignId:string,next:MetaAdsLaunchControl,userId:string){await db.appSetting.upsert({where:{key:key(campaignId)},create:{key:key(campaignId),category:CATEGORY,value:next as any,updatedBy:userId},update:{category:CATEGORY,value:next as any,updatedBy:userId}});return next;}
export async function requestMetaAdsLaunch(campaignId:string,actor:{id:string;username:string}){const now=new Date().toISOString();const cur=(await getMetaAdsLaunchControl(campaignId))||base(campaignId);if(cur.status==='ACTIVE')throw new Error('meta_ads_already_active');return save(campaignId,{...cur,status:'REQUESTED',requestedBy:actor.username,requestedAt:now,approvedBy:null,approvedAt:null,lastError:null,updatedAt:now},actor.id);}
export async function approveMetaAdsLaunch(campaignId:string,actor:{id:string;username:string;role:string}){if(actor.role!=='SUPER_ADMIN')throw new Error('super_admin_required');const cur=await getMetaAdsLaunchControl(campaignId);if(!cur||cur.status!=='REQUESTED')throw new Error('meta_ads_launch_request_required');const now=new Date().toISOString();return save(campaignId,{...cur,status:'APPROVED_FOR_LAUNCH',approvedBy:actor.username,approvedAt:now,lastError:null,updatedAt:now},actor.id);}
export async function recordMetaAdsActivated(campaignId:string,actor:{id:string;username:string}){const cur=await getMetaAdsLaunchControl(campaignId);if(!cur||cur.status!=='APPROVED_FOR_LAUNCH')throw new Error('meta_ads_launch_approval_required');const now=new Date().toISOString();return save(campaignId,{...cur,status:'ACTIVE',activatedBy:actor.username,activatedAt:now,lastError:null,updatedAt:now},actor.id);}
export async function recordMetaAdsPaused(campaignId:string,actor:{id:string;username:string}){const cur=(await getMetaAdsLaunchControl(campaignId))||base(campaignId);const now=new Date().toISOString();return save(campaignId,{...cur,status:'PAUSED',pausedBy:actor.username,pausedAt:now,lastError:null,updatedAt:now},actor.id);}
export async function recordMetaAdsLaunchFailure(campaignId:string,error:string,userId:string){const cur=(await getMetaAdsLaunchControl(campaignId))||base(campaignId);const now=new Date().toISOString();return save(campaignId,{...cur,status:'FAILED',lastError:String(error).slice(0,500),updatedAt:now},userId);}
