import {randomUUID} from 'node:crypto';
import {db} from '@/lib/db';

export type NotificationSeverity='INFO'|'WARNING'|'CRITICAL';
export type InternalNotification={id:string;recipientId:string;title:string;message:string;severity:NotificationSeverity;href?:string|null;dedupeKey?:string|null;readAt?:string|null;createdAt:string;updatedAt:string};
const PREFIX='workspace.notification.';
const CATEGORY='Workspace Notifications';
function parse(v:unknown):InternalNotification|null{if(!v||typeof v!=='object')return null;const n=v as InternalNotification;return n.id&&n.recipientId&&n.title&&n.createdAt?n:null;}
export async function listInternalNotifications(recipientId:string,limit=60){const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PREFIX}},orderBy:{updatedAt:'desc'}});return rows.map(r=>parse(r.value)).filter((n):n is InternalNotification=>Boolean(n)&&n.recipientId===recipientId).sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime()).slice(0,limit);}
export async function unreadInternalNotificationCount(recipientId:string){const rows=await listInternalNotifications(recipientId,200);return rows.filter(n=>!n.readAt).length;}
export async function upsertInternalNotification(input:{recipientId:string;title:string;message:string;severity?:NotificationSeverity;href?:string|null;dedupeKey:string}){const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PREFIX}}});const current=rows.map(r=>parse(r.value)).find(n=>n?.recipientId===input.recipientId&&n.dedupeKey===input.dedupeKey)||null;const now=new Date().toISOString();if(current){const next={...current,title:input.title,message:input.message,severity:input.severity||'INFO',href:input.href||null,updatedAt:now};await db.appSetting.update({where:{key:`${PREFIX}${current.id}`},data:{value:next as any,updatedBy:'DONI_NOTIFICATIONS'}});return next;}const n:InternalNotification={id:randomUUID(),recipientId:input.recipientId,title:input.title,message:input.message,severity:input.severity||'INFO',href:input.href||null,dedupeKey:input.dedupeKey,readAt:null,createdAt:now,updatedAt:now};await db.appSetting.create({data:{key:`${PREFIX}${n.id}`,category:CATEGORY,value:n as any,updatedBy:'DONI_NOTIFICATIONS'}});return n;}
export async function markInternalNotificationRead(id:string,recipientId:string,read=true){const key=`${PREFIX}${id}`;const row=await db.appSetting.findUnique({where:{key}});const current=parse(row?.value);if(!current||current.recipientId!==recipientId)throw new Error('notification_not_found');const next={...current,readAt:read?new Date().toISOString():null,updatedAt:new Date().toISOString()};await db.appSetting.update({where:{key},data:{value:next as any,updatedBy:recipientId}});return next;}
export async function markAllInternalNotificationsRead(recipientId:string){const rows=await listInternalNotifications(recipientId,200);let count=0;for(const n of rows){if(!n.readAt){await markInternalNotificationRead(n.id,recipientId,true);count++;}}return count;}
