import {randomUUID} from 'node:crypto';
import {db} from '@/lib/db';
import type {Department} from '@/lib/auth/departments';

export const TASK_STATUSES=['OPEN','IN_PROGRESS','BLOCKED','DONE'] as const;
export const TASK_PRIORITIES=['LOW','NORMAL','HIGH','URGENT'] as const;
export type TaskStatus=(typeof TASK_STATUSES)[number];
export type TaskPriority=(typeof TASK_PRIORITIES)[number];
export type WorkspaceTask={id:string;title:string;description?:string|null;department:Department;priority:TaskPriority;status:TaskStatus;assigneeId?:string|null;assigneeName?:string|null;dueAt?:string|null;entityType?:string|null;entityId?:string|null;createdById:string;createdByName?:string|null;createdAt:string;updatedAt:string;history:Array<{at:string;by:string;action:string;from?:string|null;to?:string|null}>};
const PREFIX='workspace.task.';
const CATEGORY='Workspace Tasks';
function validStatus(v:unknown):v is TaskStatus{return typeof v==='string'&&(TASK_STATUSES as readonly string[]).includes(v)}
function validPriority(v:unknown):v is TaskPriority{return typeof v==='string'&&(TASK_PRIORITIES as readonly string[]).includes(v)}
function parse(v:unknown):WorkspaceTask|null{if(!v||typeof v!=='object')return null;const t=v as WorkspaceTask;return t.id&&t.title&&t.department&&validStatus(t.status)&&validPriority(t.priority)?t:null;}
export async function listWorkspaceTasks(filter?:{department?:Department;assigneeId?:string;includeDone?:boolean}){const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PREFIX}},orderBy:{updatedAt:'desc'}});let tasks=rows.map(r=>parse(r.value)).filter((x):x is WorkspaceTask=>Boolean(x));if(filter?.department)tasks=tasks.filter(t=>t.department===filter.department);if(filter?.assigneeId)tasks=tasks.filter(t=>t.assigneeId===filter.assigneeId);if(!filter?.includeDone)tasks=tasks.filter(t=>t.status!=='DONE');return tasks.sort((a,b)=>{const rank={URGENT:0,HIGH:1,NORMAL:2,LOW:3};const p=rank[a.priority]-rank[b.priority];if(p)return p;const ad=a.dueAt?new Date(a.dueAt).getTime():Number.MAX_SAFE_INTEGER,bd=b.dueAt?new Date(b.dueAt).getTime():Number.MAX_SAFE_INTEGER;return ad-bd;});}
export async function createWorkspaceTask(input:{title:string;description?:string|null;department:Department;priority?:TaskPriority;assigneeId?:string|null;dueAt?:string|null;entityType?:string|null;entityId?:string|null;createdById:string;createdByName?:string|null}){const now=new Date().toISOString();let assigneeName:string|null=null;if(input.assigneeId){const u=await db.portalUser.findUnique({where:{id:input.assigneeId},select:{fullName:true,username:true}});assigneeName=u?.fullName||u?.username||null;}const task:WorkspaceTask={id:randomUUID(),title:input.title.trim(),description:input.description?.trim()||null,department:input.department,priority:input.priority||'NORMAL',status:'OPEN',assigneeId:input.assigneeId||null,assigneeName,dueAt:input.dueAt||null,entityType:input.entityType||null,entityId:input.entityId||null,createdById:input.createdById,createdByName:input.createdByName||null,createdAt:now,updatedAt:now,history:[{at:now,by:input.createdByName||input.createdById,action:'CREATED'}]};await db.appSetting.create({data:{key:`${PREFIX}${task.id}`,category:CATEGORY,value:task as any,updatedBy:input.createdById}});return task;}
export async function updateWorkspaceTask(id:string,patch:Partial<Pick<WorkspaceTask,'title'|'description'|'department'|'priority'|'status'|'assigneeId'|'dueAt'|'entityType'|'entityId'>>,{userId,userName}:{userId:string;userName:string}){const key=`${PREFIX}${id}`;const row=await db.appSetting.findUnique({where:{key}});const current=parse(row?.value);if(!current)throw new Error('task_not_found');const next:{[k:string]:any}={...current};const history=[...(current.history||[])];for(const [field,value] of Object.entries(patch)){if(value===undefined)continue;const before=(current as any)[field];if(before!==value){next[field]=value;history.push({at:new Date().toISOString(),by:userName,action:`UPDATE_${field.toUpperCase()}`,from:before==null?null:String(before),to:value==null?null:String(value)});}}if(patch.assigneeId!==undefined){if(patch.assigneeId){const u=await db.portalUser.findUnique({where:{id:patch.assigneeId},select:{fullName:true,username:true}});next.assigneeName=u?.fullName||u?.username||null;}else next.assigneeName=null;}next.updatedAt=new Date().toISOString();next.history=history.slice(-50);await db.appSetting.update({where:{key},data:{value:next,updatedBy:userId}});return next as WorkspaceTask;}
export async function taskAssignees(){return db.portalUser.findMany({where:{active:true},orderBy:[{role:'desc'},{fullName:'asc'}],select:{id:true,username:true,fullName:true,role:true}});}
