import {DoniShell} from '@/components/DoniShell';
import {requirePageUser} from '@/lib/auth/session';
import {getCustomerServiceWorkCenter} from '@/services/workspace/work-centers';
import {MetricCard} from '@/components/analytics/MetricCard';
import {WorkCenterHeader,WorkQueue} from '@/components/workspace/WorkQueue';
import {AutoRefresh} from '@/components/analytics/AutoRefresh';
export const dynamic='force-dynamic';
function age(v:Date){const m=Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/60000));return m<60?`${m} min`:m<1440?`${Math.floor(m/60)} h`:`${Math.floor(m/1440)} j`;}
export default async function Page(){const user=await requirePageUser('AGENT');if(user.role==='AGENT'&&!['CUSTOMER_SERVICE','OPERATIONS','MANAGEMENT'].includes(user.department||''))return <DoniShell title="Service client" active="/service-client" user={user}><div className="card"><strong>Accès réservé au Service client.</strong></div></DoniShell>;const d=await getCustomerServiceWorkCenter();return <DoniShell title="Service client" active="/service-client" user={user}><AutoRefresh seconds={30}/><WorkCenterHeader kicker="Service client" title="Centre de relation client" description="Traiter d'abord les conversations et demandes qui bloquent le voyage du client." actions={[{label:'Live Ops',href:'/live-ops'},{label:'Après-vente',href:'/post-booking'}]}/><div className="grid"><MetricCard label="Conversations à reprendre" value={d.agentRequired.length} tone={d.agentRequired.length?'bad':'good'}/><MetricCard label="Après-vente ouverts" value={d.postBooking.length} tone={d.postBooking.length?'warn':'good'}/><MetricCard label="Check-in actifs" value={d.checkins.length}/><MetricCard label="Bagages en cours" value={d.baggage.length}/></div><div className="workCenterGrid"><WorkQueue title="Priorité client" note="Conversations nécessitant une intervention humaine" items={d.agentRequired.map(x=>({key:x.id,title:x.waId,meta:`${x.country||'Pays inconnu'} · ${x.currentSegment} · attente ${age(x.updatedAt)}`,href:'/live-ops',tone:'bad' as const,badge:'Agent requis'}))}/><WorkQueue title="Après-vente" note="Demandes encore ouvertes" items={d.postBooking.map(x=>({key:x.id,title:`${x.reference} · ${x.requestType}`,meta:`${x.status} · ${x.phone||'sans téléphone'} · ${age(x.createdAt)}`,href:'/post-booking',tone:x.priority==='critical'?'bad' as const:'warn' as const,badge:x.priority||'Ouvert'}))}/><WorkQueue title="Check-in" items={d.checkins.map(x=>({key:x.id,title:`${x.tracking.ticketReference||'Dossier'} · ${x.tracking.airlineCode}${x.tracking.flightNumber}`,meta:`${x.status} · départ ${new Date(x.tracking.scheduledDeparture).toLocaleString('fr-FR')}`,href:'/checkin',badge:x.paymentStatus||x.status}))}/><WorkQueue title="Bagages" items={d.baggage.map(x=>({key:x.id,title:`${x.tracking.ticketReference||'Dossier'} · ${x.quantity} bagage(s)`,meta:`${x.weightKg?`${x.weightKg} kg · `:''}${x.status} · ${x.tracking.clientPhone||'sans téléphone'}`,href:'/baggage',badge:x.paymentStatus||x.status}))}/></div></DoniShell>}
