import {NextResponse} from 'next/server';
import {requireApiUser} from '@/lib/auth/session';
import {requireRecentStepUp} from '@/lib/auth/session-security';
import {audit} from '@/lib/audit';
import {SETTING_BY_KEY} from '@/lib/settings/catalog';
import {clearSetting,saveSetting,settingsSnapshot} from '@/lib/settings/service';
export const runtime='nodejs';
export async function GET(){const auth=await requireApiUser('ADMIN');if(!auth.ok)return NextResponse.json({success:false,error:auth.error},{status:auth.status});return NextResponse.json({success:true,settings:await settingsSnapshot(),canEditSecrets:auth.user.orgRole==='SUPER_ADMIN',canEditSettings:auth.user.orgRole==='SUPER_ADMIN'});}
export async function PUT(req:Request){const auth=await requireApiUser('AGENT');if(!auth.ok)return NextResponse.json({success:false,error:auth.error},{status:auth.status});if(auth.user.orgRole!=='SUPER_ADMIN')return NextResponse.json({success:false,error:'super_admin_required'},{status:403});const step=await requireRecentStepUp();if(!step.ok)return NextResponse.json({success:false,error:step.error,windowSeconds:step.windowSeconds},{status:step.status});try{const body=await req.json();const key=String(body.key||'');const def=SETTING_BY_KEY.get(key);if(!def)return NextResponse.json({success:false,error:'unknown_setting'},{status:400});if(body.clear===true){await clearSetting(key);await audit({userId:auth.user.id,action:'SETTING_CLEAR',entity:'AppSetting',entityId:key,metadata:{category:def.category,secret:def.type==='secret',stepUp:true}});return NextResponse.json({success:true});}await saveSetting(key,body.value,auth.user.id);await audit({userId:auth.user.id,action:'SETTING_UPDATE',entity:'AppSetting',entityId:key,metadata:{category:def.category,secret:def.type==='secret',stepUp:true}});return NextResponse.json({success:true});}catch(e){return NextResponse.json({success:false,error:e instanceof Error?e.message:'settings_update_failed'},{status:400});}}
