import {redirect} from 'next/navigation';
import {DoniShell} from '@/components/DoniShell';
import {requirePageUser} from '@/lib/auth/session';
import {canAccessMarketing} from '@/lib/auth/marketing-access';
import {getMarketingCommandCenter} from '@/lib/workspace/marketing-command-center';
export const dynamic='force-dynamic';
function readinessLabel(v:string){return v==='READY'?'READY FOR PRODUCTION':v==='CONDITIONAL'?'PRÊT SOUS CONDITIONS':'NON PRÊT';}
function checkLabel(v:string){return v==='PASS'?'OK':v==='WARNING'?'Attention':'Bloquant';}
export default async function Page(){const user=await requirePageUser('AGENT');if(!canAccessMarketing(user))redirect('/overview?forbidden=1');const data=await getMarketingCommandCenter();return <DoniShell title="Marketing Command Center" active="/marketing/command-center" user={user}>
<section className={`workspaceWelcome commandHero ${data.readiness.toLowerCase()}`}><div><span className="workspaceKicker">Marketing V2 · Final Production Readiness</span><h2>{readinessLabel(data.readiness)}</h2><p>Vue consolidée de toute la chaîne DONI Marketing : intelligence, récupération, offres live, conformité, publication, engagement, apprentissage et expérimentation.</p></div><div className="commandScore"><strong>{data.score}</strong><span>/100</span><small>{data.critical} bloquant · {data.warnings} avertissement</small></div></section>
<div className="marketingKpis"><div className="card"><span>Recherches 30j</span><strong>{data.metrics.searches}</strong><small>{data.metrics.highIntent} forte intention</small></div><div className="card"><span>Réservations abandonnées</span><strong>{data.metrics.abandoned}</strong></div><div className="card"><span>Offres live vérifiées</span><strong>{data.metrics.verifiedOffers}</strong></div><div className="card"><span>Lecture WhatsApp</span><strong>{data.metrics.readRate}%</strong><small>Réponse {data.metrics.replyRate}%</small></div><div className="card"><span>Conversion 7 jours</span><strong>{data.metrics.conversionRate}%</strong></div><div className="card"><span>Learning Score</span><strong>{data.metrics.learningScore}/100</strong><small>{data.metrics.promotedLearnings} learnings promus</small></div></div>
<section className="card commandChecks"><div className="searchIntelHead"><div><span>Production Gate</span><h3>Contrôles de préparation</h3></div><small>{data.passed} OK · {data.warnings} attention · {data.critical} bloquant</small></div><div className="commandCheckGrid">{data.checks.map(x=><a href={x.route} className={`commandCheck ${x.level.toLowerCase()}`} key={x.id}><div><span>{checkLabel(x.level)}</span><h4>{x.label}</h4></div><p>{x.detail}</p></a>)}</div></section>
<section className="card commandModules"><div className="searchIntelHead"><div><span>System Map</span><h3>État des moteurs Marketing V2</h3></div><small>Lecture seule · aucune action automatique</small></div><div className="commandModuleRows">{data.modules.map(x=><a href={x.route} className="commandModuleRow" key={x.name}><div><span>{x.status}</span><h4>{x.name}</h4></div><strong>{x.primary}</strong><small>{x.secondary}</small><b>Ouvrir →</b></a>)}</div></section>
<section className="card commandSafety"><div><span>Garde-fous finaux</span><h3>Contrôle humain conservé</h3></div><p>DONI peut détecter, analyser, recommander, préparer, mesurer et apprendre. L’envoi réel reste soumis aux règles de consentement, au Policy Guard et au workflow d’approbation. Les expériences ne choisissent ni n’appliquent automatiquement un gagnant et aucun budget publicitaire n’est dépensé automatiquement.</p><small>Snapshot généré {new Date(data.generatedAt).toLocaleString('fr-FR')}</small></section>
</DoniShell>}
