import {redirect} from 'next/navigation';
import {revalidatePath} from 'next/cache';
import {DoniShell} from '@/components/DoniShell';
import {requirePageUser} from '@/lib/auth/session';
import {canAccessMarketing} from '@/lib/auth/marketing-access';
import {getPublisherControlCenter,retryPublisherItem} from '@/lib/workspace/marketing-publisher-control';
export const dynamic='force-dynamic';
function label(s:string){return ({SENT:'Envoyé',FAILED:'Échec',BLOCKED:'Bloqué',DRY_RUN:'Dry run',RETRY_REQUESTED:'Remis en file'} as Record<string,string>)[s]||s;}
function date(v:string|null|undefined){return v?new Date(v).toLocaleString('fr-FR'):'—';}
export default async function Page(){const user=await requirePageUser('AGENT');if(!canAccessMarketing(user))redirect('/overview?forbidden=1');const data=await getPublisherControlCenter();const isAdmin=user.role==='ADMIN'||user.role==='SUPER_ADMIN';async function retry(formData:FormData){'use server';const u=await requirePageUser('ADMIN');const id=String(formData.get('itemId')||'');if(id)await retryPublisherItem(id,{id:u.id,username:u.username,role:u.role});revalidatePath('/marketing/publisher-control');}
return <DoniShell title="Publisher Control Center" active="/marketing/publisher-control" user={user}>
<section className="workspaceWelcome"><div><span className="workspaceKicker">Marketing V2 · Exécution contrôlée</span><h2>Publisher Control Center</h2><p>Supervision des publications réellement exécutées par le worker. Les échecs et blocages restent en pause jusqu’à une remise en file explicite par un administrateur.</p></div></section>
<div className="marketingKpis"><div className="card"><span>Envoyés</span><strong>{data.counts.SENT}</strong></div><div className="card"><span>Échecs</span><strong>{data.counts.FAILED}</strong></div><div className="card"><span>Bloqués</span><strong>{data.counts.BLOCKED}</strong></div><div className="card"><span>Dry run</span><strong>{data.counts.DRY_RUN}</strong></div><div className="card"><span>Remis en file</span><strong>{data.counts.RETRY_REQUESTED}</strong></div></div>
<section className="card publisherQueue"><div className="searchIntelHead"><div><span>File contrôlée</span><h3>Campagnes et dernier état d’exécution</h3></div><small>Retry manuel admin uniquement</small></div><div className="publisherRows">{data.queue.map((x:any)=><article className="publisherRow" key={x.id}><div><span className="publisherStatus">{x.latestEvent?label(x.latestEvent.status):x.status}</span><h4>{x.title}</h4><small>{x.channel||'Canal non défini'} · planifiée {date(x.scheduledFor)}</small></div><div><span>Dernière tentative</span><strong>{x.latestEvent?date(x.latestEvent.at):'Aucune'}</strong><small>{x.latestEvent?.reason||'—'}</small></div><div><span>Approbateur</span><strong>{x.approvedBy||'—'}</strong></div><div>{isAdmin&&x.latestEvent&&['FAILED','BLOCKED','DRY_RUN'].includes(x.latestEvent.status)?<form action={retry}><input type="hidden" name="itemId" value={x.id}/><button className="primaryButton" type="submit">Remettre en file</button></form>:null}</div></article>)}</div></section>
<section className="card publisherEvents"><div className="searchIntelHead"><div><span>Journal</span><h3>Historique des tentatives</h3></div><small>200 derniers événements</small></div><div className="publisherEventList">{data.events.map((e:any,i:number)=><div className="publisherEvent" key={`${e.at}-${i}`}><strong>{label(e.status)}</strong><span>{e.itemId}</span><span>{e.channel||'—'}</span><span>{date(e.at)}</span><small>{e.reason||e.actor||''}</small></div>)}</div></section>
</DoniShell>}
