import {redirect} from 'next/navigation';
import {revalidatePath} from 'next/cache';
import {DoniShell} from '@/components/DoniShell';
import {requirePageUser} from '@/lib/auth/session';
import {canAccessMarketing} from '@/lib/auth/marketing-access';
import {getPublisherControlCenter,retryPublisherItem} from '@/lib/workspace/marketing-publisher-control';
import {savePublisherPolicy} from '@/lib/workspace/marketing-publisher-policy';
export const dynamic='force-dynamic';
function label(s:string){return ({SENT:'Envoyé',FAILED:'Échec',BLOCKED:'Bloqué',DRY_RUN:'Dry run',RETRY_REQUESTED:'Remis en file',DEFERRED:'Différé',HEALTHY:'Sain',DEGRADED:'Dégradé',STALE:'Inactif',UNKNOWN:'Inconnu'} as Record<string,string>)[s]||s;}
function date(v:string|null|undefined){return v?new Date(v).toLocaleString('fr-FR'):'—';}
export default async function Page(){const user=await requirePageUser('AGENT');if(!canAccessMarketing(user))redirect('/overview?forbidden=1');const data=await getPublisherControlCenter();const isAdmin=user.role==='ADMIN'||user.role==='SUPER_ADMIN';async function retry(formData:FormData){'use server';const u=await requirePageUser('ADMIN');const id=String(formData.get('itemId')||'');if(id)await retryPublisherItem(id,{id:u.id,username:u.username,role:u.role});revalidatePath('/marketing/publisher-control');}async function savePolicy(formData:FormData){'use server';const u=await requirePageUser('ADMIN');await savePublisherPolicy({globalPause:formData.get('globalPause')==='on',maxPerRun:Number(formData.get('maxPerRun')||20),maxPerHour:Number(formData.get('maxPerHour')||120),maxPerRecipient24h:Number(formData.get('maxPerRecipient24h')||2),quietHoursEnabled:formData.get('quietHoursEnabled')==='on',quietStartHour:Number(formData.get('quietStartHour')||21),quietEndHour:Number(formData.get('quietEndHour')||8),timezone:String(formData.get('timezone')||'America/Mexico_City')},u.id);revalidatePath('/marketing/publisher-control');}
return <DoniShell title="Publisher Control Center" active="/marketing/publisher-control" user={user}>
<section className="workspaceWelcome"><div><span className="workspaceKicker">Marketing V2 · Exécution contrôlée</span><h2>Publisher Control Center</h2><p>Supervision des publications réellement exécutées par le worker. Idempotence, verrou anti-double envoi, limites de débit et retry admin protègent chaque publication.</p></div></section>
<div className="marketingKpis"><div className="card"><span>Santé worker</span><strong>{label(data.health.status)}</strong><small>{data.health.lastRunAt?`Dernier passage ${date(data.health.lastRunAt)}`:'Aucun heartbeat enregistré'}</small></div><div className="card"><span>Envoyés</span><strong>{data.counts.SENT}</strong></div><div className="card"><span>Différés</span><strong>{data.counts.DEFERRED}</strong></div><div className="card"><span>Échecs</span><strong>{data.counts.FAILED}</strong></div><div className="card"><span>Bloqués</span><strong>{data.counts.BLOCKED}</strong></div><div className="card"><span>Dry run</span><strong>{data.counts.DRY_RUN}</strong></div></div>
<section className="card publisherQueue"><div className="searchIntelHead"><div><span>Policy Guard</span><h3>Limites et fenêtre d’envoi</h3></div><small>{data.policy.globalPause?'PAUSE GLOBALE ACTIVE':'Exécution autorisée'}</small></div>{isAdmin?<form action={savePolicy} className="publisherPolicyForm"><label><span>Pause globale</span><input type="checkbox" name="globalPause" defaultChecked={data.policy.globalPause}/></label><label><span>Max / passage</span><input type="number" min="1" max="50" name="maxPerRun" defaultValue={data.policy.maxPerRun}/></label><label><span>Max / heure</span><input type="number" min="1" max="5000" name="maxPerHour" defaultValue={data.policy.maxPerHour}/></label><label><span>Max / destinataire / 24 h</span><input type="number" min="1" max="20" name="maxPerRecipient24h" defaultValue={data.policy.maxPerRecipient24h}/></label><label><span>Heures calmes</span><input type="checkbox" name="quietHoursEnabled" defaultChecked={data.policy.quietHoursEnabled}/></label><label><span>Début</span><input type="number" min="0" max="23" name="quietStartHour" defaultValue={data.policy.quietStartHour}/></label><label><span>Fin</span><input type="number" min="0" max="23" name="quietEndHour" defaultValue={data.policy.quietEndHour}/></label><label><span>Fuseau</span><input type="text" name="timezone" defaultValue={data.policy.timezone}/></label><button className="primaryButton" type="submit">Enregistrer la politique</button></form>:<p className="muted">Seul un administrateur peut modifier la politique d’envoi.</p>}</section>
<section className="card publisherQueue"><div className="searchIntelHead"><div><span>File contrôlée</span><h3>Campagnes et dernier état d’exécution</h3></div><small>Retry manuel admin uniquement pour échec/blocage</small></div><div className="publisherRows">{data.queue.map((x:any)=><article className="publisherRow" key={x.id}><div><span className="publisherStatus">{x.latestEvent?label(x.latestEvent.status):x.status}</span><h4>{x.title}</h4><small>{x.channel||'Canal non défini'} · planifiée {date(x.scheduledFor)}</small></div><div><span>Dernière tentative</span><strong>{x.latestEvent?date(x.latestEvent.at):'Aucune'}</strong><small>{x.latestEvent?.reason||'—'}{x.latestEvent?.retryAfter?` · reprise ${date(x.latestEvent.retryAfter)}`:''}</small></div><div><span>Approbateur</span><strong>{x.approvedBy||'—'}</strong></div><div>{isAdmin&&x.latestEvent&&['FAILED','BLOCKED','DRY_RUN'].includes(x.latestEvent.status)?<form action={retry}><input type="hidden" name="itemId" value={x.id}/><button className="primaryButton" type="submit">Remettre en file</button></form>:null}</div></article>)}</div></section>
<section className="card publisherEvents"><div className="searchIntelHead"><div><span>Audit d'exécution</span><h3>Historique des tentatives</h3></div><small>200 derniers événements · heartbeat système séparé</small></div><div className="publisherEventList">{data.events.map((e:any,i:number)=><div className="publisherEvent" key={`${e.at}-${i}`}><strong>{label(e.status)}</strong><span>{e.itemId}</span><span>{e.channel||'—'}</span><span>{date(e.at)}</span><small>{e.reason||e.actor||e.idempotencyKey||''}{e.retryAfter?` · reprise ${date(e.retryAfter)}`:''}</small></div>)}</div></section>
</DoniShell>}
