import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import {normalizeTicketPayload, type TicketPayload} from './types';
export async function buildEticketPdf(ticket:{reference:string;pnr:string|null;ticketNumber:string|null;issuedAt:Date|null;payload:unknown}){
  const payload=normalizeTicketPayload(ticket.payload) as TicketPayload; const pdf=await PDFDocument.create(); const page=pdf.addPage([595.28,841.89]);
  const regular=await pdf.embedFont(StandardFonts.Helvetica); const bold=await pdf.embedFont(StandardFonts.HelveticaBold);
  const draw=(s:string,x:number,y:number,size=10,b=false)=>page.drawText(s,{x,y,size,font:b?bold:regular,color:rgb(.08,.15,.23)});
  page.drawRectangle({x:0,y:760,width:595.28,height:82,color:rgb(.03,.35,.53)}); draw('DONI TRAVEL',40,804,22,true); page.drawText('E-TICKET / ITINERARY',{x:40,y:780,size:12,font:bold,color:rgb(1,1,1)});
  draw(`Reference: ${ticket.reference}`,40,730,11,true); draw(`PNR: ${ticket.pnr||'-'}`,300,730,11,true); draw(`Ticket: ${ticket.ticketNumber||'-'}`,40,710); draw(`Issued: ${ticket.issuedAt?ticket.issuedAt.toISOString().slice(0,10):'-'}`,300,710);
  let y=665; draw('PASSENGERS',40,y,13,true); y-=24; for(const [i,p] of (payload.passengers||[]).entries()){draw(`${i+1}. ${(p.firstName||'').toUpperCase()} ${(p.lastName||'').toUpperCase()}  ${p.type||''}`,50,y);y-=18;}
  y-=12; draw('ITINERARY',40,y,13,true);y-=24; for(const s of payload.segments||[]){draw(`${s.airline||''} ${s.flightNumber||''}   ${s.origin||'---'} -> ${s.destination||'---'}`,50,y,10,true);y-=17;draw(`${s.departureAt||''}  -  ${s.arrivalAt||''}   ${s.cabin||'Economy'}`,50,y,9);y-=24;}
  if(payload.total){y-=4;draw(`Total: ${payload.total} ${payload.currency||''}`,40,y,12,true);}
  draw('Please verify names, dates and travel documents before departure.',40,70,9); draw('Generated by DONI Travel',40,50,8);
  return Buffer.from(await pdf.save());
}
