import { PDFDocument, StandardFonts, rgb, type PDFPage, type PDFFont } from 'pdf-lib';
import {normalizeTicketPayload, type TicketPayload, type TicketSegment} from './types';

const NAVY=rgb(.02,.16,.31), BLUE=rgb(.03,.35,.53), LIGHT=rgb(.95,.97,.99), TEXT=rgb(.08,.15,.23), MUTED=rgb(.36,.43,.51), BORDER=rgb(.78,.85,.91);
const fmt=(v?:string)=>{if(!v)return '-';const d=new Date(v);if(Number.isNaN(d.getTime()))return v;return d.toISOString().replace('T',' ').slice(0,16)};

export async function buildEticketPdf(ticket:{reference:string;pnr:string|null;ticketNumber:string|null;issuedAt:Date|null;payload:unknown}){
  const payload=normalizeTicketPayload(ticket.payload) as TicketPayload;
  const pdf=await PDFDocument.create();
  const regular=await pdf.embedFont(StandardFonts.Helvetica);
  const bold=await pdf.embedFont(StandardFonts.HelveticaBold);
  const page=pdf.addPage([595.28,841.89]);
  drawHeader(page,bold);
  const draw=(s:string,x:number,y:number,size=10,b=false,color=TEXT)=>page.drawText(s,{x,y,size,font:b?bold:regular,color});

  page.drawRectangle({x:34,y:685,width:527,height:58,color:LIGHT,borderColor:BORDER,borderWidth:.8});
  draw('Reference',50,724,8,false,MUTED); draw(ticket.reference,50,706,11,true);
  draw('Ticket',305,724,8,false,MUTED); draw(ticket.ticketNumber||'-',305,706,11,true);
  draw('Issued',50,693,8,false,MUTED); draw(ticket.issuedAt?ticket.issuedAt.toISOString().slice(0,10):'-',98,693,9,true);
  draw('Segments',305,693,8,false,MUTED); draw(String(payload.segments?.length||0),355,693,9,true);

  let y=650;
  drawSectionTitle(page,bold,'PASSENGERS',y); y-=30;
  for(const [i,p] of (payload.passengers||[]).entries()){
    page.drawRectangle({x:50,y:y-7,width:495,height:26,color:LIGHT,borderColor:BORDER,borderWidth:.5});
    draw(`${i+1}. ${(p.firstName||'').toUpperCase()} ${(p.lastName||'').toUpperCase()}`,62,y,10,true);
    draw(String(p.type||'Adult'),390,y,9,false,MUTED); y-=34;
  }

  y-=4; drawSectionTitle(page,bold,'ITINERARY',y); y-=20;
  for(const [i,s] of (payload.segments||[]).entries()){
    y=drawSegmentCard(page,regular,bold,s,i+1,y,ticket.pnr||undefined);
  }

  if(payload.total){
    y-=4; page.drawRectangle({x:45,y:y-43,width:505,height:48,color:LIGHT,borderColor:NAVY,borderWidth:1.2});
    draw('TOTAL',65,y-14,10,true,MUTED); draw(`${payload.total} ${payload.currency||''}`,160,y-20,22,true,NAVY); y-=58;
  }

  draw('Please verify names, dates and travel documents before departure.',45,60,8,false,MUTED);
  draw('Generated by DONI Travel',45,43,8,true,NAVY);
  page.drawRectangle({x:0,y:0,width:595.28,height:18,color:NAVY});
  return Buffer.from(await pdf.save());
}

function drawHeader(page:PDFPage,bold:PDFFont){
  page.drawRectangle({x:0,y:760,width:595.28,height:82,color:NAVY});
  page.drawRectangle({x:0,y:756,width:595.28,height:4,color:BLUE});
  page.drawText('DONI TRAVEL',{x:40,y:805,size:24,font:bold,color:rgb(1,1,1)});
  page.drawText('E-TICKET / ITINERARY RECEIPT',{x:40,y:781,size:11,font:bold,color:rgb(.78,.91,1)});
}

function drawSectionTitle(page:PDFPage,bold:PDFFont,title:string,y:number){
  page.drawText(title,{x:45,y,size:12,font:bold,color:NAVY});
  page.drawLine({start:{x:145,y:y+3},end:{x:550,y:y+3},thickness:1,color:BLUE});
}

function drawSegmentCard(page:PDFPage,regular:PDFFont,bold:PDFFont,s:TicketSegment,index:number,y:number,globalPnr?:string){
  const x=45,w=505,h=88,top=y;
  const pnr=String(s.pnr||s.bookingReference||globalPnr||'-').toUpperCase();
  page.drawRectangle({x,y:top-h,width:w,height:h,color:rgb(1,1,1),borderColor:BORDER,borderWidth:.9});
  page.drawRectangle({x,y:top-22,width:95,height:22,color:NAVY});
  page.drawText(`SEGMENT ${index}`,{x:x+12,y:top-15,size:9,font:bold,color:rgb(1,1,1)});
  page.drawText(`PNR: ${pnr}`,{x:x+365,y:top-15,size:10,font:bold,color:NAVY});

  const airline=`${s.airline||''} ${s.flightNumber||''}`.trim()||'Flight';
  page.drawText(airline,{x:x+15,y:top-48,size:11,font:bold,color:NAVY});
  page.drawText(`${s.origin||'---'}  ->  ${s.destination||'---'}`,{x:x+125,y:top-48,size:14,font:bold,color:TEXT});
  page.drawText(String(s.cabin||'Economy'),{x:x+420,y:top-48,size:9,font:bold,color:NAVY});
  page.drawText('DEPART',{x:x+125,y:top-66,size:7,font:bold,color:MUTED});
  page.drawText(fmt(s.departureAt),{x:x+170,y:top-66,size:8,font:regular,color:TEXT});
  page.drawText('ARRIVE',{x:x+315,y:top-66,size:7,font:bold,color:MUTED});
  page.drawText(fmt(s.arrivalAt),{x:x+355,y:top-66,size:8,font:regular,color:TEXT});
  page.drawText(`PNR ${pnr}`,{x:x+15,y:top-78,size:8,font:bold,color:BLUE});
  return top-h-12;
}
