import {redirect} from 'next/navigation';
import {DoniShell} from '@/components/DoniShell';
import {requirePageUser} from '@/lib/auth/session';
import {hasRole} from '@/lib/auth/permissions';
import {getMarketingWorkCenter} from '@/services/workspace/work-centers';
import {MetricCard} from '@/components/analytics/MetricCard';
import {WorkCenterHeader,WorkQueue} from '@/components/workspace/WorkQueue';
export const dynamic='force-dynamic';
export default async function MarketingPage(){const user=await requirePageUser('AGENT');if(!hasRole(user.role,'ADMIN')&&user.department!=='MARKETING')redirect('/overview?forbidden=1');const d=await getMarketingWorkCenter();return <DoniShell title="Centre marketing" active="/marketing" user={user}><WorkCenterHeader kicker="Marketing & croissance" title="Acquisition, audiences et conversion" description="Utiliser les données clients et le funnel réel de DONI pour prioriser les campagnes et opportunités commerciales." actions={[{label:'Clients / CRM',href:'/customers'},{label:'Parcours client',href:'/flow-tracker'}]}/><div className="grid"><MetricCard label="Nouveaux clients · 7 j" value={d.newCustomers}/><MetricCard label="Conversations démarrées · 24 h" value={d.started}/><MetricCard label="Paiements · 24 h" value={d.paid} tone={d.paid?'good':'default'}/><MetricCard label="Conversion paiement" value={`${d.conversion}%`} tone={d.conversion>=20?'good':d.conversion>0?'warn':'default'}/></div><div className="workCenterGrid"><WorkQueue title="Audiences actives" note="Nouveaux clients par pays sur 7 jours" items={d.topCountries.map((x,i)=>({key:`${x.country}-${i}`,title:x.country,meta:`${x.count} nouveau(x) client(s)`,href:'/customers',badge:String(x.count)}))}/><WorkQueue title="Clients récents" note="À segmenter ou réengager" items={d.recentCustomers.map(x=>({key:x.customerCode,title:x.displayName||x.customerCode,meta:`${x.country||'Pays inconnu'} · ${x.preferredLanguage||'langue inconnue'} · ${new Date(x.lastSeenAt).toLocaleString('fr-FR')}`,href:'/customers',badge:'CRM'}))}/></div><h2 className="sectionTitle">Outils marketing</h2><div className="marketingGrid"><div className="card marketingModule"><span className="moduleIcon">◎</span><strong>Campagnes</strong><p>Préparer les campagnes WhatsApp, e-mail et publicitaires à partir des segments CRM.</p><span className="badge warn">Prochaine étape</span></div><div className="card marketingModule"><span className="moduleIcon">↗</span><strong>Leads & audiences</strong><p>Segmenter les prospects et clients selon pays, langue, destination et historique.</p><span className="badge ok">Données connectées</span></div><div className="card marketingModule"><span className="moduleIcon">▥</span><strong>Contenu</strong><p>Organiser offres, promotions, messages et calendrier de publication.</p><span className="badge warn">À connecter</span></div><div className="card marketingModule"><span className="moduleIcon">%</span><strong>Performance</strong><p>Suivre les démarrages, paiements et conversion du funnel DONI.</p><span className="badge ok">Mesure active</span></div></div></DoniShell>}
