import {redirect} from 'next/navigation';
import {revalidatePath} from 'next/cache';
import {DoniShell} from '@/components/DoniShell';
import {requirePageUser} from '@/lib/auth/session';
import {canAccessMarketing} from '@/lib/auth/marketing-access';
import {getMarketingConsentDashboard,setMarketingConsent,setMarketingConsentPolicy,type MarketingConsentStatus} from '@/lib/workspace/marketing-consent';
export const dynamic='force-dynamic';
function date(v:string|null|undefined){return v?new Date(v).toLocaleString('fr-FR'):'—';}
function label(s:string){return({OPTED_IN:'Autorisé',OPTED_OUT:'Désinscrit',UNKNOWN:'Inconnu'} as Record<string,string>)[s]||s;}
export default async function Page(){const user=await requirePageUser('AGENT');if(!canAccessMarketing(user))redirect('/overview?forbidden=1');const data=await getMarketingConsentDashboard();const isAdmin=user.role==='ADMIN'||user.role==='SUPER_ADMIN';async function savePolicy(formData:FormData){'use server';const u=await requirePageUser('ADMIN');await setMarketingConsentPolicy(formData.get('requireExplicitConsent')==='on',u.id);revalidatePath('/marketing/consent');}async function setConsent(formData:FormData){'use server';const u=await requirePageUser('ADMIN');const recipient=String(formData.get('recipient')||'');const status=String(formData.get('status')||'UNKNOWN') as MarketingConsentStatus;if(recipient&&['OPTED_IN','OPTED_OUT','UNKNOWN'].includes(status))await setMarketingConsent(recipient,status,{source:'ADMIN',updatedBy:u.username,reason:'manual_update'});revalidatePath('/marketing/consent');}
return <DoniShell title="Consent & Opt-out" active="/marketing/consent" user={user}>
<section className="workspaceWelcome"><div><span className="workspaceKicker">Marketing V2 · Compliance</span><h2>Consent & Opt-out</h2><p>Registre de préférences marketing. Un contact désinscrit est bloqué avant toute livraison, même si sa campagne est déjà approuvée et planifiée.</p></div></section>
<div className="marketingKpis"><div className="card"><span>Autorisés</span><strong>{data.counts.OPTED_IN}</strong></div><div className="card"><span>Désinscrits</span><strong>{data.counts.OPTED_OUT}</strong></div><div className="card"><span>Mode strict</span><strong>{data.policy.requireExplicitConsent?'ACTIF':'OFF'}</strong><small>{data.policy.requireExplicitConsent?'Seuls OPTED_IN peuvent recevoir':'UNKNOWN reste autorisé, OPTED_OUT bloqué'}</small></div></div>
<section className="card consentControls"><div className="searchIntelHead"><div><span>Politique</span><h3>Consentement explicite</h3></div><small>ADMIN / SUPER_ADMIN</small></div>{isAdmin?<><form action={savePolicy} className="consentPolicyForm"><label><input type="checkbox" name="requireExplicitConsent" defaultChecked={data.policy.requireExplicitConsent}/><span>Exiger OPTED_IN avant toute campagne marketing</span></label><button className="primaryButton" type="submit">Enregistrer</button></form><form action={setConsent} className="consentManualForm"><input name="recipient" placeholder="Téléphone / WhatsApp" required/><select name="status" defaultValue="OPTED_IN"><option value="OPTED_IN">Autoriser</option><option value="OPTED_OUT">Désinscrire</option><option value="UNKNOWN">Réinitialiser à inconnu</option></select><button className="primaryButton" type="submit">Mettre à jour</button></form></>:<p className="muted">Seul un administrateur peut modifier les préférences.</p>}</section>
<section className="card consentRegistry"><div className="searchIntelHead"><div><span>Registre</span><h3>Préférences enregistrées</h3></div><small>{data.records.length} contacts</small></div><div className="consentRows">{data.records.length?data.records.map(x=><article className="consentRow" key={x.recipient}><strong>{x.recipient}</strong><span>{label(x.status)}</span><span>{x.source}</span><span>{date(x.updatedAt)}</span><small>{x.reason||'—'}</small></article>):<p className="muted">Aucune préférence marketing enregistrée pour le moment.</p>}</div></section>
<section className="card consentRegistry"><div className="searchIntelHead"><div><span>Audit</span><h3>Historique des changements</h3></div><small>200 derniers événements</small></div><div className="consentRows">{data.events.map((e:any,i:number)=><article className="consentRow" key={`${e.at}-${i}`}><strong>{e.recipient}</strong><span>{label(e.previous)} → {label(e.status)}</span><span>{e.source}</span><span>{date(e.at)}</span><small>{e.updatedBy||e.reason||'—'}</small></article>)}</div></section>
</DoniShell>}
