import Link from 'next/link';
import {notFound} from 'next/navigation';
import {DoniShell} from '@/components/DoniShell';
import {CaseWorkspacePanel} from '@/components/workspace/CaseWorkspacePanel';
import {requirePageUser} from '@/lib/auth/session';
import {getCase360,type CaseKind} from '@/services/workspace/case-360';
export const dynamic='force-dynamic';
const kinds=['CLIENT','PAYMENT','TICKET','POST_BOOKING','FLIGHT','TASK'] as const;
function validKind(v:string):v is CaseKind{return (kinds as readonly string[]).includes(v)}
function fmt(v:any){return v?new Date(v).toLocaleString('fr-FR'):'—'}
function statusClass(v:any){const s=String(v||'').toLowerCase();return s.includes('fail')||s.includes('cancel')||s.includes('critical')||s.includes('blocked')?'badBadge':s.includes('pending')||s.includes('wait')||s.includes('delay')||s.includes('open')?'warn':'ok'}
export default async function Page({params}:{params:Promise<{kind:string;id:string}>}){const user=await requirePageUser('AGENT');const {kind,id}=await params;if(!validKind(kind))notFound();const d:any=await getCase360(kind,id,user);if(!d)notFound();const title=d.ticket?.reference||d.payment?.reference||d.post?.reference||d.client?.displayName||d.client?.customerCode||d.flight?.ticketReference||'Dossier';return <DoniShell title="Dossier 360°" active="" user={user}>
<section className="caseHero"><div><span className="workspaceKicker">Vue consolidée</span><h2>{title}</h2><p>{d.client?.displayName||d.client?.customerCode||'Client non identifié'}{d.client?.phone?` · ${d.client.phone}`:''}{d.ticket?.pnr?` · PNR ${d.ticket.pnr}`:''}</p></div><div className="caseHeroActions"><Link className="btn" href="/tasks">Tâches</Link>{d.ticket?<Link className="btn" href={`/ticketing?focus=${encodeURIComponent(d.ticket.id)}`}>Ticketing</Link>:null}{d.flight?<Link className="btn" href={`/flight-ops?focus=${encodeURIComponent(d.flight.id)}`}>Flight Ops</Link>:null}{d.post?<Link className="btn" href={`/post-booking?focus=${encodeURIComponent(d.post.id)}`}>Après-vente</Link>:null}</div></section>
<div className="caseSummaryGrid">
 <div className="card caseSummary"><span>Client</span><strong>{d.client?.displayName||d.client?.customerCode||'—'}</strong><small>{d.client?.phone||'—'} · {d.client?.email||'Sans email'} · {d.client?.country||'Pays —'}</small></div>
 <div className="card caseSummary"><span>Paiement</span><strong>{d.payment?.reference||'—'}</strong><small>{d.payment?`${Number(d.payment.amount).toFixed(2)} ${d.payment.currency} · ${d.payment.status}`:'Aucun paiement lié'}</small></div>
 <div className="card caseSummary"><span>Billet / PNR</span><strong>{d.ticket?.reference||'—'}</strong><small>{d.ticket?`${d.ticket.pnr||'PNR —'} · ${d.ticket.ticketNumber||'Ticket —'} · ${d.ticket.status}`:'Aucun billet lié'}</small></div>
 <div className="card caseSummary"><span>Flight Ops</span><strong>{d.flight?`${d.flight.airlineCode}${d.flight.flightNumber}`:'—'}</strong><small>{d.flight?`${d.flight.origin}→${d.flight.destination} · ${d.flight.flightStatus}`:'Aucun suivi actif'}</small></div>
</div>
<CaseWorkspacePanel kind={kind} id={id}/>
<div className="caseMainGrid"><section><h2 className="sectionTitle">Parcours du dossier</h2><div className="card caseTimeline">{d.timeline.map((x:any,i:number)=><div className="caseTimelineRow" key={`${x.at}-${i}`}><div className="caseTimelineDot"/><div><div className="caseTimelineTop"><strong>{x.title}</strong><span>{fmt(x.at)}</span></div><small>{x.type}{x.detail?` · ${x.detail}`:''}</small></div></div>)}{!d.timeline.length?<div className="emptyState">Aucun événement disponible.</div>:null}</div></section>
<aside className="caseSide"><h2 className="sectionTitle">Actions & risques</h2><div className="card casePanel"><div className="casePanelTitle">Tâches actives <b>{d.tasks.filter((t:any)=>t.status!=='DONE').length}</b></div>{d.tasks.filter((t:any)=>t.status!=='DONE').slice(0,8).map((t:any)=><Link href={`/tasks?focus=${encodeURIComponent(t.id)}`} className="caseMiniRow" key={t.id}><div><strong>{t.title}</strong><small>{t.assigneeName||'Non assignée'} · {t.department}</small></div><span className={`badge ${t.priority==='URGENT'?'badBadge':t.priority==='HIGH'?'warn':'ok'}`}>{t.priority}</span></Link>)}{!d.tasks.filter((t:any)=>t.status!=='DONE').length?<div className="emptyState">Aucune tâche active.</div>:null}</div>
<div className="card casePanel"><div className="casePanelTitle">Incidents Flight Ops <b>{d.incidents.length}</b></div>{d.incidents.slice(0,6).map((x:any)=><div className="caseMiniRow" key={x.id}><div><strong>{x.title}</strong><small>{x.incidentType} · {fmt(x.createdAt)}</small></div><span className={`badge ${statusClass(x.severity)}`}>{x.status}</span></div>)}{!d.incidents.length?<div className="emptyState">Aucun incident lié.</div>:null}</div></aside></div>
<h2 className="sectionTitle">Données liées</h2><div className="caseDataGrid"><div className="card casePanel"><div className="casePanelTitle">Paiements <b>{d.payments.length}</b></div>{d.payments.map((p:any)=><div className="caseDataRow" key={p.id}><div><strong>{p.reference}</strong><small>{p.provider} · {Number(p.amount).toFixed(2)} {p.currency}</small></div><span className={`badge ${statusClass(p.status)}`}>{p.status}</span></div>)}</div><div className="card casePanel"><div className="casePanelTitle">Billets <b>{d.tickets.length}</b></div>{d.tickets.map((t:any)=><div className="caseDataRow" key={t.id}><div><strong>{t.reference}</strong><small>{t.pnr||'PNR —'} · {t.ticketNumber||'Ticket —'}</small></div><span className={`badge ${statusClass(t.status)}`}>{t.status}</span></div>)}</div><div className="card casePanel"><div className="casePanelTitle">Après-vente <b>{d.postRequests.length}</b></div>{d.postRequests.map((p:any)=><div className="caseDataRow" key={p.id}><div><strong>{p.reference}</strong><small>{p.requestType}</small></div><span className={`badge ${statusClass(p.status)}`}>{p.status}</span></div>)}</div><div className="card casePanel"><div className="casePanelTitle">Remboursements <b>{d.refunds.length}</b></div>{d.refunds.map((r:any)=><div className="caseDataRow" key={r.id}><div><strong>{Number(r.amount).toFixed(2)} {r.currency}</strong><small>{r.reason||'Remboursement'}</small></div><span className={`badge ${statusClass(r.status)}`}>{r.status}</span></div>)}</div></div>
</DoniShell>}
