import {redirect} from 'next/navigation';
import Link from 'next/link';
import {DoniShell} from '@/components/DoniShell';
import {requirePageUser} from '@/lib/auth/session';
import {hasRole} from '@/lib/auth/permissions';
import {getMarketingPerformance} from '@/services/workspace/marketing-performance';
export const dynamic='force-dynamic';
function money(v:number|null){return v==null?'—':v.toFixed(2)}
export default async function Page(){const user=await requirePageUser('AGENT');if(!hasRole(user.role,'ADMIN')&&user.department!=='MARKETING')redirect('/overview?forbidden=1');const d=await getMarketingPerformance();return <DoniShell title="Performance Marketing" active="/marketing/performance" user={user}><section className="mkPerfHero"><div><span className="workspaceKicker">Mesure & rentabilité</span><h2>Performance des campagnes</h2><p>Comparer les dépenses, leads, ventes et revenus attribués avant de réallouer le budget.</p></div><Link href="/marketing/campaigns" className="btn primary">Gérer les campagnes</Link></section><div className="mkPerfSummary"><div className="card"><span>Dépenses</span><strong>{money(d.totals.spend)}</strong></div><div className="card"><span>Leads</span><strong>{d.totals.leads}</strong></div><div className="card"><span>Ventes</span><strong>{d.totals.sales}</strong></div><div className="card"><span>CPL moyen</span><strong>{money(d.totals.cpl)}</strong></div><div className="card"><span>CAC moyen</span><strong>{money(d.totals.cac)}</strong></div><div className="card"><span>ROAS</span><strong>{d.totals.roas==null?'—':`${d.totals.roas.toFixed(2)}x`}</strong></div><div className="card"><span>ROI</span><strong>{d.totals.roi==null?'—':`${d.totals.roi.toFixed(1)}%`}</strong></div></div><div className="card tableWrap"><table className="table"><thead><tr><th>Campagne</th><th>Canal</th><th>Dépensé</th><th>Leads</th><th>Ventes</th><th>CPL</th><th>CAC</th><th>ROAS</th><th>ROI</th></tr></thead><tbody>{d.rows.map(c=><tr key={c.id}><td><strong>{c.name}</strong><div className="muted">{c.destination||'Offre générale'}</div></td><td>{c.channel}</td><td>{money(c.spend)} {c.currency}</td><td>{c.leads}</td><td>{c.sales}</td><td>{money(c.metrics.cpl)}</td><td>{money(c.metrics.cac)}</td><td>{c.metrics.roas==null?'—':`${c.metrics.roas.toFixed(2)}x`}</td><td>{c.metrics.roi==null?'—':`${c.metrics.roi.toFixed(1)}%`}</td></tr>)}{!d.rows.length?<tr><td colSpan={9} className="muted">Aucune campagne mesurée.</td></tr>:null}</tbody></table></div></DoniShell>}
