'use client';
import {useEffect,useMemo,useState} from 'react';
type Item={key:string;category:string;label:string;description?:string;type:string;value?:any;configured:boolean;source:string;secretStored:boolean;options?:string[];min?:number;max?:number};
const integrations=[['Duffel','duffel'],['WhatsApp Meta','whatsapp'],['Stripe','stripe'],['Mercado Pago','mercadopago'],['PayPal','paypal'],['Brevo','brevo']] as const;
export function SettingsCenter(){const [items,setItems]=useState<Item[]>([]);const [canSecrets,setCanSecrets]=useState(false);const [msg,setMsg]=useState('');const [busy,setBusy]=useState('');
 async function load(){const r=await fetch('/api/settings',{cache:'no-store'});const j=await r.json();if(j.success){setItems(j.settings);setCanSecrets(!!j.canEditSecrets)}}
 useEffect(()=>{load()},[]);
 const groups=useMemo(()=>Object.entries(items.reduce((a:any,x)=>{(a[x.category]??=[]).push(x);return a},{})),[items]);
 function updateLocal(key:string,value:any){setItems(xs=>xs.map(x=>x.key===key?{...x,value}:x))}
 async function save(x:Item){setBusy(x.key);setMsg('');const r=await fetch('/api/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({key:x.key,value:x.value})});const j=await r.json();setBusy('');setMsg(j.success?`✓ ${x.label} enregistré`:`Erreur: ${j.error}`);if(j.success)await load()}
 async function clear(x:Item){setBusy(x.key);const r=await fetch('/api/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({key:x.key,clear:true})});const j=await r.json();setBusy('');setMsg(j.success?`✓ ${x.label}: fallback Vercel réactivé`:`Erreur: ${j.error}`);if(j.success)await load()}
 async function testIntegration(name:string){setBusy(`test-${name}`);setMsg('');const r=await fetch('/api/settings/test',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({integration:name})});const j=await r.json();setBusy('');setMsg(j.success?(j.result.ok?'✓ ':'⚠ ')+j.result.message:`Erreur: ${j.error}`)}
 return <div className="settingsStack">{msg&&<div className="settingsMessage">{msg}</div>}{canSecrets&&<section className="card"><div className="settingsHead"><div><h2>Diagnostics intégrations</h2><p className="muted">Tests de connexion uniquement. Aucun paiement ni réservation n’est créé.</p></div></div><div className="integrationGrid">{integrations.map(([label,name])=><button className="btn" key={name} disabled={!!busy} onClick={()=>testIntegration(name)}>{busy===`test-${name}`?'Test...':`Tester ${label}`}</button>)}</div></section>}{groups.map(([cat,rows]:any)=><section className="card" key={cat}><div className="settingsHead"><div><h2>{cat}</h2><p className="muted">Configuration opérationnelle et intégrations.</p></div></div><div className="settingsGrid">{rows.map((x:Item)=><div className="settingRow" key={x.key}><div className="settingInfo"><strong>{x.label}</strong><span>{x.description||x.key}</span><small>Source: {x.source} · {x.configured?'configuré':'manquant'}</small></div><div className="settingControl">{x.type==='boolean'?<label className="switchLine"><input type="checkbox" checked={!!x.value} onChange={e=>updateLocal(x.key,e.target.checked)}/><span>{x.value?'Activé':'Désactivé'}</span></label>:x.type==='select'?<select value={x.value??''} onChange={e=>updateLocal(x.key,e.target.value)}>{x.options?.map(o=><option key={o}>{o}</option>)}</select>:<input type={x.type==='secret'?'password':x.type==='number'?'number':'text'} min={x.min} max={x.max} value={x.value??''} disabled={x.type==='secret'&&!canSecrets} placeholder={x.type==='secret'?(x.configured?'•••••••• configuré':'Entrer le secret'):''} onChange={e=>updateLocal(x.key,x.type==='number'?Number(e.target.value):e.target.value)}/>}<div className="settingButtons"><button className="btn primary" disabled={busy===x.key||(x.type==='secret'&&!canSecrets)||(x.type==='secret'&&!x.value)} onClick={()=>save(x)}>{busy===x.key?'...':'Enregistrer'}</button>{x.source==='database'&&(x.type!=='secret'||canSecrets)&&<button className="btn" disabled={busy===x.key} onClick={()=>clear(x)}>Utiliser fallback</button>}</div></div></div>)}</div></section>)}</div>}
