import {db} from '../../lib/db'; import {deepMerge} from './state'; import {segmentExists} from '../segments/registry'; import type {ConversationSession, JsonObject, DoniLanguage} from './types';import {getSetting} from '@/lib/settings/service';
export const INITIAL_SEGMENT='segment_language';
function hydrate(row:any):ConversationSession{return {id:row.id,waId:row.waId,country:row.country??null,businessSegment:row.businessSegment??'flights',lockedLanguage:row.lockedLanguage??null,currentSegment:row.currentSegment??INITIAL_SEGMENT,previousSegment:row.previousSegment??null,state:(row.state??{}) as JsonObject,status:row.status??'ACTIVE',agentRequired:!!row.agentRequired,lastMessageAt:row.lastMessageAt??null,createdAt:row.createdAt,updatedAt:row.updatedAt};}
async function staleReason(s:ConversationSession){if(!segmentExists(s.currentSegment))return'unknown_segment';const t=s.lastMessageAt?.getTime(),hours=Number(await getSetting<number>('conversation.stale_hours'))||72;if(t&&Date.now()-t>hours*3600_000)return`stale_${hours}h`;return null;}
export async function inactivityResetMinutes(){return Number(await getSetting<number>('conversation.inactivity_reset_minutes'))||30;}
export async function loadOrCreateSession(waId:string){let row=await db.doniConversation.findFirst({where:{waId,status:{in:['ACTIVE','PAUSED','AGENT_HOLD']}},orderBy:{updatedAt:'desc'}});if(!row){row=await db.doniConversation.create({data:{waId,currentSegment:INITIAL_SEGMENT,businessSegment:'flights',state:{},status:'ACTIVE',lastMessageAt:new Date()}});}let s=hydrate(row);const reason=await staleReason(s);if(reason){row=await db.doniConversation.update({where:{id:s.id},data:{previousSegment:s.currentSegment,currentSegment:INITIAL_SEGMENT,state:{reset_reason:reason},lastMessageAt:new Date()}});s=hydrate(row);}return s;}
export async function persistReply(session:ConversationSession,nextSegment:string|null,stateUpdates:JsonObject|null|undefined){let state=session.state;if(stateUpdates)state=deepMerge(state,stateUpdates);const locked=(state.locked_language as DoniLanguage|undefined)??session.lockedLanguage,business=(state.business_segment as string|undefined)??session.businessSegment,current=nextSegment??session.currentSegment;const data={previousSegment:nextSegment?session.currentSegment:session.previousSegment,currentSegment:current,state:state as any,lockedLanguage:locked,businessSegment:business,lastMessageAt:new Date(),agentRequired:Boolean(state.requires_human_review??session.agentRequired)};const result=await db.doniConversation.updateMany({where:{id:session.id,currentSegment:session.currentSegment},data});if(result.count!==1)throw new Error('conversation_state_conflict');const row=await db.doniConversation.findUnique({where:{id:session.id}});if(!row)throw new Error('conversation_not_found');return hydrate(row);}
export function inactivityMinutes(session:ConversationSession){if(!session.lastMessageAt)return 0;return Math.floor((Date.now()-session.lastMessageAt.getTime())/60000);}
export async function resetAfterInactivity(session:ConversationSession){const archived={...(session.state.archived_context as JsonObject??{}),last_reset_at:new Date().toISOString(),last_reset_reason:'inactivity',last_business_segment:session.businessSegment};const row=await db.doniConversation.update({where:{id:session.id},data:{previousSegment:session.currentSegment,currentSegment:'segment_service_selection',businessSegment:'flights',state:{archived_context:archived,service_awaiting:true},lastMessageAt:new Date()}});return hydrate(row);}
