export type SettingType='boolean'|'number'|'text'|'secret'|'select';
export type SettingDefinition={key:string;category:string;label:string;description?:string;type:SettingType;env?:string;default?:string|number|boolean;options?:string[];min?:number;max?:number};
export const SETTINGS:SettingDefinition[]=[
 {key:'whatsapp.enabled',category:'WhatsApp',label:'Envoi WhatsApp actif',type:'boolean',env:'WHATSAPP_SEND_ENABLED',default:false,description:'Désactivé = réception et simulation seulement.'},
 {key:'whatsapp.access_token',category:'WhatsApp',label:'Meta access token',type:'secret',env:'META_WHATSAPP_ACCESS_TOKEN'},
 {key:'whatsapp.phone_number_id',category:'WhatsApp',label:'Phone Number ID',type:'secret',env:'META_WHATSAPP_PHONE_NUMBER_ID'},
 {key:'whatsapp.verify_token',category:'WhatsApp',label:'Webhook verify token',type:'secret',env:'META_WHATSAPP_VERIFY_TOKEN'},
 {key:'facebook.enabled',category:'Facebook',label:'Publication Facebook active',type:'boolean',env:'FACEBOOK_PUBLISH_ENABLED',default:false,description:'Autorise uniquement les publications organiques approuvées. Aucune dépense publicitaire automatique.'},
 {key:'facebook.page_id',category:'Facebook',label:'Facebook Page ID',type:'text',env:'FACEBOOK_PAGE_ID'},
 {key:'facebook.page_access_token',category:'Facebook',label:'Facebook Page Access Token',type:'secret',env:'FACEBOOK_PAGE_ACCESS_TOKEN'},
 {key:'facebook.graph_version',category:'Facebook',label:'Meta Graph API version',type:'text',env:'FACEBOOK_GRAPH_VERSION',default:'v23.0'},
 {key:'facebook.whatsapp_number',category:'Facebook',label:'Numéro WhatsApp public',type:'text',env:'FACEBOOK_WHATSAPP_NUMBER',description:'Numéro international sans + utilisé pour le lien wa.me tracké dans les publications.'},
 {key:'flights.duffel_enabled',category:'Flights',label:'Duffel search actif',type:'boolean',env:'DUFFEL_SEARCH_ENABLED',default:false},
 {key:'flights.duffel_reprice_enabled',category:'Flights',label:'Duffel repricing actif',type:'boolean',env:'DUFFEL_REPRICE_ENABLED',default:false},
 {key:'flights.duffel_access_token',category:'Flights',label:'Duffel access token',type:'secret',env:'DUFFEL_ACCESS_TOKEN'},
 {key:'flights.provider_priority',category:'Flights',label:'Ordre des fournisseurs',type:'text',env:'FLIGHT_PROVIDER_PRIORITY',default:'duffel,manual_inventory,google_fallback,agent_quote'},
 {key:'flights.pkfare_enabled',category:'Flights',label:'PKFARE actif',type:'boolean',default:false},
 {key:'flights.pkfare_api_key',category:'Flights',label:'PKFARE API key',type:'secret',env:'PKFARE_API_KEY'},
 {key:'flights.google_fallback_enabled',category:'Flights',label:'Google Flights fallback actif',type:'boolean',env:'GOOGLE_FLIGHTS_FALLBACK_ENABLED',default:false},
 {key:'flights.rapidapi_key',category:'Flights',label:'RapidAPI Google Flights key',type:'secret',env:'RAPIDAPI_KEY'},
 {key:'flights.manual_inventory_enabled',category:'Flights',label:'Inventaire manuel actif',type:'boolean',env:'MANUAL_INVENTORY_ENABLED',default:true},
 {key:'tracking.alerts_enabled',category:'Flight Tracking',label:'Alertes automatiques actives',type:'boolean',env:'FLIGHT_ALERTS_ENABLED',default:false,description:'Autorise le traitement des alertes. L’envoi automatique reste protégé par un gate séparé.'},
 {key:'tracking.disruption_alerts_enabled',category:'Flight Tracking',label:'Alertes retard / annulation / déroutement',type:'boolean',env:'FLIGHT_DISRUPTION_ALERTS_ENABLED',default:false,description:'Autorise la création des alertes de perturbation détectées par le provider.'},
 {key:'tracking.auto_send_enabled',category:'Flight Tracking',label:'Envoi automatique des alertes',type:'boolean',env:'FLIGHT_AUTO_SEND_ENABLED',default:false,description:'Autorise la livraison automatique des alertes éligibles. Laisser OFF tant que la production n’est pas validée.'},
 {key:'tracking.standard_alerts_enabled',category:'Flight Tracking',label:'Rappels standards 48h / check-in / boarding',type:'boolean',env:'FLIGHT_STANDARD_ALERTS_ENABLED',default:false,description:'OFF = seuls les événements disruption:* peuvent être livrés automatiquement.'},
 {key:'tracking.test_alert_enabled',category:'Flight Tracking',label:'Test contrôlé des alertes',type:'boolean',default:false,description:'Autorise uniquement l’envoi d’une alerte de test par SUPER_ADMIN. Laisser désactivé hors test.'},
 {key:'tracking.test_poll_enabled',category:'Flight Tracking',label:'Polling FlightAware contrôlé',type:'boolean',default:false,description:'Autorise un polling réel ciblé par SUPER_ADMIN. Ne jamais laisser activé hors fenêtre de validation.'},
 {key:'tracking.test_delivery_enabled',category:'Flight Tracking',label:'Livraison perturbation ciblée TEST',type:'boolean',default:false,description:'Autorise uniquement la livraison disruption:* ciblée par référence via SUPER_ADMIN. Laisser OFF hors validation.'},
 {key:'tracking.oag_testing_enabled',category:'Flight Tracking',label:'OAG test/ops actif',type:'boolean',env:'OAG_TESTING_ENABLED',default:false},
 {key:'tracking.oag_secondary_api_key',category:'Flight Tracking',label:'OAG secondary key',type:'secret',env:'OAG_SECONDARY_API_KEY'},
 {key:'tracking.checkin_assistance_price',category:'Flight Tracking',label:'Prix assistance check-in (USD)',type:'number',default:5,min:0,max:100},
 {key:'tracking.enabled',category:'Flight Tracking',label:'Provider de suivi actif',type:'boolean',default:false,description:'Autorise l’utilisation du provider de tracking. Le cron automatique reste séparé.'},
 {key:'tracking.auto_poll_enabled',category:'Flight Tracking',label:'Polling automatique actif',type:'boolean',env:'FLIGHT_AUTO_POLL_ENABLED',default:false,description:'Autorise le cron Flight Ops à interroger automatiquement uniquement les vols dans la fenêtre de suivi.'},
 {key:'tracking.flightaware_api_key',category:'Flight Tracking',label:'FlightAware API key',type:'secret',env:'FLIGHTAWARE_API_KEY'},
 {key:'tracking.oag_api_key',category:'Flight Tracking',label:'OAG API key',type:'secret',env:'OAG_API_KEY'},
 {key:'payments.create_enabled',category:'Payments',label:'Création des paiements réels',type:'boolean',env:'PAYMENTS_CREATE_ENABLED',default:false,description:'Garde-fou global pour les fournisseurs automatiques. Laisser désactivé en test.'},
 {key:'payments.manual_create_enabled',category:'Payments',label:'Création des références de paiement manuel',type:'boolean',env:'MANUAL_PAYMENTS_CREATE_ENABLED',default:false,description:'Garde-fou séparé pour Zelle/virement manuel. Désactivé par défaut.'},
 {key:'payments.refunds_execute_enabled',category:'Payments',label:'Exécution réelle des remboursements',type:'boolean',env:'REFUNDS_EXECUTION_ENABLED',default:false,description:'SUPER_ADMIN uniquement. Désactivé = workflow/approbation sans appel provider.'},
 {key:'payments.auto_ttl_minutes',category:'Payments',label:'Expiration lien automatique (min)',type:'number',default:15,min:5,max:120},
 {key:'payments.manual_ttl_minutes',category:'Payments',label:'Expiration paiement manuel (min)',type:'number',default:30,min:5,max:240},
 {key:'payments.manual_receipt_ocr_enabled',category:'Payments',label:'OCR des reçus manuels',type:'boolean',env:'MANUAL_RECEIPT_OCR_ENABLED',default:false,description:'Extraction/comparaison seulement. Ne confirme jamais un paiement automatiquement.'},
 {key:'payments.mx_paypal_enabled',category:'Payments',label:'PayPal au Mexique',type:'boolean',env:'PAY_MX_ENABLE_PAYPAL',default:false},
 {key:'payments.stripe_secret_key',category:'Payments',label:'Stripe secret key',type:'secret',env:'STRIPE_SECRET_KEY'},
 {key:'payments.stripe_webhook_secret',category:'Payments',label:'Stripe webhook secret',type:'secret',env:'STRIPE_WEBHOOK_SECRET'},
 {key:'payments.mercadopago_access_token',category:'Payments',label:'Mercado Pago access token',type:'secret',env:'MERCADOPAGO_ACCESS_TOKEN'},
 {key:'payments.paypal_client_id',category:'Payments',label:'PayPal client ID',type:'secret',env:'PAYPAL_CLIENT_ID'},
 {key:'payments.paypal_client_secret',category:'Payments',label:'PayPal client secret',type:'secret',env:'PAYPAL_CLIENT_SECRET'},
 {key:'payments.paypal_mode',category:'Payments',label:'PayPal mode',type:'select',env:'PAYPAL_MODE',default:'sandbox',options:['sandbox','live']},
 {key:'payments.paypal_webhook_id',category:'Payments',label:'PayPal webhook ID',type:'secret',env:'PAYPAL_WEBHOOK_ID'},
 {key:'payments.bazik_webhook_secret',category:'Payments',label:'Bazik webhook secret',type:'secret',env:'BAZIK_WEBHOOK_SECRET'},
 {key:'payments.bazik_user_id',category:'Payments',label:'Bazik user ID',type:'secret',env:'BAZIK_USER_ID'},
 {key:'payments.bazik_secret_key',category:'Payments',label:'Bazik secret key',type:'secret',env:'BAZIK_SECRET_KEY'},
 {key:'payments.zelle_email',category:'Payments',label:'Zelle email',type:'text',env:'ZELLE_EMAIL'},
 {key:'payments.zelle_phone',category:'Payments',label:'Zelle téléphone',type:'text',env:'ZELLE_PHONE'},
 {key:'payments.us_bank_instructions',category:'Payments',label:'Instructions virement USA',type:'text',env:'US_BANK_INSTRUCTIONS'},
 {key:'fx.openexchangerates_app_id',category:'FX',label:'OpenExchangeRates App ID',type:'secret',env:'OPENEXCHANGERATES_APP_ID'},
 {key:'ticketing.write_enabled',category:'Ticketing',label:'Émission manuelle activée',type:'boolean',env:'TICKETING_WRITE_ENABLED',default:false,description:'Autorise uniquement l’émission manuelle. Laisser désactivé hors fenêtre contrôlée.'},
 {key:'ticketing.delivery_enabled',category:'Ticketing',label:'Livraison billet au client activée',type:'boolean',env:'TICKETING_DELIVERY_ENABLED',default:false,description:'Garde-fou séparé pour WhatsApp/e-mail. Désactivé par défaut.'},
 {key:'email.brevo_api_key',category:'Email',label:'Brevo API key',type:'secret',env:'BREVO_API_KEY'},
 {key:'email.sender_email',category:'Email',label:'Email expéditeur',type:'text',env:'BREVO_SENDER_EMAIL'},
 {key:'email.sender_name',category:'Email',label:'Nom expéditeur',type:'text',default:'DONI Travel'},
 {key:'ocr.enabled',category:'OCR',label:'OCR passeport actif',type:'boolean',env:'PASSPORT_OCR_ENABLED',default:false},
 {key:'ocr.anthropic_api_key',category:'OCR',label:'Anthropic API key',type:'secret',env:'ANTHROPIC_API_KEY'},
 {key:'ocr.model',category:'OCR',label:'Modèle OCR',type:'text',env:'DONI_OCR_MODEL',default:'claude-haiku-4-5-20251001'},
 {key:'app.public_url',category:'General',label:'URL publique DONI',type:'text',env:'PUBLIC_APP_URL'},
 {key:'app.name',category:'General',label:'Nom de la plateforme',type:'text',default:'DONI Travel'},
 {key:'app.support_email',category:'General',label:'Email assistance client',type:'text',env:'DONI_SUPPORT_EMAIL'},
 {key:'app.support_phone',category:'General',label:'Téléphone assistance client',type:'text',env:'DONI_SUPPORT_PHONE'},
 {key:'conversation.inactivity_reset_minutes',category:'General',label:'Reset après inactivité (min)',type:'number',default:30,min:5,max:240},
 {key:'conversation.stale_hours',category:'General',label:'Session périmée après (heures)',type:'number',default:72,min:12,max:720},
];
export const SETTING_BY_KEY=new Map(SETTINGS.map(x=>[x.key,x]));
