import {db} from '@/lib/db';
import {SETTING_BY_KEY,SETTINGS} from './catalog';
import {decryptSecret,encryptSecret} from './crypto';
function envValue(env?:string){return env?process.env[env]:undefined;}
function coerce(v:any,t:string){if(t==='boolean')return v===true||v==='true'||v==='1';if(t==='number')return Number(v);return v==null?'':String(v);}
export async function getSetting<T=unknown>(key:string):Promise<T>{const def=SETTING_BY_KEY.get(key);if(!def)throw new Error(`unknown_setting:${key}`);const row:any=await (db as any).appSetting.findUnique({where:{key}}).catch(()=>null);if(row){if(def.type==='secret'&&row.encryptedValue)return decryptSecret(row.encryptedValue) as T;if(row.value!==null&&row.value!==undefined)return row.value as T;}const ev=envValue(def.env);if(ev!==undefined)return coerce(ev,def.type) as T;return def.default as T;}
export async function hasSetting(key:string):Promise<boolean>{const def=SETTING_BY_KEY.get(key);if(!def)return false;const row:any=await (db as any).appSetting.findUnique({where:{key}}).catch(()=>null);if(def.type==='secret')return !!row?.encryptedValue||!!envValue(def.env);return !!((row?.value!==null&&row?.value!==undefined)||envValue(def.env)!==undefined||def.default!==undefined);}
export async function saveSetting(key:string,value:any,userId?:string){const def=SETTING_BY_KEY.get(key);if(!def)throw new Error(`unknown_setting:${key}`);if(def.type==='number'){const n=Number(value);if(!Number.isFinite(n))throw new Error('invalid_number');if(def.min!==undefined&&n<def.min)throw new Error('below_min');if(def.max!==undefined&&n>def.max)throw new Error('above_max');value=n;}if(def.type==='boolean')value=!!value;if(def.type==='select'&&!def.options?.includes(String(value)))throw new Error('invalid_option');if(def.type==='secret'){if(value===''||value===null||value===undefined)return;await (db as any).appSetting.upsert({where:{key},create:{key,category:def.category,isSecret:true,encryptedValue:encryptSecret(String(value)),updatedBy:userId},update:{category:def.category,isSecret:true,encryptedValue:encryptSecret(String(value)),updatedBy:userId}});return;}await (db as any).appSetting.upsert({where:{key},create:{key,category:def.category,value:value as any,isSecret:false,updatedBy:userId},update:{category:def.category,value:value as any,isSecret:false,updatedBy:userId}});}
export async function clearSetting(key:string){await (db as any).appSetting.delete({where:{key}}).catch(()=>null);}
export async function settingsSnapshot(){const rows:any[]=await (db as any).appSetting.findMany().catch(()=>[]);const map=new Map<string,any>(rows.map((r:any)=>[r.key,r]));return SETTINGS.map(def=>{const row:any=map.get(def.key);const env=envValue(def.env);const value:any=def.type==='secret'?undefined:(row?.value ?? (env!==undefined?coerce(env,def.type):def.default));const configured=def.type==='secret'?!!row?.encryptedValue||!!env:(row?.value!==null&&row?.value!==undefined)||env!==undefined||def.default!==undefined;return {...def,value,configured,source:row?'database':env!==undefined?'environment':def.default!==undefined?'default':'missing',secretStored:!!row?.encryptedValue};});}
