import {redirect} from 'next/navigation';
import {DoniShell} from '@/components/DoniShell';
import {requirePageUser} from '@/lib/auth/session';
import {canAccessMarketing} from '@/lib/auth/marketing-access';
import {getMarketingLearningLoop} from '@/lib/workspace/marketing-learning-loop';
export const dynamic='force-dynamic';
function label(v:string){return ({EXCELLENT:'Excellent',GOOD:'Bon',WATCH:'À surveiller',WEAK:'Faible'} as Record<string,string>)[v]||v;}
export default async function Page(){const user=await requirePageUser('AGENT');if(!canAccessMarketing(user))redirect('/overview?forbidden=1');const data=await getMarketingLearningLoop();return <DoniShell title="Marketing Learning Loop" active="/marketing/learning-loop" user={user}>
<section className="workspaceWelcome"><div><span className="workspaceKicker">Marketing V2 · Boucle d’apprentissage</span><h2>Learn from real outcomes</h2><p>DONI compare livraison, lecture, réponse et conversion pour identifier les campagnes à reproduire ou à corriger. Les recommandations restent consultatives et nécessitent une décision humaine.</p></div></section>
<div className="marketingKpis"><div className="card"><span>Campagnes suivies</span><strong>{data.summary.campaigns}</strong></div><div className="card"><span>Échantillon mature</span><strong>{data.summary.mature}</strong><small>≥ 5 envois</small></div><div className="card"><span>Gagnantes</span><strong>{data.summary.winners}</strong></div><div className="card"><span>À optimiser</span><strong>{data.summary.needsWork}</strong></div><div className="card"><span>Score global</span><strong>{data.summary.globalScore}/100</strong></div><div className="card"><span>Mode</span><strong>Conseil</strong><small>Aucune action automatique</small></div></div>
<section className="card learningAdvice"><div className="searchIntelHead"><div><span>Priorités</span><h3>Recommandations globales</h3></div><small>Données réelles uniquement</small></div><div className="learningAdviceList">{data.globalRecommendations.map((x,i)=><div key={i}><strong>{i+1}</strong><p>{x}</p></div>)}</div></section>
<section className="card learningCampaigns"><div className="searchIntelHead"><div><span>Scorecard</span><h3>Performance par campagne</h3></div><small>Score pondéré conversion & engagement</small></div><div className="learningRows">{data.campaigns.map((x:any)=><article className="learningRow" key={x.itemId}><div><span className="publisherStatus">{label(x.level)}</span><h4>{x.title}</h4><small>{x.route||x.destination||x.source||x.itemId}</small></div><div><span>Score</span><strong>{x.score}/100</strong><small>{x.sent} envoi{x.sent>1?'s':''}</small></div><div><span>Lu</span><strong>{x.readRate}%</strong><small>Livré {x.deliveredRate}%</small></div><div><span>Réponse</span><strong>{x.replyRate}%</strong><small>Échec {x.failureRate}%</small></div><div><span>Conversion</span><strong>{x.conversionRate}%</strong><small>{x.converted} conversion{x.converted>1?'s':''}</small></div><div className="learningRecommendation"><span>Action recommandée</span><small>{x.recommendations[0]}</small></div></article>)}</div></section>
</DoniShell>}
