import {redirect} from 'next/navigation';
import {DoniShell} from '@/components/DoniShell';
import {requirePageUser} from '@/lib/auth/session';
import {hasRole} from '@/lib/auth/permissions';
import {getMarketingPhase1Dashboard} from '@/services/workspace/marketing-phase1';
export const dynamic='force-dynamic';
function pct(value:number,target:number){return target?Math.min(100,Math.round(value/target*100)):0}
function Goal({label,value,target,unit=''}:{label:string;value:number;target:number;unit?:string}){const p=pct(value,target);return <div className="marketingGoal"><div><span>{label}</span><strong>{value}{unit} <small>/ {target}{unit}</small></strong></div><div className="marketingGoalTrack"><i style={{width:`${p}%`}}/></div><small>{p}% de l'objectif minimum</small></div>}
export default async function Page(){const user=await requirePageUser('AGENT');if(!hasRole(user.role,'ADMIN')&&user.department!=='MARKETING')redirect('/overview?forbidden=1');const d=await getMarketingPhase1Dashboard();return <DoniShell title="Objectifs marketing" active="/marketing/objectives" user={user}><section className="workspaceWelcome"><div><span className="workspaceKicker">Plan Doni Travel</span><h2>Objectifs jour / semaine / mois</h2><p>Les objectifs du guide sont affichés séparément des résultats réels. Aucun résultat n'est simulé.</p></div></section><div className="marketingGoalColumns"><section className="card marketingGoalPanel"><h3>Aujourd'hui</h3><Goal label="Nouveaux prospects" value={d.metrics.dayLeads} target={d.goals.daily.leadsMin}/><Goal label="Contenus publiés" value={d.metrics.dayPublished} target={d.goals.daily.publicationsMin}/><div className="marketingManualGoal"><span>Temps de réponse</span><strong>&lt; {d.goals.daily.responseMinutes} min</strong><small>Mesure à connecter aux canaux marketing.</small></div></section><section className="card marketingGoalPanel"><h3>Cette semaine</h3><Goal label="Prospects" value={d.metrics.weekLeads} target={d.goals.weekly.leadsMin}/><Goal label="Publications" value={d.metrics.weekPublished} target={d.goals.weekly.publicationsMin}/><Goal label="Conversions" value={d.metrics.weekSales} target={d.goals.weekly.salesMin}/><div className="marketingManualGoal"><span>Vidéos</span><strong>Objectif {d.goals.weekly.videos}</strong><small>Le type Reel/TikTok est suivi dans le calendrier.</small></div></section><section className="card marketingGoalPanel"><h3>Ce mois</h3><Goal label="Prospects" value={d.metrics.monthLeads} target={d.goals.monthly.leadsMin}/><Goal label="Conversions" value={d.metrics.monthSales} target={d.goals.monthly.salesMin}/><div className="marketingManualGoal"><span>ROI publicitaire</span><strong>≥ {d.goals.monthly.roiTarget}</strong><small>Connexion budget/Ads prévue en Phase 2.</small></div><div className="marketingManualGoal"><span>Partenariat</span><strong>{d.goals.monthly.partnerships} / mois</strong><small>Module Partenariats prévu ultérieurement.</small></div></section></div></DoniShell>}
