import {redirect} from 'next/navigation';
import Link from 'next/link';
import {DoniShell} from '@/components/DoniShell';
import {requirePageUser} from '@/lib/auth/session';
import {hasRole} from '@/lib/auth/permissions';
import {getManagementWorkCenter} from '@/services/workspace/work-centers';
import {getOverviewMetrics,getFinanceMetrics} from '@/services/analytics/dashboard';
import {MetricCard} from '@/components/analytics/MetricCard';
import {WorkCenterHeader,WorkQueue} from '@/components/workspace/WorkQueue';
import {AutoRefresh} from '@/components/analytics/AutoRefresh';
export const dynamic='force-dynamic';
function money(n:number,c:string){try{return new Intl.NumberFormat('fr-FR',{style:'currency',currency:c,maximumFractionDigits:0}).format(n)}catch{return `${n.toFixed(0)} ${c}`}}
export default async function Page(){const user=await requirePageUser('ADMIN');if(!hasRole(user.role,'ADMIN'))redirect('/overview?forbidden=1');const w:any=await getManagementWorkCenter();const d=await getOverviewMetrics();const f=await getFinanceMetrics();return <DoniShell title="Direction" active="/management" user={user}><AutoRefresh seconds={30}/><WorkCenterHeader kicker="Direction & supervision" title="Cockpit exécutif DONI" description="Vue consolidée des risques opérationnels, files de travail et performance de l'agence." actions={[{label:'Utilisateurs',href:'/users'},{label:'Audit',href:'/audit'}]}/><div className="grid"><MetricCard label="Équipe active" value={w.users}/><MetricCard label="Conversations actives" value={w.activeConversations} tone={d.agentRequired?'warn':'good'} note={`${d.agentRequired} intervention(s) agent`}/><MetricCard label="Incidents vols" value={w.openIncidents} tone={w.openIncidents?'bad':'good'}/><MetricCard label="Billets à émettre" value={w.ticketsToIssue} tone={w.ticketsToIssue?'warn':'good'}/></div><div className="workCenterGrid"><WorkQueue title="Risques à superviser" note="Éléments qui nécessitent un responsable" items={[{key:'incidents',title:'Incidents Flight Ops',meta:`${w.openIncidents} incident(s) ouvert(s)`,href:'/flight-ops',tone:w.openIncidents?'bad' as const:'normal' as const,badge:String(w.openIncidents)},{key:'refunds',title:'Remboursements ouverts',meta:`${w.pendingRefunds} dossier(s)`,href:'/finance',tone:w.pendingRefunds?'warn' as const:'normal' as const,badge:String(w.pendingRefunds)},{key:'reviews',title:'Validations financières',meta:`${w.pendingReviews} reçu(s) à vérifier`,href:'/manual-payments',tone:w.pendingReviews?'warn' as const:'normal' as const,badge:String(w.pendingReviews)},{key:'tickets',title:'Ticketing',meta:`${w.ticketsToIssue} billet(s) à émettre`,href:'/ticketing',tone:w.ticketsToIssue?'warn' as const:'normal' as const,badge:String(w.ticketsToIssue)}]}/><section className="card executiveRevenue"><div className="workQueueHead"><div><h3>Encaissements · 7 jours</h3><p>Vue rapide par devise</p></div></div>{f.currencyTotals.length?f.currencyTotals.map(x=><div className="executiveMoney" key={x.currency}><span>{x.currency}</span><strong>{money(x.amount,x.currency)}</strong><small>{x.count} paiement(s)</small></div>):<div className="queueEmpty">Aucun encaissement.</div>}</section></div><h2 className="sectionTitle">Centres opérationnels</h2><div className="executiveLinks">{[['/reservations','Réservations','Ventes et dossiers clients'],['/service-client','Service client','Conversations et après-vente'],['/finance','Finance','Encaissements et remboursements'],['/ticketing','Ticketing','Émission et livraison'],['/flight-ops','Flight Ops','Vols et perturbations'],['/marketing','Marketing','Acquisition et conversion']].map(([href,label,note])=><Link href={href} className="executiveLink card" key={href}><strong>{label}</strong><span>{note}</span><b>›</b></Link>)}</div></DoniShell>}
