import {createCipheriv,createDecipheriv,createHash,randomBytes,createHmac,timingSafeEqual} from 'node:crypto';
import {db} from '@/lib/db';

const CATEGORY='Auth MFA';
const CHALLENGE_CATEGORY='Auth MFA Challenges';
const TOTP_PREFIX='auth.mfa.totp.';
const RECOVERY_PREFIX='auth.mfa.recovery.';
const CHALLENGE_PREFIX='auth.mfa.challenge.';
const STEP=30;
const DIGITS=6;
export type MfaMethod='PASSKEY'|'TOTP'|'RECOVERY';
const ALL_METHODS:MfaMethod[]=['PASSKEY','TOTP','RECOVERY'];

function encryptionKey(){
 const raw=process.env.AUTH_MFA_ENCRYPTION_KEY||'';
 if(!raw)throw new Error('mfa_encryption_key_missing');
 return createHash('sha256').update(raw).digest();
}
function encrypt(text:string){const iv=randomBytes(12),key=encryptionKey(),cipher=createCipheriv('aes-256-gcm',key,iv);const body=Buffer.concat([cipher.update(text,'utf8'),cipher.final()]);const tag=cipher.getAuthTag();return Buffer.concat([iv,tag,body]).toString('base64url');}
function decrypt(value:string){const data=Buffer.from(value,'base64url');const iv=data.subarray(0,12),tag=data.subarray(12,28),body=data.subarray(28);const decipher=createDecipheriv('aes-256-gcm',encryptionKey(),iv);decipher.setAuthTag(tag);return Buffer.concat([decipher.update(body),decipher.final()]).toString('utf8');}
const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
function base32Encode(input:Buffer){let bits=0,value=0,out='';for(const byte of input){value=(value<<8)|byte;bits+=8;while(bits>=5){out+=alphabet[(value>>>(bits-5))&31];bits-=5;}}if(bits>0)out+=alphabet[(value<<(5-bits))&31];return out;}
function base32Decode(input:string){const clean=input.replace(/=+$/,'').toUpperCase().replace(/\s+/g,'');let bits=0,value=0;const bytes:number[]=[];for(const c of clean){const idx=alphabet.indexOf(c);if(idx<0)continue;value=(value<<5)|idx;bits+=5;if(bits>=8){bytes.push((value>>>(bits-8))&255);bits-=8;}}return Buffer.from(bytes);}
function hotp(secret:string,counter:number){const key=base32Decode(secret);const buf=Buffer.alloc(8);buf.writeBigUInt64BE(BigInt(counter));const digest=createHmac('sha1',key).update(buf).digest();const offset=digest[digest.length-1]&15;const code=(digest.readUInt32BE(offset)&0x7fffffff)%10**DIGITS;return String(code).padStart(DIGITS,'0');}
export function verifyTotp(secret:string,code:string){const normalized=code.replace(/\D/g,'');if(normalized.length!==DIGITS)return false;const current=Math.floor(Date.now()/1000/STEP);for(let delta=-1;delta<=1;delta++){const expected=hotp(secret,current+delta);const a=Buffer.from(expected),b=Buffer.from(normalized);if(a.length===b.length&&timingSafeEqual(a,b))return true;}return false;}
function hashRecovery(userId:string,code:string){return createHash('sha256').update(`${userId}:${code.trim().toUpperCase()}`).digest('hex');}
function challengeKey(raw:string){return `${CHALLENGE_PREFIX}${createHash('sha256').update(raw).digest('hex')}`;}
function normalizeMethods(value:unknown):MfaMethod[]{if(!Array.isArray(value))return [...ALL_METHODS];const methods=value.filter((x):x is MfaMethod=>typeof x==='string'&&(ALL_METHODS as string[]).includes(x));return methods.length?methods:[...ALL_METHODS];}
export async function getTotpStatus(userId:string){const row=await db.appSetting.findUnique({where:{key:`${TOTP_PREFIX}${userId}`}});const v=row?.value as any;return {enabled:Boolean(v?.enabled&&row?.encryptedValue),confirmedAt:v?.confirmedAt||null};}
export async function beginTotpEnrollment(user:{id:string;username:string;email?:string|null}){const secret=base32Encode(randomBytes(20));const issuer='DONI';const label=encodeURIComponent(`${issuer}:${user.email||user.username}`);const uri=`otpauth://totp/${label}?secret=${secret}&issuer=${encodeURIComponent(issuer)}&algorithm=SHA1&digits=${DIGITS}&period=${STEP}`;await db.appSetting.upsert({where:{key:`${TOTP_PREFIX}${user.id}`},create:{key:`${TOTP_PREFIX}${user.id}`,category:CATEGORY,value:{enabled:false,pending:true,createdAt:new Date().toISOString()},encryptedValue:encrypt(secret),isSecret:true,updatedBy:user.id},update:{value:{enabled:false,pending:true,createdAt:new Date().toISOString()},encryptedValue:encrypt(secret),isSecret:true,updatedBy:user.id}});return {secret,uri};}
export async function confirmTotpEnrollment(userId:string,code:string){const key=`${TOTP_PREFIX}${userId}`;const row=await db.appSetting.findUnique({where:{key}});if(!row?.encryptedValue)throw new Error('totp_setup_not_started');const secret=decrypt(row.encryptedValue);if(!verifyTotp(secret,code))throw new Error('invalid_totp');const recovery=Array.from({length:10},()=>`${randomBytes(3).toString('hex').toUpperCase()}-${randomBytes(3).toString('hex').toUpperCase()}`);const hashes=recovery.map(c=>hashRecovery(userId,c));await db.$transaction([
 db.appSetting.update({where:{key},data:{value:{enabled:true,pending:false,confirmedAt:new Date().toISOString()},updatedBy:userId}}),
 db.appSetting.upsert({where:{key:`${RECOVERY_PREFIX}${userId}`},create:{key:`${RECOVERY_PREFIX}${userId}`,category:CATEGORY,value:{hashes,generatedAt:new Date().toISOString()},isSecret:true,updatedBy:userId},update:{value:{hashes,generatedAt:new Date().toISOString()},isSecret:true,updatedBy:userId}})
 ]);return recovery;}
export async function disableTotp(userId:string){await db.$transaction([db.appSetting.deleteMany({where:{key:`${TOTP_PREFIX}${userId}`}}),db.appSetting.deleteMany({where:{key:`${RECOVERY_PREFIX}${userId}`}})]);}
export async function verifyUserMfa(userId:string,code:string){const row=await db.appSetting.findUnique({where:{key:`${TOTP_PREFIX}${userId}`}});const v=row?.value as any;if(v?.enabled&&row?.encryptedValue&&verifyTotp(decrypt(row.encryptedValue),code))return {ok:true as const,method:'TOTP' as const};const recovery=await db.appSetting.findUnique({where:{key:`${RECOVERY_PREFIX}${userId}`}});const rv=recovery?.value as any;const hashes:Array<string>=Array.isArray(rv?.hashes)?rv.hashes:[];const wanted=hashRecovery(userId,code);const idx=hashes.findIndex(h=>h===wanted);if(idx>=0){const next=hashes.filter((_,i)=>i!==idx);await db.appSetting.update({where:{key:`${RECOVERY_PREFIX}${userId}`},data:{value:{...rv,hashes:next},updatedBy:userId}});return {ok:true as const,method:'RECOVERY' as const};}return {ok:false as const};}
export async function createMfaChallenge(userId:string,methods:MfaMethod[]=ALL_METHODS){const raw=randomBytes(32).toString('base64url'),expiresAt=new Date(Date.now()+10*60_000).toISOString();const allowed=normalizeMethods(methods);await db.appSetting.create({data:{key:challengeKey(raw),category:CHALLENGE_CATEGORY,value:{userId,expiresAt,attempts:0,methods:allowed},isSecret:true,updatedBy:userId}});return raw;}
export async function inspectMfaChallenge(raw:string){const key=challengeKey(raw);const row=await db.appSetting.findUnique({where:{key}});const v=row?.value as any;if(!row||!v?.userId||!v?.expiresAt)throw new Error('invalid_mfa_challenge');if(new Date(v.expiresAt)<=new Date()){await db.appSetting.delete({where:{key}}).catch(()=>{});throw new Error('mfa_challenge_expired');}const attempts=Number(v.attempts||0);if(attempts>=5){await db.appSetting.delete({where:{key}}).catch(()=>{});throw new Error('mfa_challenge_locked');}return {key,userId:String(v.userId),attempts,methods:normalizeMethods(v.methods),value:v};}
export async function assertMfaMethodAllowed(raw:string,method:MfaMethod){const current=await inspectMfaChallenge(raw);if(!current.methods.includes(method))throw new Error('mfa_method_not_allowed');return current;}
export async function recordMfaChallengeFailure(raw:string){const current=await inspectMfaChallenge(raw);await db.appSetting.update({where:{key:current.key},data:{value:{...current.value,attempts:current.attempts+1}}});}
export async function completeMfaChallenge(raw:string,userId:string){const current=await inspectMfaChallenge(raw);if(current.userId!==userId)throw new Error('invalid_mfa_challenge');await db.appSetting.delete({where:{key:current.key}}).catch(()=>{});return {userId};}
export async function consumeMfaChallenge(raw:string,code:string){const current=await inspectMfaChallenge(raw);const verified=await verifyUserMfa(current.userId,code);if(!verified.ok){await recordMfaChallengeFailure(raw);throw new Error('invalid_mfa_code');}if(!current.methods.includes(verified.method)){await recordMfaChallengeFailure(raw);throw new Error('mfa_method_not_allowed');}await completeMfaChallenge(raw,current.userId);return {userId:current.userId,method:verified.method};}
