import {db} from '@/lib/db';
import {generateAuthenticationOptions,generateRegistrationOptions,verifyAuthenticationResponse,verifyRegistrationResponse} from '@simplewebauthn/server';
import type {AuthenticationResponseJSON,RegistrationResponseJSON,AuthenticatorTransportFuture} from '@simplewebauthn/server';

const CATEGORY='Auth Passkeys';
const PASSKEY_PREFIX='auth.passkey.';
const REGISTER_CHALLENGE_PREFIX='auth.passkey.register.challenge.';
const LOGIN_CHALLENGE_PREFIX='auth.passkey.login.challenge.';

type StoredPasskey={id:string;userId:string;name:string;publicKey:string;counter:number;transports:AuthenticatorTransportFuture[];deviceType?:string;backedUp?:boolean;createdAt:string;lastUsedAt?:string|null};
function b64(v:Uint8Array){return Buffer.from(v).toString('base64url')}
function bytes(v:string){return new Uint8Array(Buffer.from(v,'base64url'))}
function hostFromOrigin(origin:string){return new URL(origin).hostname;}
export function webauthnConfig(req:Request){const origin=(process.env.AUTH_WEBAUTHN_ORIGIN||new URL(req.url).origin).replace(/\/$/,'');const rpID=process.env.AUTH_WEBAUTHN_RP_ID||hostFromOrigin(origin);return{origin,rpID,rpName:'DONI Travel Operations'};}
async function rowsForUser(userId:string){const rows=await db.appSetting.findMany({where:{category:CATEGORY,key:{startsWith:PASSKEY_PREFIX}},orderBy:{createdAt:'asc'}});return rows.map(r=>r.value as any).filter((v):v is StoredPasskey=>Boolean(v?.id&&v?.userId===userId&&v?.publicKey));}
export async function getPasskeyStatus(userId:string){const credentials=await rowsForUser(userId);return{enabled:credentials.length>0,count:credentials.length,credentials:credentials.map(x=>({id:x.id,name:x.name,createdAt:x.createdAt,lastUsedAt:x.lastUsedAt||null,deviceType:x.deviceType||null,backedUp:Boolean(x.backedUp)}))};}
async function saveChallenge(key:string,value:Record<string,unknown>,userId:string){await db.appSetting.upsert({where:{key},create:{key,category:CATEGORY,value:{...value,expiresAt:new Date(Date.now()+10*60_000).toISOString()},isSecret:true,updatedBy:userId},update:{value:{...value,expiresAt:new Date(Date.now()+10*60_000).toISOString()},isSecret:true,updatedBy:userId}});}
async function readChallenge(key:string){const row=await db.appSetting.findUnique({where:{key}});const v=row?.value as any;if(!v?.challenge||!v?.expiresAt||new Date(v.expiresAt)<=new Date()){if(row)await db.appSetting.delete({where:{key}}).catch(()=>{});throw new Error('passkey_challenge_expired');}return{row,v};}
export async function registrationOptions(req:Request,user:{id:string;username:string;fullName?:string|null;email?:string|null}){const cfg=webauthnConfig(req),existing=await rowsForUser(user.id);const options=await generateRegistrationOptions({rpName:cfg.rpName,rpID:cfg.rpID,userID:new TextEncoder().encode(user.id),userName:user.email||user.username,userDisplayName:user.fullName||user.username,attestationType:'none',excludeCredentials:existing.map(x=>({id:x.id,transports:x.transports})),authenticatorSelection:{residentKey:'preferred',userVerification:'required'},supportedAlgorithmIDs:[-7,-257],timeout:60000});await saveChallenge(`${REGISTER_CHALLENGE_PREFIX}${user.id}`,{challenge:options.challenge},user.id);return options;}
export async function verifyAndStoreRegistration(req:Request,userId:string,response:RegistrationResponseJSON,name?:string|null){const cfg=webauthnConfig(req),key=`${REGISTER_CHALLENGE_PREFIX}${userId}`,challenge=await readChallenge(key);const verification=await verifyRegistrationResponse({response,expectedChallenge:String(challenge.v.challenge),expectedOrigin:cfg.origin,expectedRPID:cfg.rpID,requireUserVerification:true});if(!verification.verified||!verification.registrationInfo)throw new Error('passkey_registration_failed');const info=verification.registrationInfo,credential=info.credential;const stored:StoredPasskey={id:credential.id,userId,name:String(name||'Passkey').trim().slice(0,80)||'Passkey',publicKey:b64(credential.publicKey),counter:credential.counter,transports:(credential.transports||[]) as AuthenticatorTransportFuture[],deviceType:info.credentialDeviceType,backedUp:info.credentialBackedUp,createdAt:new Date().toISOString(),lastUsedAt:null};await db.$transaction([db.appSetting.upsert({where:{key:`${PASSKEY_PREFIX}${credential.id}`},create:{key:`${PASSKEY_PREFIX}${credential.id}`,category:CATEGORY,value:stored as any,isSecret:true,updatedBy:userId},update:{value:stored as any,isSecret:true,updatedBy:userId}}),db.appSetting.deleteMany({where:{key}})]);return stored;}
export async function authenticationOptions(req:Request,mfaChallenge:string,userId:string){const cfg=webauthnConfig(req),credentials=await rowsForUser(userId);if(!credentials.length)throw new Error('passkey_not_configured');const options=await generateAuthenticationOptions({rpID:cfg.rpID,allowCredentials:credentials.map(x=>({id:x.id,transports:x.transports})),userVerification:'required',timeout:60000});await saveChallenge(`${LOGIN_CHALLENGE_PREFIX}${userId}`,{challenge:options.challenge,mfaChallenge},userId);return options;}
export async function verifyAuthentication(req:Request,mfaChallenge:string,userId:string,response:AuthenticationResponseJSON){const cfg=webauthnConfig(req),key=`${LOGIN_CHALLENGE_PREFIX}${userId}`,challenge=await readChallenge(key);if(challenge.v.mfaChallenge!==mfaChallenge)throw new Error('invalid_passkey_challenge');const credential=(await rowsForUser(userId)).find(x=>x.id===response.id);if(!credential)throw new Error('unknown_passkey');const verification=await verifyAuthenticationResponse({response,expectedChallenge:String(challenge.v.challenge),expectedOrigin:cfg.origin,expectedRPID:cfg.rpID,credential:{id:credential.id,publicKey:bytes(credential.publicKey),counter:credential.counter,transports:credential.transports},requireUserVerification:true});if(!verification.verified)throw new Error('passkey_authentication_failed');const next={...credential,counter:verification.authenticationInfo.newCounter,lastUsedAt:new Date().toISOString()};await db.$transaction([db.appSetting.update({where:{key:`${PASSKEY_PREFIX}${credential.id}`},data:{value:next as any,updatedBy:userId}}),db.appSetting.deleteMany({where:{key}})]);return{credentialId:credential.id};}
export async function deletePasskey(userId:string,credentialId:string){const key=`${PASSKEY_PREFIX}${credentialId}`,row=await db.appSetting.findUnique({where:{key}}),v=row?.value as any;if(!row||v?.userId!==userId)throw new Error('passkey_not_found');await db.appSetting.delete({where:{key}});}
