'use client';
import {startAuthentication} from '@simplewebauthn/browser';

export async function performStepUp(){const r=await fetch('/api/auth/step-up/start',{method:'POST'});const j=await r.json().catch(()=>({}));if(!r.ok||!j?.success)throw new Error(j?.error||'step_up_start_failed');const challenge=String(j.challenge||'');const methods:string[]=Array.isArray(j.methods)?j.methods:[];if(methods.includes('PASSKEY')){const o=await fetch('/api/auth/step-up/passkey/options',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({challenge})});const oj=await o.json().catch(()=>({}));if(!o.ok||!oj?.success)throw new Error(oj?.error||'passkey_options_failed');const response=await startAuthentication({optionsJSON:oj.options});const v=await fetch('/api/auth/step-up/passkey/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({challenge,response})});const x=await v.json().catch(()=>({}));if(!v.ok||!x?.success)throw new Error(x?.error||'passkey_step_up_failed');return true;}if(methods.includes('TOTP')||methods.includes('RECOVERY')){const code=window.prompt('Validation de sécurité requise. Entre ton code Google Authenticator ou un code de récupération.');if(!code)throw new Error('step_up_cancelled');const v=await fetch('/api/auth/step-up/code',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({challenge,code})});const x=await v.json().catch(()=>({}));if(!v.ok||!x?.success)throw new Error(x?.error||'step_up_failed');return true;}throw new Error('mfa_not_configured');}

async function performPasswordReauth(){const password=window.prompt('Confirme ton mot de passe DONI pour sécuriser l’activation de ton premier facteur.');if(!password)throw new Error('password_reauth_cancelled');const r=await fetch('/api/auth/reauth/password',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password})});const j=await r.json().catch(()=>({}));if(!r.ok||!j?.success)throw new Error(j?.error||'password_reauth_failed');return true;}

export async function fetchWithStepUp(input:RequestInfo|URL,init?:RequestInit){let r=await fetch(input,init);if(r.status!==428)return r;await performStepUp();r=await fetch(input,init);return r;}

export async function fetchForFactorChange(input:RequestInfo|URL,init?:RequestInit){let r=await fetch(input,init);if(r.status!==428)return r;const body=await r.clone().json().catch(()=>({}));if(body?.error==='password_reauth_required')await performPasswordReauth();else if(body?.error==='step_up_required')await performStepUp();else return r;return fetch(input,init);}
